### PR TITLE
use https for github repos

### PR DESCRIPTION
**Pull request by steckerhalter**
Use secure protocol (https) for github

### CODE REVIEW

**Comment by purcell** [comment]
I'm sure you've submitted this change for a good reason, but you haven't provided a word of information here about what that is, so it's hard for me to know how to handle this PR. :-)

**Comment by steckerhalter** [comment]
Sorry, I forgot to add the description. Since git:// is insecure it would be better to use https:// as it is the case already for the gitlab fetcher

**Comment by purcell** [comment]
Makes sense, thanks!

**Comment by milkypostman** [comment]
@purcell related to this I just added a rewrite to the server to change git@ to https:// paths. someone else  had mentioned this idea before and a submodule was breaking a recipe because it was using the git@ address.

**Comment by purcell** [comment]
Oh, a rewrite? How does that work?

**Comment by milkypostman** [comment]
It's a fit config thing. You tell it to rewrite any matching git url.

**Comment by purcell** [comment]
Aha! Clever.

**Pull request merged**
