### PR TITLE
Add semantic-refactor

### PR DESCRIPTION
**Pull request by tuhdo**
A refactoring package for C/C++ based on Semantic parser framework.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

The package cannot be called `semantic-refactor` if the code inside it is called `srefactor`, so the recipe filename and the package name in the recipe file will both need to be changed.

Additionally, please remove the `:files` spec from this recipe: the default already includes "*.el".

Ideally, you should amend the commit as necessary and force-push it back here to keep the PR commit history clean.

-Steve

**Comment by tuhdo** [comment]
Thanks for reviewing.

But isn't [emr](https://github.com/chrisbarrett/emacs-refactor) also a case? I mean, `srefactor` is just an abbreviation. [function-arguments](https://github.com/abo-abo/function-args) also uses `fa` as its prefix name and more packages.

**Comment by tuhdo** [comment]
is it ok if I rename `srefactor` to `sr`?

**Comment by purcell** [comment]
> But isn't emr also a case? I mean, srefactor is just an abbreviation.

You're missing my point. In `emr`, the package is called `emr` and the file is called `emr`, so they match. Here, you have `semantic-refactor` and `srefactor`, which do not match.

> function-arguments also uses fa as its prefix name and more packages.

That's a different situation, because the `function-args` package name matches the `function-args.el` filename. However, yes, it uses the prefix `fa-` internally, which is simply a bad idea.

> is it ok if I rename srefactor to sr?

If you mean the package name, please don't. Descriptive names are better than cute abbreviations. Similarly, renaming the symbols like that to save a few characters it not smart in my view, and also breaks the [official elisp coding conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html). So please don't do that either. :-)

**Comment by tuhdo** [comment]
@purcell Thanks for the advice. I updated it.

**Comment by purcell** [comment]
Great, thanks!

**Pull request merged**
