### PR TITLE
Fix :fetcher of recipes that used a string as value

### PR DESCRIPTION
**Pull request by tarsius**
While comparing the sets of Emacswiki packages on Melpa and the Emacsmirror (more on that later), I came across these errors.

### CODE REVIEW

**Comment by milkypostman** [comment]
How is this working now?  Lol.

**Comment by Fanael** [comment]
> How is this working now? Lol.

There's nothing in `package-build.el` that would require `:fetcher` to be a symbol. In fact, `:fetcher (1234 [5678 9012] #s(hash-table test eq data (1 2 3 4)) "abcd")` is accepted just fine, `format`, the only user of this value, doesn't mind.

**Comment by purcell** [comment]
Yikes. We should add a check on the types, or at least ensure that the specified fetcher is one of a known list.

**Comment by purcell** [comment]
Ah, saw #2338 - thanks @Fanael.

**Pull request merged**
