### PR TITLE
Added recipe for ‘kill-or-bury-alive’

### PR DESCRIPTION
**Pull request by mrkkrp**
This package slowly evolved in my init file as collection of helper functions and I've decided that it may be useful for others too. I tried to find something similar, but I couldn't. The closest thing that comes to mind is `unkillable-scratch`, but it's not quite a match for `kill-or-bury-alive`.

Maybe you know of some package to control buffer killing?

Here's my stuff:

https://github.com/mrkkrp/kill-or-bury-alive

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, added. I think there *might* be a little overlap with the built-in `midnight` mode. For example, if people have marked buffers as killable by `midnight`, then it would perhaps be reasonable for `kill-or-bury-alive` to kill them immediately. Just a thought.

**Comment by mrkkrp** [comment]
Steve, can I ask your opinion? I have a list of default "long lasting" buffers [here](https://github.com/mrkkrp/kill-or-bury-alive/blob/master/kill-or-bury-alive.el#L68-L72). But it turns out that such defaults values don't play well with autoload. I mean when user tweaks the variables in his/her init file, package itself isn't loaded, so these variables don't exist in List environment. It's OK for simple `setq`able things, but for this sort of list it maybe poor choice, because if users modifies the list defaults will be lost (as far as I know from my investigation). I was advised to use `eval-after-load` to append defaults of list that might be formed by user before loading of the package, but then it's impossible for use to delete items from the list, I guess. Should I just abandon the idea of default values in a list?

**Comment by purcell** [comment]
What you're doing is pretty much fine, although you should use `defcustom` instead of `defvar`. Just keep it simple. If you try to be too clever about this, you'll end up accidentally overwriting users' preferences in some circumstances. :-)

**Comment by purcell** [comment]
(All of those user-settable `defvar`s should be `defcustom`s, together with a containing `defgroup`.)

**Pull request merged**
