### PR TITLE
Add evil-visual-mark recipe

### PR DESCRIPTION
**Pull request by roman**
http://github.com/roman/evil-visual-mark-mode

### CODE REVIEW

**Comment by roman** [comment]
ping

**Comment by purcell** [comment]
Sorry, I must have missed this. Some feedback:

- The package name must match the file name, which it doesn't here: you've got `evil-visual-mark` vs. `evil-visual-mark-mode.el`
- You should remove the `:files` spec from the recipe: it's unnecessary here. Ideally, amend the recipe commit and force-push it here to keep the history clean.
- `evil-visual-marker-face` should be `evil-visual-mark-face`, to keep a consistent namespace prefix
- You're missing a `Package-Requires` dependency on `evil`.
- Consider adding an `;;;###autoload` cookie comment on the line before the minor mode definition

Hope that helps. :-)

**Comment by roman** [comment]
@purcell thank you very much for the comments, love how you take the time to do a review.

Keep the great work.

**Comment by purcell** [comment]
Thanks. I missed a couple of other points, and sent you a quick PR to fix them up: https://github.com/roman/evil-visual-mark-mode/pull/2

**Pull request closed without merging**
