### PR TITLE
add flycheck-protobuf

### PR DESCRIPTION
**Pull request by edvorg**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. I think you'll need to `(require 'flycheck)` in order for it to byte-compile cleanly for all users, and you should also declare a package dependency on the latest stable version of `flycheck`, of course.

**Comment by purcell** [comment]
Additionally, the suggestion that users should call `flycheck-select-checker` is not the best plan: they should never need to call that themselves. I think you should instead include a line which says:

```
(add-to-list 'flycheck-checkers 'protobuf-protoc-reporter t)
```

then tell users to configure the package like this:

```
(eval-after-load 'flycheck
  '(require 'flycheck-protobuf))
```

Flycheck will then take care of enabling the checker when appropriate.

**Comment by edvorg** [comment]
Thanks, fixed.

**Comment by purcell** [comment]
Sorry, I meant that you should put the `(add-to-list ...)` form in the `.el` file itself, then the `(eval-after-load ...)` form will be sufficient for users.

**Comment by purcell** [comment]
But anyway, I can merge this in the meantime.

**Comment by edvorg** [comment]
Thanks. I will fix it soon.

**Pull request merged**
