### PR TITLE
Add ahungry-theme to recipes

### PR DESCRIPTION
**Pull request by ahungry**
Bright colored dark theme I created for emacs.

https://github.com/ahungry/color-theme-ahungry

I am the maintainer and tested the melpa builds locally (they worked, I think).

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this. I'm happy to see that `flycheck-package` helped you fill in the metadata correctly. You might want to add a `;; Package-Requires: ((emacs "24"))`, since only Emacs 24 has reliable `deftheme` functionality.

There's an issue in that the result of `display-graphic-p` depends on the current frame at the time the code is executed, so it would not work properly if, say, Emacs is started in GUI mode and then a terminal frame is created using `emacsclient`, or vice versa. So the definition of the theme will vary according to when/how the theme is loaded, and will sometimes be wrong.

**Comment by milkypostman** [comment]
Cool theme.

**Comment by ahungry** [comment]
Thanks for the suggestion - added the Package-Requires for emacs 24 in there.

Regarding the call to #'display-graphic-p, I use that to set it to "default" in non-windowed mode, which causes emacs to avoid painting the background (hence leaving a transparent terminal transparent), but paint it gray in GUI mode.

I am able to reproduce the issue you mentioned (it will cause the background in a windowed emacsclient attached to a non-windowed daemon to remain white/unpainted).

Even with this possible inconsistency, I think it is better to leave it as is (maybe I need a note about the potential issue in the commentary somewhere?)

As the terminal transparency is more important than the gray background, I don't wish to call a consistent color (I think most users would choose either emacs or emacs -nw mode, even with the daemon/client set up).

On my desktop that I use emacs daemon with emacsclient GUI, I have a call to (setenv "DISPLAY" ":0.0") in my ~/.emacs, to make sure that the daemon knows it has a display when it fires up (even if started with the window manager).

Do you think it is OK as it is?  (will it hinder acceptance to Melpa)?

**Comment by purcell** [comment]
> Regarding the call to #'display-graphic-p, I use that to set it to "default" in non-windowed mode, which causes emacs to avoid painting the background (hence leaving a transparent terminal transparent), but paint it gray in GUI mode.
> 
> I am able to reproduce the issue you mentioned (it will cause the background in a windowed emacsclient attached to a non-windowed daemon to remain white/unpainted).

To reproduce, I'd try firing up a GUI frame, then load the theme in it. Next, create a terminal frame on the Emacs instance using `emacsclient` -- the background should be non-default in that terminal frame.

> Even with this possible inconsistency, I think it is better to leave it as is (maybe I need a note about the potential issue in the commentary somewhere?)

Yes, might be good.

> Do you think it is OK as it is? (will it hinder acceptance to Melpa)?

It's not really an issue for MELPA. I take the opportunity to review packages when they're submitted, because if there are significant potential issues for users, it's better for everyone if they're fixed before wider distribution of the code. But this isn't a major issue IMO, just something to bear in mind.

**Pull request merged**
