### PR TITLE
quasi-monochrome-theme recipe

### PR DESCRIPTION
**Pull request by lbolla**
Recipe for quasi-monochrome-theme.

### CODE REVIEW

**Comment by purcell** [comment]
Did you actually try building that? The repo name in the recipe doesn't exist.

**Comment by xuchunyang** [comment]
Real repo link: https://github.com/lbolla/emacs-quasi-monochrome

**Comment by purcell** [comment]
Please amend the commit and force-push it after testing locally that it builds okay. :-)

**Comment by lbolla** [comment]
Oh, very sorry about this! I did not know there was a "build" command I could run. Amended.

**Comment by purcell** [comment]
Great, that's better, but you'll also need to add the standard elisp boilerplate comments so that the package has metadata: as it stands, the code is not a valid package. [Here's a good example](https://github.com/cryon/subatomic/blob/master/subatomic-theme.el). Note in particular that there's a [special incantation](https://github.com/cryon/subatomic/blob/master/subatomic-theme.el#L988-L992) you can add in order to make the theme loadable when installed as a package.

**Comment by lbolla** [comment]
Thanks a lot for your help! I've amended the theme adding the comments as requested:
https://github.com/lbolla/emacs-quasi-monochrome/commit/a40a889e9c8d3c3556b42ae27d577cbb1582e2d8

**Comment by purcell** [comment]
Perfect - thanks!

**Pull request merged**
