### PR TITLE
Adding memento to recipes list.

### PR DESCRIPTION
**Pull request by ReneFroger**

### CODE REVIEW

**Comment by ReneFroger** [comment]
I'm not sure the pull request is visible for you now?

**Comment by purcell** [comment]
Thanks. I'd advise a couple of fixes upstream (cc @ehartc :-)) before we merge this:
- I don't think `:type 'memento` is valid for the first `defcustom` - it was probably meant to be `:group 'memento`
- And that group should be declared with `defgroup`
- There's a `write-log` function which doesn't have the correct `memento-` namespace prefix
- `memento-hook` isn't a great name for a function: it indicates a variable with a list of functions. Just `memento` would be a better name
- Don't add this to `kill-emacs-hook` -- let the user decide how/when to call `memento`. By all means *suggest* this mechanism to the user.

Hope that helps!

**Comment by ReneFroger** [comment]
@purcell The contents of the package Memento are changed on your advice. The purpose of Memento lies in the exit of Emacs, which is sometimes at the end of the day, and not in the middle of coding session. There is a variable added, to disable Memento on the exit. 

Could you tell me this is available in MELPA?

**Comment by purcell** [comment]
Merged, thanks.

**Comment by Fanael** [comment]
The lack of license on this package makes me kinda nervous. IANAL, but I doubt it's legal for it to be redistributed via MELPA.

**Comment by purcell** [comment]
True. @ehartc - please can you add a licence declaration somewhere?

**Pull request merged**
