### PR TITLE
Add spacemacs theme

### PR DESCRIPTION
**Pull request by nashamri**
### Summary
A color theme for emacs.

### Link
https://github.com/nashamri/spacemacs-theme

### Association
Author.

---
Cheers!

### CODE REVIEW

**Comment by purcell** [comment]
You should avoid calling the common code file `spacemacs-theme`: with that name, it will show up in the list of loadable themes, whereas what you want is for just the `light` and `dark` variants to show up there. Try using `spacemacs-common.el` instead.

**Comment by purcell** [comment]
(Looks great, by the way!)

**Comment by nashamri** [comment]
Thanks steve, that was a rookie mistake :+1: and indeed I am one. Hope it's working fine now. I tested it locally and it seems it okay. It only show `spacemacs-dark` & `spacemacs-light` in the list of themes.

**Comment by purcell** [comment]
No problem. Now, I could merge this, but I thought of another possibility: if you call that file `spacemacs-themes.el`, then you could use that as the package name, and throw away the `-pkg.el` file -- the metadata could just live in the `spacemacs-themes.el` headers. Might be a bit neater overall. Let me know which you prefer.

**Comment by nashamri** [comment]
Thanks Steve for the feedback :smile: . I like the idea of getting rid of the `-pkg-el` file but to me I think renaming the package to `spacemacs-themes` gives the idea of having more than one theme. While in reality, it's only one theme with two variants, like solarized theme for example.
So I think I'll stick with the current approach.
Cheers! :beer:

**Comment by purcell** [comment]
Cool, merged - thanks.

**Pull request merged**
