### PR TITLE
added kooten-theme

### PR DESCRIPTION
**Pull request by kootenpv**

### CODE REVIEW

**Comment by milkypostman** [comment]
@purcell still adding themes here? Do you think we should spawn a separate repo for those? I guess it doesn't matter.

**Comment by kootenpv** [comment]
@milkypostman  I was indeed confused; it seems weird to upload a theme into the package manager. Is there a better way to do it?

**Comment by milkypostman** [comment]
oh no, it makes sense but just that lots of packages we have are themes. it
has been discussed before to maybe not make them part of the main package
repo but not many other choices.

**Comment by purcell** [comment]
It's fine, but I sent a small fix in https://github.com/kootenpv/emacs-kooten-theme/pull/1.

**Comment by kootenpv** [comment]
@milkypostman @purcell Can this still be merged after having merged purcell's changes?

**Comment by purcell** [comment]
yup, done

**Pull request merged**
