### PR TITLE
Add ocodo-svg-modelines

### PR DESCRIPTION
**Pull request by jasonm23**
https://github.com/ocodo/ocodo-svg-modelines

### CODE REVIEW

**Comment by jasonm23** [comment]
Ahh... this is wrong. I need to update the recipe for multi files

**Comment by jasonm23** [comment]
Please advise if this is the correct multi-file format for including `images/*.base64` and `*.el`

**Comment by purcell** [comment]
Yes, this is basically right, but `(:defaults ("images" "images/*.base64"))` would be preferable, since `:defaults` includes `"*.el"` but is more future-proof.

**Comment by jasonm23** [comment]
Ok I'll fix that.  

I just realised that git archive --format=tar isn't a compatible tar for emacs... 

did you know this (am I wrong!?)

**Comment by jasonm23** [comment]
Updated

**Comment by purcell** [comment]
Great, thanks. Just noticed your `Package-Requires` line is invalid: version number is mandatory. `flycheck-package` can help spot that sort of thing.

**Comment by purcell** [comment]
(Use latest stable version, if any, otherwise something like `"1"` or `"0"` - avoid depending on snapshot versions.)

**Comment by jasonm23** [comment]
Updated

**Comment by purcell** [comment]
:+1:

**Pull request merged**
