### PR TITLE
Remove helm-c-yasnippet.

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
I have also removed helm-c-yasnippet from emacs-helm.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Probably I can now close this as the maintainer of package have moved the package somewhere else.

**Comment by milkypostman** [comment]
Do we need to fix the repo in the recipe?

**Comment by purcell** [comment]
@milkypostman That was done in #3160, I believe, so just assume we're all set here unless someone says otherwise. :-)

**Comment by milkypostman** [comment]
the description in this PR was confusing me :)

**Comment by thierryvolpiatto** [comment]
Sorry for confusing you, the maintainer of this package asked me to move it outside of emacs-helm, so I did and BTW I also wanted to remove it from here, but at the same time he provided the package from somewhere else...
Thanks to you and steve anyway ;-)

**Comment by milkypostman** [comment]
np

On Sat, Oct 3, 2015 at 10:38 AM, Thierry Volpiatto <notifications@github.com

**Pull request closed without merging**
