### PR TITLE
Add recipe `helm-bundle-show`

### PR DESCRIPTION
**Pull request by masutaka**
`helm-bundle-show.el` is `$ bundle show` with helm interface

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Pending https://github.com/masutaka/emacs-helm-bundle-show/pull/1.

**Comment by masutaka** [comment]
Thanks a lot. I've just merged!

**Comment by purcell** [comment]
Great, added. Thanks!

**Comment by masutaka** [comment]
Welcome! :sushi:

**Pull request merged**
