### PR TITLE
Add recipe for totd

### PR DESCRIPTION
**Pull request by egh**
A little utility to display a daily tip.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You should add `(cl-lib "0.5")` to the `Package-Requires` list.

**Comment by purcell** [comment]
P.S. I just added a `gitlab` fetcher shorthand, so this recipe could be written:

```el
(totd :fetcher gitlab :repo "egh/emacs-totd")
```

**Comment by egh** [comment]
Thanks, @purcell, I didn't realize cl-lib was a package. FIxed!

**Comment by egh** [comment]
Fixed.

**Comment by purcell** [comment]
Great, thanks! Merged.

**Comment by egh** [comment]
Thanks!

**Pull request merged**
