### PR TITLE
Add recipe for Pacmacs

### PR DESCRIPTION
**Pull request by rexim**
Just a Pacman-like clone for Emacs. :)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

`:files` could just be `(:defaults "maps" ("sprites" "sprites/*.json") ("sprites" "sprites/*.xpm"))`. Would you mind amending the recipe commit, testing it locally again (e.g. with `C-c C-c`) and force-pushing it back here?

Looks good otherwise. :-)

**Comment by rexim** [comment]
@purcell thanks for the remark! Done. :)

**Comment by purcell** [comment]
Super, thanks a lot. Merged.

**Comment by rexim** [comment]
Thank you! :)

**Pull request merged**
