### PR TITLE
add helm-mt recipe

### PR DESCRIPTION
**Pull request by dfdeshom**
Add helm-mt recipe, a package  to create and delete multi-term terminals easily with Helm.

Package repo link: https://github.com/dfdeshom/helm-mt

I am the author of the package.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You should declare a dependency on `(cl-lib "0.5")`, and also add `(require 'helm)` and `(require 'multi-term)` to eliminate byte compilation warnings.

(Tip: `flycheck`, together with `flycheck-package`, would have indicated those issues directly in the buffer. Definitely worth using.)

**Comment by dfdeshom** [comment]
Thanks! I added those requirements. 

I did use `flycheck-packages`, and it caught a lot of errors for me. But it marked those `require` statements as an error: `Cannot open load file: helm`. Any tips on how to resolve these? It seems like  there should be a way for me to tell emacs/flycheck where to find `helm` (I have it installed via `package.el`).

**Comment by purcell** [comment]
This is the secret trick:

```el
(setq flycheck-emacs-lisp-load-path 'inherit)
```

**Comment by purcell** [comment]
Merged now -- thanks!

**Pull request merged**
