### PR TITLE
add recipe `uimage'

### PR DESCRIPTION
**Pull request by lujun9972**

### CODE REVIEW

**Comment by milkypostman** [comment]
Just some comments before merge,

- think this should be called `urlimage` as `uimage` seems a bit unclear.
- traditionally you should make some of these function private `prefixed with uimage--` where it makes sense. e.g., `uimage-no-images`, `uimage-display-images`.
- the code in general is a bit messy. it would be good to add a space before the `;;; Commentary` line.
    - The depth in the `uimage-mode-buffer` function is a bit deep.
- doesn't this require `image-file` all the time?

**Comment by lujun9972** [comment]
1. I think the urlimage is too long to type. And also,because the functionality of uimage is similar with the iimage. so I think it will be better to have a similar name.
2. Actually,`uimage-no-images' and `uimage-display-images' are commands, not private functions
3. I have added a newline before ;;; Commentary line and reduced the depth of `uimage-mode-buffer' function.
4. The `image-file' now will be required all the time.

**Comment by purcell** [comment]
Thanks. The default `:files` spec already includes `*.el`, so the spec here is unnecessary and should be removed from the recipe. Also, we want to build packages from development branches, not other branches which may or may not get updated regularly, so the `:branch` option should be removed from the recipe. To make "stable" releases, just tag commits with versions and they will be built in MELPA Stable.

**Comment by lujun9972** [comment]
Thank you. I have removed these 2 options already.

**Comment by purcell** [comment]
Thanks! Recipe added as a single commit in 346cb25, just to keep the commit history tidy.

**Pull request closed without merging**
