### PR TITLE
Add ob-prolog

### PR DESCRIPTION
**Pull request by ljos**
Org-babel support for prolog.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You'll need a package dependency header for `cl-lib`:

```el
;; Package-Requires: ((cl-lib "0.5"))
```

It would also be good to put a little more information in the `Commentary:` section, e.g. suggest how to enable it:

```el
(eval-after-load 'org
  '(require 'ob-prolog))
```

**Comment by ljos** [comment]
Thank you for reviewing my project and looking to see that it follows the standards. I appreciate the time you take to ensure that everything is correct.

I have fixed the problems you found by removing the dependency on cl-lib (I didn't need it) and added the comment you suggested. I don't know what more I should put in there as most the documentation of how you should use it is already included with org-babel. The tradition for these ob-* modes is also very sparse.

**Comment by purcell** [comment]
> I have fixed the problems you found by removing the dependency on cl-lib (I didn't need it) and added the comment you suggested.

Thanks.

> I don't know what more I should put in there as most the documentation of how you should use it is already included with org-babel. The tradition for these ob-* modes is also very sparse.

Okay, cool. Merging now - thanks!

**Comment by ljos** [comment]
Thank you for adding this to melpa. I hope now that I might get some new input from some users into how I can improve the mode in the future.

**Pull request merged**
