### PR TITLE
Added discover-point

### PR DESCRIPTION
**Pull request by netromdk**
* Added discover-point with which you can discover information about value at point or region in Emacs. If value is a number then binary/octal/decimal/hexadecimal/character values and conversions are shown. For strings each character is processed in the same way. Especially while programming I find myself converting between bin/oct/hex/dec/ascii/unicode often and this simple package makes it a bit more simple.
* Package can be found here: https://github.com/netromdk/discover-point
* I am the author.
* Used flycheck to check the package file.
* I tested with `make recipes/discover-point`,
* And installed successfully using `package-install-file`.

This is my first package so please do tell if something is not up to par.
Thanks!

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Have you seen the build-in `describe-char`? I don't see what additional functionality this package provides. The name `discover-point` doesn't really fit it well.

Quick feedback re. the code itself:

- If your code actually requires `lexical-binding`, you must declare a package dependency on `(emacs "24")`. If not, you should remove the `lexical-binding: t`
- `dp/` is a bad prefix to use. Not only does it not follow the [elisp conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html), but if everyone chose a 2-character symbol prefix, then there could only be 676 distinct prefixes, and there are already 2000+ packages in MELPA! :-)  So something looking like `discover-point--` would be the correct choice here.

Hope that helps - happy to discuss further.

**Comment by netromdk** [comment]
Thanks for the feedback! Yes, I know `describe-char` and it's great but it only shows information for a single character, it doesn't interpret a number like "101" and "FE", for instance, and that was one of the main reason for making this package; to easily interpret/convert between representations.

I removed the lexical binding.

Hm maybe the name I chose wasn't the best and most suitable one. I will change it to be called `describe-number`, which is exactly what it is doing.

**Comment by purcell** [comment]
Ah yes, great name!

**Comment by netromdk** [comment]
Okay I changed the name everywhere now and tested recipe and install. Any chance you can reboot travis to forget the old name?

Thanks

**Comment by purcell** [comment]
I just committed the updated version of the recipe directly in d5ed906 instead. Thanks!

P.S. You should use `describe-number--` as the private symbol prefix rather than `describe-number/` -- elisp is not Clojure, and the best thing for the community is if authors make it easy and consistent for everyone to work on each other's code.

**Comment by netromdk** [comment]
Thank you! I made the change. :)

**Comment by purcell** [comment]
Great. Looking forward to trying this out - I can see that it would be handy.

**Comment by netromdk** [comment]
Do I have to do something specific for the badge to be created as well? I see that the package was included in the last build at http://melpa.org/#/describe-number but the badge was not created at http://melpa.org/packages/describe-number-badge.svg

When I do `make recipes/describe-number` locally then it does create the svg.

Thanks

**Comment by purcell** [comment]
There's an issue with the badges right now: #3235. You haven't done anything wrong, and the badge will start working when we fix the other issue. Sorry for the disruption.

**Pull request closed without merging**
