### PR TITLE
remove non-package ph

### PR DESCRIPTION
**Pull request by tarsius**
@gromnitsky do you intend to fix that? Otherwise I think @purcell should remove this.

### CODE REVIEW

**Comment by gromnitsky** [comment]
what should I fix exactly? it still works (at least on my machine). why did it suddenly become a 'non-package'?

**Comment by tarsius** [comment]
It slipped though review, usually @purcell would have required that you make changes before adding it to Melpa. The library completely lacks a header. To get started see http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html. You should also cleanup the whitespace, I recommend that you use `untabify` on the complete buffer. [This](https://github.com/gromnitsky/ph/blob/master/ph.el#L485) looks especially messy.

**Comment by purcell** [comment]
Yep, it's not ideal, but there's a valid `-pkg.el` file. Ideally all the `.el` files would be tidy and well-formed, and I'd strongly encourage @gromnitsky to address that, but we don't need to remove this from MELPA. A well-formed `ph.el` would allow us to extract its `Commentary` section to display on the MELPA package page for `ph`, for example.

**Comment by tarsius** [comment]
@gromnitsky Are you considering to make the suggested changes?

**Pull request closed without merging**
