### PR TITLE
Add web-completion-data

### PR DESCRIPTION
**Pull request by osv**
As was discussed in https://github.com/milkypostman/melpa/pull/2734 (company-web) I create package that containe completion data. If it will be applied I contact author of ac-html for using this one too.

### CODE REVIEW

**Comment by dunn** [comment]
Is this not yet available in melpa-stable? I get `web-completion-data-0.1 not available` when trying to install `ac-html`?

**Comment by purcell** [comment]
It's not in MELPA Stable because @osv needs to add a version tag to the repo.

**Comment by osv** [comment]
Hello, I add version tags to `web-completion-data`, `company-web`, `ac-html-bootstrap`, and `ac-html-csswatcher
`

**Comment by dunn** [comment]
Thank you!

**Comment by purcell** [comment]
Thanks folks!

**Pull request merged**
