### PR TITLE
Update recipe for org-ioslide.

### PR DESCRIPTION
**Pull request by kuanyui**
https://github.com/coldnew/org-ioslide/issues/18

### CODE REVIEW

**Comment by xuchunyang** [comment]
@kuanyui I think you'd better change your commit message to something like "Update org-ioslide recipe"

**Comment by purcell** [comment]
Rather than including `"*.el"`, it would be better to use `:defaults`: `:files (:defaults "js" "theme" "images")`

**Comment by kuanyui** [comment]
Done. Another question, will the directories in `:files` be retrieved **recursively** by MELPA?

**Comment by purcell** [comment]
> Done. Another question, will the directories in :files be retrieved recursively by MELPA?

If you include directories, they will be copied to the package including all their contents.

**Pull request merged**
