### PR TITLE
New recipe: pbcopy

### PR DESCRIPTION
**Pull request by webframp**
Found a github repo for this, PR for headers here: https://github.com/jkp/pbcopy.el/pull/1

### CODE REVIEW

**Comment by milkypostman** [comment]
@daniel-nelson just wondering if we can get some official sign-off on using this package.

@webframp possibly you want to open an issue on his repo or we can just use a fork. I am ok with this if someone is maintaining it.

**Comment by daniel-nelson** [comment]
Apologies, everyone. I somehow missed all emails related to this, until just now. Please do whatever you like with the package.

**Comment by milkypostman** [comment]
@jkp @kb so who is going to maintain this thing??? Or at least keep it around in their github account and handle any issues that get filed. It's not a huge package it can't be *that* much maintenance.

**Comment by jasonm23** [comment]
I'll fork it to EmacsFodder - it's tiny, I can look after it.

**Comment by jasonm23** [comment]
https://github.com/emacsfodder/pbcopy.el

**Comment by webframp** [comment]
OK, so I can update this PR to use `emacsfodder/pbcopy.el` as needed, headers still need to be added as in this commit: https://github.com/webframp/pbcopy.el/commit/f555cf558f75df93ded1e8a461a6bc634aaa03f9

**Comment by milkypostman** [comment]
webframp, any chance you can send that pull request to emacsfodder now. I'm sure @jasonm23 could easily merge then. Should be able to just use the same commit but redirect the pull request? I think!

when you go to create a pull request I think you can change what repo you're using. although maybe you have to refork. i dunno.

**Comment by jasonm23** [comment]
I've added the pull request to EmacsFodder/pbcopy.el and merged it.  The recipe can be updated and pushed into MELPA now

**Comment by milkypostman** [comment]
Thanks everyone.

**Pull request merged**
