### PR TITLE
add theme-looper recipe

### PR DESCRIPTION
**Pull request by myTerminal**
This package can be used to cycle through the available themes in Emacs 24 with a key-binding of your choice. Just a key combination to switch to the next theme.

The package repository can be found at [https://github.com/myTerminal/theme-looper](https://github.com/myTerminal/theme-looper).

I am the creator and maintainer of this package.

### CODE REVIEW

**Comment by purcell** [comment]
How does this compare to https://github.com/toroidal-code/cycle-themes.el ? Ideally we wouldn't have multiple packages which do the same thing.

**Comment by myTerminal** [comment]
theme-looper provides not only a way to cycle through a list of themes, but also load a random theme, like if you want to load a different theme at every startup.

It also provides a way of running post scripts that are executed after a theme has been applied, for example resetting powerline in my case.

Also my package is older. :)

**Comment by myTerminal** [comment]
Also rhe other guy seems to be using lexical bindings, that are not so quick as far as I know.

**Comment by purcell** [comment]
> Also rhe other guy seems to be using lexical bindings, that are not so quick as far as I know.

They're faster, actually. But not enough to make a difference.

**Comment by purcell** [comment]
Okay, so let's see about adding this.

The code seems reasonable, but you should change the `tl:` prefix to `theme-looper-`. Yes, it's more verbose, but it's also the [convention](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).

**Comment by myTerminal** [comment]
Sure, I'll change that in the next push. I did realize that while creating a couple of other packages that do follow this convention.

Could you please add it, I assure you that I will make the next push at the earliest.

Thanks.

**Comment by purcell** [comment]
It's better for us to just wait for the push: that way, the API won't suddenly change for the early adopters who install the package as soon as it appears on MELPA. Just ping this issue when done, and we can quickly merge it. :-)

**Comment by myTerminal** [comment]
Done :)

**Comment by purcell** [comment]
Yay! They're still with `:`, though. `-` is conventional. You'll occasionally see `--` used for "private" symbols, or even `/`, but public symbols should all just be `my-prefix-whatever`.

**Comment by purcell** [comment]
P.S. You might also like to add `;;;###autoload` magic comments before each of the `(interactive)` functions.

**Comment by myTerminal** [comment]
I did change the `:` to `-` and for private symbols, to `--` now. Not sure how `;;;###autoload` will help in my case.

**Comment by myTerminal** [comment]
I have added the magic comments, could you please verify?

**Comment by purcell** [comment]
Perfect, merged! Thanks.

**Comment by myTerminal** [comment]
Thank you, a couple of more to go :)

**Pull request merged**
