### PR TITLE
Add systemd mode recipe

### PR DESCRIPTION
**Pull request by holomorph**
I wrote the following and it was suggested that I add it to MELPA

https://github.com/holomorph/systemd-mode

It's a mode for editing systemd units, similar to conf-mode in a way, with some facilities for completion and navigating to relevant documentation.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Looks good, but there are a few issues.

- The default `:files` spec includes `*.el`, so yours is redundant here
- You're using `setq-local`, so you need to either declare a package dependency on Emacs 24.3, or just use the classic `(set (make-local-variable ...) ...)` instead
- `systemd-company` should probably be a separate package which depends on `systemd`, `company` and `cl-lib`. Otherwise, you'll have to make the whole combined package depend on those, which would narrow its appeal -- we can build 2 separate packages from the same repo provided each `.el` file has the appropriate metadata headers, including `Package-Requires`

Hope that helps!

**Comment by holomorph** [comment]
Ah, thanks. I'll remove the `:files` argument and add a Package-requires for 24.3.

I modeled the company support after that in geiser. `company` itself depends on `cl-lib`, and nothing interesting happens if company is not present, so I'm not inclined to either introduce a dependency on company, or split the package.

**Comment by purcell** [comment]
Fair enough. Re. `cl-lib`, you generally shouldn't rely on transitive dependencies, though, when you're using libraries directly. It's not an issiue in this specific case because any Emacs >= 24.3 will have it anyway.

I just noticed that you're using `with-eval-after-load`, which is Emacs 24.4 and greater, so you should either bump the dependency or just use `eval-after-load` and quote the body of the form.

**Comment by holomorph** [comment]
> Re. `cl-lib`, you generally shouldn't rely on transitive dependencies, though, when you're using libraries directly. It's not an issiue in this specific case because any Emacs >= 24.3 will have it anyway.

Makes sense

> I just noticed that you're using `with-eval-after-load`, which is Emacs 24.4 and greater

Thanks, dependency bumped.

**Pull request merged**
