### PR TITLE
Request to add searchq package.

### PR DESCRIPTION
**Pull request by boyw165**
Hi MELPA team,

The brief introduction of `search` package:

**A search framework which let you search string or regular expression in the background and queue the search tasks. It uses find, grep, ack or ag command as its searching backends. In addition, the search result can be a jotting. So it keeps the search result for you and provides editing function.**

Please check [official website](https://github.com/boyw165/search) for detail.

### CODE REVIEW

**Comment by boyw165** [comment]
Hi MELPA team,

What is the error?

**Comment by milkypostman** [comment]
probably no error, i think purcell is backlogged. I'll have a look now.

**Comment by purcell** [comment]
I've restarted the build. Not sure what the error was about.

Regarding the package, I'm -1 on the extremely general `search` name, not least because `search-` is not going to be a very unique symbol prefix. Something like `file-search` would be much better IMO.

**Comment by milkypostman** [comment]
flex-search, any-search, master-search, etc. are all better names.

@boyw165 problem with the PR is that one of the quotes wasn't a quote but some other character (the second quote around `boyw165/search`).

**Comment by purcell** [comment]
I'm also not sure that the package should depend on `hl-anything` -- if `anything` is required for the package to work, then the package name should include `anything` somehow (e.g. `anything-file-search`). And if it's not required, then users are going to be annoyed if they end up with `anything` installed. Better to split the `anything` support into a separate package, or just provide the `anything`-related code in an `(eval-after-load 'anything ...)` block, with no formal package dependency.

**Comment by boyw165** [comment]
Good idea!

**Comment by boyw165** [comment]
How about the name, **findq** which stands for "find queue"?

**Comment by purcell** [comment]
> How about the name, findq which stands for "find queue" (or searchq)?

Either is fine. :-)

**Comment by purcell** [comment]
(`searchq` is probably better, since `find` generally produces lists of files, rather than lines within files.)

**Comment by boyw165** [comment]
Ok, `searchq` is taken.

**Comment by purcell** [comment]
Squashed and applied in 9738c1b

**Comment by boyw165** [comment]
Thank you, MELPA team. :D

**Pull request closed without merging**
