### PR TITLE
Added DTrace mode

### PR DESCRIPTION
**Pull request by dotemacs**
DTrace mode for editing D language.

Repo: https://github.com/dotemacs/dtrace-script-mode
To set your mind at ease: I'll maintain the mode from now on. This is not a fork.

Seeing how there was already a mode for a completely unrelated D
language, called d-mode.el, I worked with the original author on renaming this
mode and adding the license of his choice as there wasn't one present.

### CODE REVIEW

**Comment by purcell** [comment]
:+1:

**Comment by dotemacs** [comment]
The license has been approved by the original package author.

Feel free to merge this PR at your convenience. 

Thank you :smile:

**Comment by dotemacs** [comment]
@purcell just a gentle ping ... :)

**Comment by purcell** [comment]
> @purcell just a gentle ping ... :)

Yep, busy week. First time in ages I've had a couple of blank days in my github timeline...

Why does this package define `d-font-lock-keywords` and other symbols starting with `d-`? These should all be renamed to use a unique prefix which won't clash with symbols from elsewhere.

**Comment by dotemacs** [comment]
Hey @purcell 

sorry, the only reason for pinging is because I'm used to your super prompt responses to the pull requests :)

Anyway, I've since renamed all the symbols from **d-** something to **dtrace-script-mode-** something. Have a look and let me know what you think.

Thank you for your time

**Comment by purcell** [comment]
Looks great now, thanks.

**Pull request merged**
