### PR TITLE
Add recipe for nameframe-projectile

### PR DESCRIPTION
**Pull request by john2x**
https://github.com/john2x/nameframe

Nameframe is a package to manage frames by name.

This package provides Projectile integration for nameframe (#3170).

### CODE REVIEW

**Comment by purcell** [comment]
I wonder if @bbatsov would consider adding something like `projectile-before-switch-project-hook` so that you could do this without having to override and replace `projectile-switch-project-by-name` like this?

**Comment by bbatsov** [comment]
It's fine to add something like this.

On Monday, 5 October 2015, Steve Purcell <notifications@github.com> wrote:

> I wonder if @bbatsov <https://github.com/bbatsov> would consider adding
> something like projectile-before-switch-project-hook so that you could do
> this without having to override and replace
> projectile-switch-project-by-name like this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/milkypostman/melpa/pull/3177#issuecomment-145461188>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by milkypostman** [comment]
@john2x would you be willing to follow up on the projectile change and send a PR to @bbatsov ?

**Comment by john2x** [comment]
I'll give it a shot. :+1:

**Comment by john2x** [comment]
I have opened a PR for Projectile to add the before hook, but still waiting for feedback on the author (I have a question regarding the use of `run-hook-with-args` as my use case needs the project name for the hook function).

For the mean time, I have updated nameframe-projectile integration by using a global minor mode to toggle the keymap changes ([diff](https://github.com/john2x/nameframe/commit/e4b1554668bb4a47afc3289d2ceda662e22b8379#diff-396a89ea89a16c027fd82347190c498e))

**Comment by purcell** [comment]
Merging this for now; will leave you to follow up with related changes independently. :-)

**Comment by john2x** [comment]
Thanks! Can the related package (#3176) be merged as well? :grinning:

**Comment by john2x** [comment]
Just a quick update that nameframe-projectile is now using Projectile's new `projectile-before-switch-project-hook` :+1:

**Comment by purcell** [comment]
Yay, great - thanks to you and @bbatsov for coordinating that change.

**Pull request merged**
