### PR TITLE
Add easy-lentic

### PR DESCRIPTION
**Pull request by tumashu**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- The `\C-c j` keybinding is reserved for user customisations, so you should choose something different
- The `lentic-*` methods should be called `easy-lentic-*` to match the package name, right, or am I missing a technical reason for this naming?

**Comment by tumashu** [comment]
lentic-* is for lentic package and can't rename....

**Comment by purcell** [comment]
Okay, makes sense.

**Comment by purcell** [comment]
Let me know when you've updated the keybindings, then I can go ahead and merge this.

**Comment by tumashu** [comment]
```
The \C-c j keybinding is reserved for user customisations, so you should choose something different
```
I don't familar this field, suggest one?

**Comment by purcell** [comment]
The elisp manual has [some guidelines](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) - maybe `C-c .` or `C-c :`?

**Comment by tumashu** [comment]
Fixed, use  'C-c .'

**Comment by tumashu** [comment]
Fixed, use  'C-c .'

**Comment by tumashu** [comment]
Fixed, use  'C-c .'

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
