### PR TITLE
Add nand2tetris package

### PR DESCRIPTION
**Pull request by CestDiego**
Useful to follow the Coursera Class `From Nand 2 Tetris'

https://www.coursera.org/course/nand2tetris1

### CODE REVIEW

**Comment by xzerocode** [comment]
chuch

**Comment by purcell** [comment]
Cool, but please don't set top-level symbols like `HardwareSimulator`. Use `nand2tetris-...` instead. (And yes, you can have vars and functions with the same name if you like.)

**Comment by CestDiego** [comment]
thanks, it wasn't supposed to stay like this :) fixing this now

**Comment by CestDiego** [comment]
Fixed with https://github.com/CestDiego/nand2tetris.el/commit/de55c2e5e9ed99e8466026e657fde460f02a3bf0

**Comment by purcell** [comment]
Super, merged - thanks.

**Pull request merged**
