### PR TITLE
add recipe for pylookup

### PR DESCRIPTION
**Pull request by danielwuz**
`pylookup` is a tool that an emacs user to search Python HTML documentation either online or offline. This is the link to project page: https://github.com/tsgates/pylookup.

I'm not the author nor the maintainer, just a user of this package. I have reached the author and he's willing to add a recipe for this package(as https://github.com/tsgates/pylookup/issues/31).  I'll be happy to take care of any issue that comes up.

### CODE REVIEW

**Comment by milkypostman** [comment]
@danielwuz any progress on this?

**Comment by tsgates** [comment]
Hi, I recently found m/elpa very useful; I don't have to maintain and update packages by myself. I'd like to include pylookup as well, but it requires bootstrapping, such as downloading python documents and generating indexing. Is it possible to run "make build" when installing the package in elpa? Another solution is to just include all documents (i.e., html and db file) so that we can discard Makefile as you guys were discussing above. Any suggestion?

**Comment by chrischambers** [comment]
@milkypostman - Looks like this should possibly be re-opened?

**Comment by pataquets** [comment]
@milkypostman @purcell Fancy to reopen?
I'm curious about why is the `Makefile` not desirable. Just a matter of repo tidiness (which is understandable) or does it conflict/interfere/confuses some sort of automation/CI/etc.?
If the latter, we could figure out a quick solution by renaming or something easy to prevent any annoyance.

**Pull request closed without merging**
