### PR TITLE
Add johanvts/emacs-fireplace

### PR DESCRIPTION
**Pull request by hut8**
https://github.com/johanvts/emacs-fireplace

**What it does:**

displays a fireplace

**My relation to project**

I asked if I could make a package for it here: https://github.com/johanvts/emacs-fireplace/issues/1

Thanks.

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
:+1:

**Comment by milkypostman** [comment]
haha, this is hilarious. but it's missing an autoload statement which means it will be worthless to add to MELPA at this point.

can you send a PR/file an issue with the original package to add the autoloads, then we can merge this.

I think all you need is to add,

```
;;;### autoload
```

before the `fireplace` function.

**Comment by hut8** [comment]
Aww man, rookie mistake. I'm on it.

**Comment by AdrieanKhisbe** [comment]
@milkypostman PR is pending https://github.com/johanvts/emacs-fireplace/pull/8 :)

**Comment by hut8** [comment]
Heh. Beat me to it @AdrieanKhisbe

**Comment by purcell** [comment]
This is lots of fun, so please bear with me while I get a little picky:

- The metadata looks like it's been hacked together just enough to work, but it's messy, with the `Commentary:` above the other headers etc. Please try using `M-x auto-insert` in a fresh `fireplace.el` and then use the more complete boilerplate it will generate for you.
- `fp-` is not a good prefix for private symbol names. Use `fireplace--`, as per the [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html).
- `C-s` is a keybinding [reserved for users](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html)

**Comment by purcell** [comment]
Also: `smoke`, `flame`, `make-grid`, `gotoxy` etc. all need to be prefixed with `fireplace-` or `fireplace--`.

**Comment by AdrieanKhisbe** [comment]
@purcell: your concern have now been addressed and PR has been merge.

I thinks it's time to put melpa on fire!! :D :fire:

**Comment by purcell** [comment]
Thanks!

**Comment by AdrieanKhisbe** [comment]
:fireworks:

**Pull request merged**
