### PR TITLE
Add recipe for emms-mode-line-cycle

### PR DESCRIPTION
**Pull request by momomo5717**
https://github.com/momomo5717/emms-mode-line-cycle
This package is a minor mode for displaying `emms-mode-line-string` cyclically within specified width.
Thank you.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, looks good. Sent you a quick fix in https://github.com/momomo5717/emms-mode-line-cycle/pull/1.

**Comment by momomo5717** [comment]
Thank you for fixing it.
I've merged it.

**Comment by purcell** [comment]
Cool, thanks - merged!

**Comment by momomo5717** [comment]
Thank you for your help!

**Pull request merged**
