### PR TITLE
add ember-mode recipe

### PR DESCRIPTION
**Pull request by jesse-black**
This adds a recipe for [ember-mode](https://github.com/madnificent/ember-mode) which provides a minor mode for Ember.js projects using ember-cli, with keybindings for fast navigation inside projects, running blueprint generators, and compilation-mode integration for building, serving, and testing. 

I've contributed code and I discussed this with the maintainer [here](https://github.com/madnificent/ember-mode/pull/5).

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this. Quick feedback:

- This should use the standard boilerplate (more or less as generated by `auto-insert-mode`), with the informational text in the `;;; Commentary:` section so it can be found by `package.el`, and the usual `ends here` trailing comment etc. The MIT license text should of course be wrapped: `M-q` makes this easy.
- Minor modes should not normally be distributed in packages called `*-mode` -- that suffix is generally reserved for major modes. The file and package should therefore really be renamed.
- You should have `;;;###autoload` cookie comments for the main interactive entry points (ie. the `(define-derived-mode ember-mode ...)` form)
- The `C-c c` binding is [reserved for customisation by end users](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html). You should choose an alternate binding.
- Consider using the `inflections` package to handle pluralisation etc. More re-use is good!
- `cl` is being phased out in favour of `cl-lib`: consider switching from one to the other and declaring a package dependency on `(cl-lib "0.5")` in the `Package-Requires` header

Hope that helps!

-Steve

/cc @madnificent

**Comment by purcell** [comment]
Oh, a further minor tip: where you're using `make-local-variable` followed by `add-to-list`, it's conventional to use (abuse?) `add-hook` to do this, since it provides a "LOCAL" flag which makes the modified value buffer-local.

**Comment by purcell** [comment]
(Re. `cl` vs `cl-lib`, the code actually already uses some `cl-*` functions from `cl-lib`, so the package dependency declaration is already necessary.)

**Comment by jesse-black** [comment]
Yes, i made a PR for autoload cookies already [here](https://github.com/madnificent/ember-mode/pull/6)

We can take care of the boilerplate and wrapping.

What's the convention for naming minor modes? Ember.js is a pretty major javascript framework and I don't see anything else competing for the name in the package archives. And there aren't that many packages postfixed -minor-mode and on the other hand I see a lot of minor modes breaking the rules.

We can find an alternate keybinding.

I think the issue with inflections is we need to copy the same inflections as the `ember-cli` tool to be effective in navigating files so I'm not sure how closely the `inflections` package corresponds to it.

We can deal with the cl stuff.

Regarding make local variable and add to list I guess you mean `compilation-finish-functions` and `compilation-error-regexp-alist`. I guess it makes sense for `compilation-finish-functions`, I just wasn't sure because it wasn't named as a hook, but it feels pretty gross for `compilation-error-regexp-alist` because thats not really a hook at all.

Thanks

**Comment by purcell** [comment]
> Yes, i made a PR for autoload cookies already here
> 

Great.

> We can take care of the boilerplate and wrapping.

Thanks.

> What's the convention for naming minor modes? Ember.js is a pretty major javascript framework and I don't see anything else competing for the name in the package archives. And there aren't that many packages postfixed -minor-mode and on the other hand I see a lot of minor modes breaking the rules.

The convention is to only use `-mode` for major modes. Many packages have broken the convention, but if possible we should still make an effort to follow it. It's particularly feasible to do so before publishing a package for the first time, which is why I'm pointing it out now, but I'm not going to refuse the package over this. :-)

> We can find an alternate keybinding.

:+1: 

> I think the issue with inflections is we need to copy the same inflections as the ember-cli tool to be effective in navigating files so I'm not sure how closely the inflections package corresponds to it.

Yep, can understand that, though presumably pluralisation and singularisation of english nouns is pretty standard. :-) I wouldn't expect problems in practice.

> We can deal with the cl stuff.

Thanks.

> Regarding make local variable and add to list I guess you mean compilation-finish-functions and compilation-error-regexp-alist. I guess it makes sense for compilation-finish-functions, I just wasn't sure because it wasn't named as a hook, but it feels pretty gross for compilation-error-regexp-alist because thats not really a hook at all.

That's my point: while it looks odd, `add-hook` frequently gets used for locally modifying things which aren't hooks. But you can certainly feel free to ignore this point.

**Comment by madnificent** [comment]
I applaud moving to the `inflections` package once ember-cli gets a better understanding of plurals.  Would it be ok if we started using it once ember-cli adopts a smarter pluralization approach?

**Comment by purcell** [comment]
> Would it be ok if we started using it once ember-cli adopts a smarter pluralization approach?

Yep, sure. 

Merging now. Thanks for your patience.

**Comment by purcell** [comment]
(But don't forget to fix that `C-c c` binding!)

**Pull request merged**
