### PR TITLE
Add elscreen-buffer-group

### PR DESCRIPTION
**Pull request by jeffgran**
Elscreen Buffer Group

* This is an addition to elscreen.el that automatically maintains a separate buffer list per elscreen. When you switch to or display any buffer, it is added to that screen's buffer group. Any standard buffer-switcher or -lister that uses (buffer-list) or (ido-make-buffer-list) will automatically be filtered to the current buffer, and specific commands can be opted-out from the filtering.
* direct link: https://github.com/jeffgran/elscreen-buffer-group
* Originally from here: http://www.emacswiki.org/emacs/elscreen-buffer-list.el this is a complete rewrite. You'd be hard-pressed to find a single line leftover from that code intact, but it started from there. Barring that, I'm the author.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- The dependency on `(elscreen "2012-09-21")` is invalid: that's not a well-formed version number, so just use `"0"` instead.
- `ido-make-buffer-list-hook` is not necessarily defined at compile-time (perhaps `elscreen` loads it, but you shouldn't rely on that). Either wrap the associated `add-hook` form in an `(eval-after-load 'ido '(progn ...))` or (best avoided) explicitly `(require 'ido)`.

Hope that helps!

-Steve

**Comment by jeffgran** [comment]
Hi Steve, thanks for your help on this. I cleaned up your suggestions and a few other things. Let me know if this passes muster now. :)

**Comment by purcell** [comment]
Looking over the code again, it looks like there'd be no way to disable this once enabled: once enabled, the advice for the buffer functions stays in place forever. So you might consider making a global minor mode so that the mode variable can be used to decide whether to override behaviour, or so that the on/off toggling of the mode can enable/disable the advice.

And a final point before I merge this, which I should have mentioned earlier: I *always* read `-bg` as `background`. It might just be me, but I feel like `-buflist` or `-bufgroup` or even `-buffer-group` would make for clearer naming, and those extra bytes are inexpensive.

**Comment by milkypostman** [comment]
@jeffgran /ping

**Comment by jeffgran** [comment]
I changed the name and added the code to turn off/on all the advice.

**Comment by milkypostman** [comment]
@jeffgran sorry to have to ask you for one more thing but this PR needs to have your recent commits *rebased* (not merged) on to milkypostman/master and then repushed.

**Comment by purcell** [comment]
@jeffgran Don't worry too much about the squashing & rebasing of the PR: I can manually commit a recipe locally if necessary. Sent you a necessary (and also a recommended) fix in https://github.com/jeffgran/elscreen-buffer-group/issues/3 though.

**Comment by jeffgran** [comment]
oops :blush:

**Comment by vyp** [comment]
@jeffgran you should update your 'fork'/local branch first before rebasing.

**Comment by purcell** [comment]
Not to worry - I've committed this recipe directly in 9c6fedb.

**Comment by jeffgran** [comment]
Thank you again @purcell :)

**Pull request closed without merging**
