### PR TITLE
Adding darktooth-theme

### PR DESCRIPTION
**Pull request by jasonm23**
New emacs theme

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this, but all those `display-graphic-p` tests are just wrong: they will cause the theme to be "frozen" into a particular set of colours according to the frame type in which it is first loaded (terminal / daemon / GUI), and then it will look wrong in other frames connected to the same Emacs instance.

The right way to handle this is to define each face using the DISPLAY option: see the corresponding [docs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Faces.html#Defining-Faces). The `min-colors` matcher is probably what you want.

Hope that helps,

-Steve

**Comment by purcell** [comment]
Also, `darktooth-set-ansi-color-names-vector` looks redundant w.r.t. the `custom-theme-set-variables` form above, unless I'm misunderstanding something.

**Comment by jasonm23** [comment]
Steve this is a fork of Gruvbox, which is listed.  So I appreciate the input and will make the changes when scheduling allows, but this should not be a reason to delay its release

**Comment by purcell** [comment]
Yes, and I should have picked up the problem with `gruvbox` when it was submitted, because things like this tend to get copied from one theme to another once they're published.

Part of our goal of curating MELPA packages is to ensure that they are widely useful and of good quality, and submitted packages are not automatically entitled to addition.

Now, I'm not going to dig in my heels and delay this PR *this time*, but I think it's worth you and @Greduan fixing things up as soon as time permits, for everyone's benefit.

**Comment by jasonm23** [comment]
Thanks, I've opened an issue on dark tooth and I now maintain gruvbox too, so the changes will roll out together.

Fwiw I thought the display-graphic-p method was quite neat, since I will usually run one way or another, since OS X Mac port won't launch a terminal :( anyway that's a separate issue and the only real neatness of the hack is its brevity.

**Comment by jasonm23** [comment]
Chances are these changes will get done in a few hours from now, I'm just on the way to dinner out with my wife, and wanted to show off that I released another Emacs theme to all the people there...


(Just kidding of course no one cares ;) )

**Comment by purcell** [comment]
> Fwiw I thought the display-graphic-p method was quite neat, since I will usually run one way or another, since OS X Mac port won't launch a terminal :( anyway that's a separate issue and the only real neatness of the hack is its brevity.

The DISPLAY part of face specs can match graphic terminals.

FWIW, I'm on OS X and can certainly launch terminals: you can run Emacs in the terminal by running `/Applications/Emacs.app/Contents/MacOS/Emacs -nw`, or you can use `emacsclient` to create a new terminal frame connected to an already-running GUI instance of Emacs.

**Comment by jasonm23** [comment]
Yes, but you're not running the Mac port build by Yamamoto.

**Comment by jasonm23** [comment]
(see railwaycat/emacs-mac-port)

**Comment by jasonm23** [comment]
http://lists.gnu.org/archive/html/emacs-devel/2015-03/msg00194.html Moved now.

**Comment by purcell** [comment]
Aha, right.

**Pull request merged**
