### PR TITLE
Add whitaker (comint mode for Whitaker's Words)

### PR DESCRIPTION
**Pull request by Fuco1**
https://github.com/Fuco1/whitaker

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this. The recipe says `smartparens`, though -- can you amend the commit to fix that and force push it back here please?

**Comment by Fuco1** [comment]
Copy-paste is fun...

**Comment by Fuco1** [comment]
Fixed.

**Comment by purcell** [comment]
Thanks :)

**Pull request merged**
