### PR TITLE
Add a recipe for swap-buffers

### PR DESCRIPTION
**Pull request by ekazakov**
The quickest way to swap buffers between windows. Based on [switch-window](https://github.com/dimitri/switch-window) package.

https://github.com/ekazakov/swap-buffers

/cc @ekazakov

### CODE REVIEW

**Comment by purcell** [comment]
Cool. I use `switch-window` myself -- what's actually the difference here?

**Comment by purcell** [comment]
Oh, hang on -- ignore me, I get it.

**Comment by purcell** [comment]
Can you remove the `:branch` setting from the recipe please? Best would be to amend the commit and force-push it here to cleanup update the PR.

**Comment by ekazakov** [comment]
Done

**Comment by purcell** [comment]
Great, thanks! Merged. I'm looking forward to using this myself. :-)

**Comment by milkypostman** [comment]
I think it would be more intuitive if this were named "move-window".

My window arrangements are normally not Copley enough to warrant using
switch-window -- I just bind C-a to next window and hit it as many times as
I need. -- but this seems like something worth installing.

**Comment by purcell** [comment]
@milkypostman This package is for taking the buffer in the current window and moving it to a different window. So "move-window" doesn't really describe it either. If I had to suggest a name, it would be "switch-buffer-to-window", but that's a bit longer. :-)

**Pull request merged**
