### PR TITLE
Add yatex

### PR DESCRIPTION
**Pull request by roronya**
YaTeX is an intelligent, acquisitive and integrated package which reduces your efforts of composing LaTeX source on Emacs.
http://www.yatex.org/

### CODE REVIEW

**Comment by purcell** [comment]
I have some reservations about this code. In particular, there are many symbols which do not have a `yatex-` prefix, e.g. `tex-pdfview-command` in `yatex.el`. So installing this package will potentially cause clashes with other code. And `comment.el` should be named something like `yatex-comment.el`.

I'm going to merge this anyway, since I figure the code is mature and presumably working okay for users, but I strongly encourage the author to tidy it up. Perhaps you could pass on this information to the author. :-)

**Comment by roronya** [comment]
OK, I'll pass. thank.

**Comment by milkypostman** [comment]
Really?

**Comment by purcell** [comment]
@milkypostman I think he means "I'll pass it on". :-)

**Comment by roronya** [comment]
I'm sorry for my clumsy English. I already told @purcell 's message to the author. He fixes the program as soon as possible.

**Comment by purcell** [comment]
@roronya That's great! Thanks for your help. :-)

**Pull request merged**
