### PR TITLE
Add evil-avy recipe

### PR DESCRIPTION
**Pull request by louy2**
Evil-avy is a minor mode adding avy to non-count evil motions.

My 1st mode, 1st minor mode and 1st stuff on MELPA :)

### CODE REVIEW

**Comment by xuchunyang** [comment]
Repo direct link: https://github.com/louy2/evil-avy

One small issue: it seems you forgot to add `evil` to Package-Requires.

**Comment by louy2** [comment]
Oh yeah. I don't have to offer a version right?

**Comment by louy2** [comment]
I'll just put the latest in. Thanks for pointing out.

**Comment by purcell** [comment]
Thanks, just sent [a small fix](https://github.com/louy2/evil-avy/pull/1), but this is otherwise ready to merge.

**Comment by louy2** [comment]
Gotcha. Fix merged.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
