### PR TITLE
Fetch snippets for requirejs-emacs.

### PR DESCRIPTION
**Pull request by joeheyming**
Oops, I broke package install for requirejs by adding an internal snippets dir.  Silly me.

Copied magnars's angularjs-snippets recipe (Thanks @magnars for so many good lisp examples!)

### CODE REVIEW

**Comment by purcell** [comment]
Can you amend this to `:files (:defaults "snippets")`, please? You can force-push the amended commit to update the PR, then leave a comment here so I know to merge it.

**Comment by joeheyming** [comment]
Fixed, thanks for the tip for force-push
image

**Comment by milkypostman** [comment]
I don't see the new version. Says *.el instead of ":defaults"

**Comment by joeheyming** [comment]
Ok, one more time.  How about this?

(requirejs :fetcher github :repo "joeheyming/requirejs-emacs"
		                  :files (:defaults "snippets"))

**Comment by purcell** [comment]
Yay, looks good now - thanks.

**Comment by joeheyming** [comment]
excellent
image

**Pull request merged**
