### PR TITLE
Add recipe for emms-player-simple-mpv

### PR DESCRIPTION
**Pull request by momomo5717**
[https://github.com/momomo5717/emms-player-simple-mpv](https://github.com/momomo5717/emms-player-simple-mpv)

This is an extension of [emms-palyer-simple.el](https://github.com/emacsmirror/emms/blob/master/lisp/emms-player-simple.el) for mpv JSON IPC.
I think it is useful for defining a emms player for specific protocols or input forms such as ffplay form
(for example [emms-player-mpv-jp-radios](https://github.com/momomo5717/emms-player-mpv-jp-radios)).

I'm not good at English. So there might exist unclear variable name or sentences.
I apologize in advance if there are any mistake.

Thank you for your help.

### CODE REVIEW

**Comment by purcell** [comment]
We already have [emms-player-mpv](http://melpa.org/#/emms-player-mpv) -- is this different?

**Comment by momomo5717** [comment]
Thank you for the quick response.

Yes, it is.

emms-player-mpv is one of the emms players and easy to use.

emms-player-simple-mpv helps to define different kinds of emms players of mpv like [emms-player-simple.el](https://github.com/emacsmirror/emms/blob/master/lisp/emms-player-simple.el), because mpv needs specific input format or parameters to play some streaming URLs or protocols, and it supports JSON IPC to extend control functions.

**Comment by purcell** [comment]
Okay, great.

Which package provides `later-do`?

**Comment by momomo5717** [comment]
Thank you for fixing it! I've merged.

EMMS includes [later-do.el](https://github.com/emacsmirror/emms/blob/master/lisp/later-do.el).
Should I write the dependency?

**Comment by purcell** [comment]
> EMMS includes later-do.el.
> Should I write the dependency?

Nope, that's fine -- I just needed to make sure that one of the declared dependencies included that file.

**Comment by momomo5717** [comment]
I see.

Thank you very much for your kindness.

**Pull request merged**
