### PR TITLE
Added puml-mode, a PlantUML major mode

### PR DESCRIPTION
**Pull request by skuro**
Contents: ``puml-mode`` provides an editor for [PlantUML](http://plantuml.sourceforge.net/) files
Original repo: [skuro/puml-mode](https://github.com/skuro/puml-mode)

I'm the current maintainer of the package.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. I know you inherited this from another author, but the mix of `plantuml-` and `puml-` prefixes is pretty odd. Would it be worth replacing all the `plantuml-` with `puml-`?

**Comment by skuro** [comment]
I see your point. I think it's actually worth it, especially since there's already [another project](https://github.com/milkypostman/melpa/blob/master/recipes/plantuml-mode) that uses `plantuml-` prefixes. I'll give it a go and update the PR.

**Comment by skuro** [comment]
Ok, in its current form the code only declares `puml-*` names, it should be cleaner now.

**Comment by purcell** [comment]
Great, thanks. The other project also seems to have started from the same code by Zhang Weize.

**Pull request merged**
