### PR TITLE
Added spotlight recipe

### PR DESCRIPTION
**Pull request by benmaughan**
This PR adds the package spotlight which provides functions to search files using the OS X spotlight utility. Leverages ivy to give incremental search and narrowing of results.

I am the author of the package, and it is hosted here:
https://github.com/benmaughan/spotlight.el

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- Your `defcustom` forms should have their `:group` specified
- You're [modifying `ivy-minibuffer-map` globally](https://github.com/benmaughan/spotlight.el/blob/master/spotlight.el#L101), not just for *your* use of ivy: that seems wrong to me.
- Having both `spotlight-base-dir` and `spotlight-user-base-dir` seems unnecessary to me. Just use `read-directory` when no previous directory has been specified and cached.
- You might also need to use `shell-quote-argument` to escape the queries when constructing command lines

Also, stylistic tip -- don't do this:

```el
(if arg
      ;; prompt for dir
      (setq spotlight-user-base-dir (read-directory-name "base directory: "))
    ;; else use default
    (setq spotlight-user-base-dir spotlight-base-dir))
```

when you can just do this:

```el
(setq spotlight-user-base-dir (if arg
                                   (read-directory-name "base directory: ")
                                 spotlight-base-dir))
```

Hope that helps!

**Comment by benmaughan** [comment]
Thanks for taking the time to look and comment! I'll look at fixing those and submit and updated version.

**Comment by purcell** [comment]
Yep, just leave this open and comment back here when ready. :-)

**Comment by benmaughan** [comment]
Hi,

I've taken on your comments and the only one I don't think I can include is:

> Having both spotlight-base-dir and spotlight-user-base-dir seems unnecessary to me. Just use read-directory when no previous directory has been specified and cached.

I've renamed `spotlight-base-dir` to `spotlight-default-base-dir` to reflect the fact that I want it to act as the default base directory if none is specified using the prefix argument. I couldn't see a way to get this behavior without storing the default in a separate variable.

Let me know if you have any additional comments - your previous ones were really useful!

Cheers,
 Ben

**Comment by purcell** [comment]
Makes sense - merging now. Thanks for your patience!

**Pull request merged**
