### PR TITLE
Add Focus

### PR DESCRIPTION
**Pull request by larstvei**
Hi!

I wrote a package that provides a feature similar to [iA Writer's](https://ia.net/writer) Focus Mode. It basically just dims the font color of the text in surrounding areas.

The prefix `focus` does crash with the built in `focus-frame`, but this is a obsolete function that does nothing, so I hope that's OK.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks - looks nice. Do you think you could squash the commits and force-push them to keep the history tidy please?

Also, don't depend on version 1.0 of `cl-lib` -- it's not installable from anywhere. Instead, depend on 0.5, which is in GNU ELPA.

`defvar-local` was introduced in Emacs 24.3, so your code actually needs at least that version. If you'd prefer to keep compatibility with all 24.x versions, use `defvar` + `make-variable-buffer-local` instead.

You should also use `defgroup` to explicitly declare the `'focus` custom group, and place it logically in the tree of standard custom groups.

P.S. try `M-x checkdoc` -- your docstrings are good, but not quite matching the conventions.

**Comment by larstvei** [comment]
Great feedback! Thanks :)

I'll make the changes.

**Comment by larstvei** [comment]
Applied the changes now!

`M-x checkdoc` was brilliant! It still raises one error, and I think it's because I have one argument name that is prefix of another (color and colors). This seemed like an sort of odd error to raise, so I ignored it (let me know if that's a bad call). The only reason the arguments are set up like this is to ensure that it receives at least one color (because it does not make sense to take an average of zero things).

Thank you again for great tips, and for doing such a fantastic job with melpa!

**Comment by purcell** [comment]
:+1:   Incidentally, `flycheck` displays the `checkdoc` feedback directly in-buffer, and if you use `flycheck-package` too, you'll get linting for `package.el`-specific issues. (For example, `flycheck-package` warns about the `cl-lib` 1.0 issue here.)

**Pull request merged**
