### PR TITLE
Added recipe for xah-lookup-word-on-internet

### PR DESCRIPTION
**Pull request by xahlee**
This package provides commands for looking up the web.
* xah-lookup-word-on-internet
* xah-lookup-google
* xah-lookup-wikipedia
and a few others

repo at https://github.com/xahlee/lookup-word-on-internet

I'm the author.

Would fix any issues or recommendations. Thanks.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! I'd be inclined to call this just `xah-lookup.el`: it's a bit more concise, and it matches the `xah-lookup-` prefix common to the symbols defined in the file. Also, no need to `require` `eww` -- the code doesn't use it, so it'll often result in Emacs loading `eww` even though the user prefers to use his default browser.

**Comment by xahlee** [comment]
Good points. Thanks again. Going to change. Going to delete this recipe and add the new one. (if that's not the correct process, please let me know. thx.)

**Comment by purcell** [comment]
That's fine. If you put your recipe commits on separate branches, and then create pull requests from them, you can update/replace pull request contents by amending/rewriting commits in that branch and then force-pushing them. Ideally each recipe pull request made here will have exactly one commit.

**Comment by xahlee** [comment]
I just changed the the package's name. Am following your direction for a new pull request but will take a bit time. I think in the meantime xah-lookup-word-on-internet recipe will result file not found error... am doing a new pull request as soon as i can.

**Pull request closed without merging**
