### PR TITLE
Add recipe for mb-url

### PR DESCRIPTION
**Pull request by dochang**

### CODE REVIEW

**Comment by milkypostman** [comment]
the recipe you have here is broken, please make the package name in the recipe match the name of the file.

**Comment by milkypostman** [comment]
wait, sorry, the problem is in the `mb-url-pkg.el` file. the dependency shouldn't have quotes around the package name. 

please test the recipe in a local client then you can ping in chat here; and rerun the travis test again.

**Comment by dochang** [comment]
Fixed!  @milkypostman  Thank you!

**Comment by milkypostman** [comment]
the only think that I thought about here which @purcell has been pretty diligent about is naming. while `mb-url` seems ok, my concern is conflicts with another package that may be `mb` which has a variable like `mb-url` or something. But in that case I guess that other package should rename.

**Comment by milkypostman** [comment]
merging but may need to revisit the name.

**Pull request merged**
