### PR TITLE
add kixtart-mode

### PR DESCRIPTION
**Pull request by ryrun**
summary: add kixtart support for emacs

link: https://github.com/ryrun/kixtart-mode

association: author

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. This can be merged, but some quick feedback on the code which I think will help you to improve it:

- Please use the full standard header formatting, as generated by `auto-insert-mode` (try enabling `auto-insert-mode` and creating an empty `*.el` file to see what I mean).
- Please consider adding an `;;;###autoload` cookie comment for the derived mode declaration.
- Setting `mode-name` is redundant with `define-derived-mode`, so you can delete that particular line.
- `font-lock-defaults` is always buffer-local, so you can just set it directly
- `font-lock-fontify-buffer` doesn't need to be called explicitly
- consider using `regexp-opt` to simplify `kixtart-gen-regexp-list`.

Hope that helps.

-Steve

**Comment by ryrun** [comment]
@purcell Thx, i'll check this.

**Comment by ryrun** [comment]
@purcell Made some changes on the code. Thanks again.

**Comment by purcell** [comment]
Great! Sent you a couple of further tweaks in https://github.com/ryrun/kixtart-mode/pull/1.

**Pull request merged**
