### PR TITLE
Add recipe for yesql-ghosts

### PR DESCRIPTION
**Pull request by magnars**
https://github.com/magnars/yesql-ghosts

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, looks cool! Would you consider using `yestql-ghosts-` as a prefix instead of `yesqlg-`? No reason to prefer concision over readability here.

**Comment by magnars** [comment]
Fair point. I'll fix it. :)

**Comment by magnars** [comment]
The namespace issue has been resolved, fyi. :)

**Comment by purcell** [comment]
Yay, thanks. I always point people at the elisp coding guidelines, and I think the more we can promote consistency of style, the better it is for everyone. :-)

**Pull request merged**
