### PR TITLE
Add counsel

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by purcell** [comment]
The spelling is a bit random here -- the description line says `consel`, and then the functions like `couns-git` should presumably be `counsel-git` etc.

On top of that, `couns-clj` isn't going to byte-compile properly without a dependency on `cider`.

It's not very clear to me that this is an independently useful package yet. It looks more like a few personal helper functions.

**Comment by abo-abo** [comment]
> The spelling is a bit random here -- the description line says consel, and then the functions like couns-git should presumably be counsel-git etc.

It started with just `couns-el`.

> On top of that, couns-clj isn't going to byte-compile properly without a dependency on cider.

This is by design. It's a completion package, it shouldn't depend on CIDER. But if the user happens
to have CIDER, and call `couns-clj`, it will work.

> It's not very clear to me that this is an independently useful package yet

Well, `couns-clj` is as useful as [ac-cider](http://melpa.org/#/ac-cider) to me, and `couns-git` replaces [helm-ls-git](http://melpa.org/#/helm-ls-git). Just because there's not a lot of code, it doesn't mean it's not useful.

I'll be adding other completion functions using `ivy` to this file in the future.

**Comment by purcell** [comment]
Okay, but my point is that *none* of the file will byte-compile properly without `cider`. That seems daft.

**Comment by abo-abo** [comment]
> Okay, but my point is that none of the file will byte-compile properly without cider. That seems daft.

So there's a single call to `cider-sync-request:complete`, and the byte-compile will say:

> the function `cider-sync-request:complete' is not known to be defined.

Is that a big deal? I don't think so. There are byte compilation warnings even in the Emacs-24.5
release, not to mention 60% of all MELPA packages.

**Comment by abo-abo** [comment]
> the function `cider-sync-request:complete' is not known to be defined.

Just fixed it by adding `with-no-warnings`.

**Comment by purcell** [comment]
Ah yes, you're right that it's a warning rather than an error. My mistake.

Well, I'm okay with merging this, then, but the spelling mistake on the description line will need to be fixed, and the symbol prefix, filename and package name should all match.

**Comment by purcell** [comment]
Also,

```
;; This file is part of GNU Emacs.
```

should read

```
;; This file is part of GNU Emacs.
```

:-)

Did you copy the boilerplate from a built-in file? Safer to use what `auto-insert-mode` inserts.

**Comment by abo-abo** [comment]
> Did you copy the boilerplate from a built-in file?

I don't get it, you just cite the same line twice.

**Comment by purcell** [comment]
Well spotted! Meant to add "not" to the 2nd line. :-)

**Comment by abo-abo** [comment]
> Well spotted! Meant to add "not" to the 2nd line. :-)

But it is part of Emacs. It's in GNU ELPA.

**Comment by abo-abo** [comment]
OK, prefixes fixed up.

**Comment by purcell** [comment]
> But it is part of Emacs. It's in GNU ELPA.

Oh, okay. We generally try not to distribute packages which are also actively maintained in GNU ELPA. Is `ivy` included in the ELPA package? I don't see it listed separately there. If so, then it seems odd that the packaging would be different there and here.

**Comment by abo-abo** [comment]
> Oh, okay. We generally try not to distribute packages which are also actively maintained in GNU ELPA. Is ivy included in the ELPA package? I don't see it listed separately there. If so, then it seems odd that the packaging would be different there and here.

`ivy` and `counsel` live in the `swiper` repository, all three are installed together from GNU ELPA.
`ivy` and `swiper` are distributed as separate files in MELPA.

**Comment by abo-abo** [comment]
> We generally try not to distribute packages which are also actively maintained in GNU ELPA

I like the MELPA system since it updates faster. I update in ELPA maybe once a week. Even then, it takes
around a day for the build to take place.
And if something goes wrong with the MELPA version, the user can quickly revert to ELPA.

**Comment by purcell** [comment]
> And if something goes wrong with the MELPA version, the user can quickly revert to ELPA.

Except that they might still end up loading the MELPA version of `ivy`, I suppose.

Anyway, I'm fine to add this in the meantime, when the [fix for the typo I mentioned](https://github.com/abo-abo/swiper/pull/33) is merged.

**Comment by abo-abo** [comment]
> Anyway, I'm fine to add this in the meantime, when the fix for the typo I mentioned is merged.

Thanks, I finally see the type now!

**Comment by purcell** [comment]
Great, done :-)

**Pull request merged**
