### PR TITLE
ETable + interval-list recipes

### PR DESCRIPTION
**Pull request by Silex**
Hello,

You probably don't want to merge this yet because there's discussions to be done and likely changes to be done on these repos:

https://github.com/Fuco1/interval-list
https://github.com/Fuco1/ETable

The initial discussion about adding them to MELPA is here:

https://github.com/Fuco1/ETable/issues/4

Basically as far as I understand the author is ok about them being added to MELPA stable.

@purcell: a quick review would be nice in order to fix missing dependencies / etc. I'm adding these because I'm writing another package that depends on ETable (which depends on interval-list).

@Fuco1: feel free to comment if I missunderstood something.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.

> https://github.com/Fuco1/interval-list

This should depend on (and probably require) cl-lib 0.5, and possibly depend on Emacs 24.something or ert because it defines tests.

> https://github.com/Fuco1/ETable

Looks good, though it might need to depend on Emacs 24 for eieio.

**Comment by Silex** [comment]
Alright, I'll make some PR there and tell you when they get merged.

**Comment by Silex** [comment]
@purcell: I think it's ready. I'll very like encounter more issue to fix in ETable when I publish my new package, but I can do PR there.

@Fuco1: thanks!

**Comment by purcell** [comment]
Yep, looks good, but I noticed that the etable recipe file and name are capitalised: they should be lower-case, like the `.el` files. If you can amend the commit accordingly and force-push it back here, I'll be ready to merge.

**Comment by purcell** [comment]
Thanks. :-)

**Pull request merged**
