### PR TITLE
Add mpv

### PR DESCRIPTION
**Pull request by kljohann**
See https://github.com/kljohann/mpv.el

> This package is a potpourri of helper functions to control a mpv process via its IPC interface.

(For transcription and note-taking.)

### CODE REVIEW

**Comment by purcell** [comment]
A few problems here. Firstly, the recipe says "turnip", which is why the build fails. Did you try building this locally as directed by the README? It should have failed for you locally if so, and fixing problems locally saves time for everyone.

Secondly, you need to declare a dependency on the `names` package, for `define-namespace`.

Finally, you're declaring `lexical-binding`: if the code requires this, you should depend on the `(emacs "24")` meta-package. If the code doesn't require `lexical-binding`, consider removing it to avoid confusion.

**Comment by kljohann** [comment]
Unbelievable. Every time I make a pull request for melpa I forget to stage my changes :)
I will fix the other issues, too.

**Comment by kljohann** [comment]
Fixed in [commit ec4929](https://github.com/kljohann/mpv.el/commit/ec4929ad5df1c7421d67b5cff3b21259597eb795).

**Comment by purcell** [comment]
Looks great now, thanks.

**Pull request merged**
