### PR TITLE
Add omni-tags

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
has title says :)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- The URL header in the .el file is invalid
- The `Commentary:` section in the .el file contains a copy of the copyright and instructions to refer to the README. This isn't very helpful to prospective users who see this information when they press `?` in the package menu or on the MELPA package page. So consider putting some descriptive text in there, and move the copyright text to its standard position -- enable `auto-insert-mode` and create a fresh `.el` file to see what the standard boilerplate should look like.
- Use the prefix `omni-tags-`, not `ot:`. The [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html) are the ones to follow. See [this recent discussion](https://www.reddit.com/r/emacs/comments/35kjmc/psa_devs_please_stop_using_weird_symbol_prefixes/), also.
- The `¤` and `§` in the package description line are confusing, so I'd suggest avoiding them there, or change the description to something like `Tag or annotate code or text using ¤ and §`
- The `depends-on` statement in `Cask` is redundant, since the `.el` file provides that info via cask's `package-file` directive

Hope that helps!

**Comment by AdrieanKhisbe** [comment]
Thanks for the feedback @purcell! :)
I just update my code, and push it on github along with some version tag.

**Comment by AdrieanKhisbe** [comment]
(I just realise I forgot to update the readme and remove the `ot`, but I'll do it along with adding melpa badges)

**Comment by purcell** [comment]
Okay, just ping me when done.

**Comment by AdrieanKhisbe** [comment]
finally fixed, along with a forgoten `oq:` that is now no more

**Comment by purcell** [comment]
Gerat, thanks!

**Comment by AdrieanKhisbe** [comment]
I am the one that is thaning you :)

**Pull request merged**
