### PR TITLE
Add owp-theme-emacslove

### PR DESCRIPTION
**Pull request by tumashu**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Not sure why this should be an installable elisp package, though -- it's just a bundle of js/css/templates, which will get installed into a fairly obscure directory. How does anything find it? The package doesn't provide any code which would help to locate or use the resources.

**Comment by tumashu** [comment]
The main reason is that its directory can be found easily, I use a very simple function:
```
(defun emacs-china-theme-path ()
  (file-name-directory
   (locate-library "owp-theme-emacslove")))

```

**Comment by tumashu** [comment]
manager theme by emacs package is more comfortable than by hand

**Comment by purcell** [comment]
Right, but that elisp snippet is in your own config, not inside the package. I think if you provide an autoloaded function like `owp-theme-emacslove-path` directly in the `.el` file, then I might be convinced that this could be a package. :-)

**Comment by tumashu** [comment]
Finish, please check.

**Comment by purcell** [comment]
Great, thanks!

**Pull request merged**
