### PR TITLE
 Add cask-package-toolset recipe

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Bonux: Created using this package: 

       --> cask exec package-toolset melpa-recipe -r github
       (cask-package-toolset :fetcher github :repo "AdrieanKhisbe/cask-package-toolset.el")

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Since you're using `cl-lib` and declaring `lexical-binding`, you should explicitly declare a package dependency on the minimum compatible Emacs version.

Looks good otherwise.

**Comment by purcell** [comment]
Also, why not use `(unless ...)` rather than `(when (not ...) ...)`? :-)

**Comment by AdrieanKhisbe** [comment]
*voila!* :)

**Comment by purcell** [comment]
Thanks - merged! :-)

**Comment by AdrieanKhisbe** [comment]
Merki :)

**Comment by AdrieanKhisbe** [comment]
Seems like I just learn the `:files` keyword after *why is the script not working?*  :)
Add to do a new PR: #2772

Sorry for that.

**Comment by purcell** [comment]
Not a problem. You can test recipes locally: just hit `C-c C-c` in the recipe buffer and it will be built for you, and optionally installed.

**Comment by AdrieanKhisbe** [comment]
Cool, didn't knew that :)
(should have read your message in the reverse order then)

**Pull request merged**
