### PR TITLE
Delete vs-emulation-mode

### PR DESCRIPTION
**Pull request by Fanael**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.

**Comment by jordonbiondo** [comment]
Why?

**Comment by Fanael** [comment]
It was a bad joke.

I think I still have a backup somewhere, if you need it for some reason.

**Comment by jordonbiondo** [comment]
I thought it was a pretty good joke, it got some good laughs at my office!

I just didn't want to see it go if it was being removed due to something fixable, but if it's time to retire it, I understand.

I have a fork so I'll be all set.

**Pull request merged**
