### PR TITLE
Add recipe for chronos

### PR DESCRIPTION
**Pull request by dxknight**
* A brief summary of what the package does.

Chronos provides multiple countdown/countup timers (time ranges from seconds to hours) in a special buffer, with flexible notification options.  Suitable as a cooking timer, lecture/presentation timer etc.

*  A direct link to the package repository.

https://github.com/dxknight/chronos

*  Your association with the package (e.g., are you the maintainer? have you contributed? do you just like the package a lot?).

Author

*  Relevant communications with the upstream package maintainer (e.g., package.el compatibility changes that you have submitted).

n/a

Thanks,
David.

### CODE REVIEW

**Comment by purcell** [comment]
Very nice - thanks! Looks good.

Would you mind squashing the recipe commits into just one, please? You can then force-push the branch in order to update the pull request cleanly, then ping me to merge it.

**Comment by dxknight** [comment]
The commits have been squashed and Travis CI has done its thing.

**Comment by purcell** [comment]
Thanks!

**Comment by dxknight** [comment]
Awesome! Many thanks.

**Comment by Silex** [comment]
Looks neat! going to try it out.

**Pull request merged**
