### PR TITLE
Add eopengrok recipe

### PR DESCRIPTION
**Pull request by youngker**
I would like to add a recipe for my eopengrok.el package.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- You should also declare a package dependency on `(cl-lib "0.5")`
- The `C-c s` binding is reserved for users (see the [manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html))

**Comment by purcell** [comment]
Also, you might like to just call this "opengrok.el". :-)

**Comment by youngker** [comment]
Thank you.

I fixed issues (add cl-lib, change key binding)

"opengrok.el" was used here. so I want to keep it as "eopengrok.el"
http://www.emacswiki.org/emacs/opengrok.el

**Comment by purcell** [comment]
Okay, great - merged! Thanks. :)

**Pull request merged**
