### PR TITLE
Add recipe for tldr.el

### PR DESCRIPTION
**Pull request by kuanyui**
https://github.com/kuanyui/tldr.el

### CODE REVIEW

**Comment by milkypostman** [comment]
hey cool thing. here are comments,

- needs an `;;;###autoload` line above `tldr` function.
- `defvar` should really be `defcustom` so that these things can be customizable.
- do you need lexical binding for this? i think we are still suggesting that if you don't need it that you don't use it.
- thanks for adding the emacs dependency. Is there a reason to require such a new version of emacs? I don't have an issue I was just curious.

**Comment by kuanyui** [comment]
>hey cool thing. here are comments,

Thank you for your comments because I still don't know a lot of things in Emacs Lisp.

>    needs an ;;;###autoload line above tldr function.

Now @syohex push a PR to fix it.

>    defvar should really be defcustom so that these things can be customizable.

Ok, now fixed.

>    do you need lexical binding for this? i think we are still suggesting that if you don't need it that you don't use it.

```elisp
(require 'autoinsert)
(auto-insert-mode t)
```

Emacs built-in `auto-insert-mode` insert that when I create a new `*.el` file.

>    thanks for adding the emacs dependency. Is there a reason to require such a new version of emacs? I don't have an issue I was just curious.

Because I have no elder Emacs version on my system to test...

**Comment by syohex** [comment]
> thanks for adding the emacs dependency. Is there a reason to require such a new version of emacs? I don't have an issue I was just curious.

`with-temp-buffer-window` was introduced at Emacs 24.3. And I confirmed tldr.el works on Emacs 24.3. I updated minimum Emacs version to 24.3 at https://github.com/kuanyui/tldr.el/pull/1

**Comment by milkypostman** [comment]
OK Cool, thanks :+1:

**Pull request merged**
