### PR TITLE
Please add recipe for cssfmt

### PR DESCRIPTION
**Pull request by KeenS**
cssfmt is a css code fommatter like gofmt
https://github.com/KeenS/cssfmt.el

I'm the author and tested package build locally.

### CODE REVIEW

**Comment by purcell** [comment]
Hi - this doesn't look ready for public use yet:

- Line 27 says `(gofmt-before-save)`, which definitely isn't right! :-)
- `cssfmt-after-save` shouldn't mention specific modes, and `after-save-hook` should be `before-save-hook`. Instead of this function, provide a function `cssfmt-enable-on-save` which does something like `(add-hook 'before-save-hook 'cssfmt nil t)` (note the `t` for local). You would then tell your users to add something like the following to their init file: `(add-hook 'css-mode-hook 'cssfmt-enable-on-save)`
- The `cssfmt` command won't work if the buffer doesn't have a corresponding file on disk, and using `revert-buffer` here is bad practice. Instead, use elisp to write the buffer contents to a temp file, run `cssfmt` on it, and then replace the buffer contents with the updated contents of the temp file.

Hope that helps! :-)

**Comment by KeenS** [comment]
@purcell Thank you for kind review.

* It's a mistake. I'll fix it soon.
* That's good architecture. I'll follow your advice.
* There is a reason why I use `revert-buffer`. Simply replacing buffer content with formatted code takes pointer to the start of buffer. It's very annoying, worse than using `revert-buffer`. Another option is implement patch function like `gofmt`. It generate rcs style patch then interpret the patch and edit buffer. I don't think it's a good way in which each formatter elisp reimplements patch within elisp.
I think hiding `cssfmt` from user and serving `cssfmt-enable-on-save` is an acceptable choice. How do you feel?

**Comment by purcell** [comment]
Okay, cool, I'll merge this now, but you should still make a change so that this works with buffers where `(buffer-file-name)` is `nil`.

**Comment by KeenS** [comment]
Thank you. I'll look for ways.

**Pull request merged**
