### PR TITLE
Rename evil-ranger to ranger package

### PR DESCRIPTION
**Pull request by ralesi**
As discussed in  #2922 . Let me know when you are about to approve and I will the final changes to the repository.

### CODE REVIEW

**Comment by Silex** [comment]
Hum, sorry if you know about it already but there's `dired-ranger` at https://github.com/Fuco1/dired-hacks#dired-ranger

It's not integrated with `evil` and I think it's less complete than your implementation tho.

**Comment by ralesi** [comment]
Yes, thanks, I am aware of it.  Right now it has bookmarks and copy paste ring like in ranger, but nothing that affects the interface.  I think `dired-ranger` is probably be a more ideal name, but its taken.  I was advised to not name this `ranger-mode`, as it is a derived-minor-mode of `dired`, and not a major mode.

**Comment by ralesi** [comment]
I have renamed the package to ranger and made a backup repo as evil-ranger for the time being that I will delete if this PR is approved.

**Comment by purcell** [comment]
Looks good, thanks.

**Comment by xuchunyang** [comment]
It seems the new ranger package not get built: http://melpa.org/#/ranger. melpa building should finish at least once.

**Comment by ralesi** [comment]
@xuchunyang thanks, I noticed that too.  Is there an issue with the recipe?

**Comment by purcell** [comment]
Not sure what's happening here. It's built on the server, and it's in the `archive-contents` file there.

**Comment by purcell** [comment]
We have a build issue due to an invalid package descriptor elsewhere: https://github.com/jorgenschaefer/circe/pull/198.

I'll change the corresponding part of the build to make it more robust.

**Comment by purcell** [comment]
Workaround committed in 6e015a5, which should hopefully allow the build to recover.

**Pull request merged**
