### PR TITLE
remove several problematic packages from the wiki

### PR DESCRIPTION
**Pull request by tarsius**
See #2128.

### CODE REVIEW

**Comment by milkypostman** [comment]
I think I am OK with this. Any thoughts Steve?

**Comment by milkypostman** [comment]
@purcell can revert if he thinks it's problematic. I personally don't care.

**Comment by purcell** [comment]
I'll probably reinstate `gnus-spotlight`, but other than that, I'm fine with this.

**Comment by tarsius** [comment]
I assume that means it does work with later versions than OS X Tiger and have added the package to the Emacsmirror too.

**Comment by purcell** [comment]
> I assume that means it does work with later versions than OS X Tiger

Yes, I can't see why it wouldn't -- plus, it would have been submitted to MELPA at least 7 years after Tiger.

**Pull request merged**
