### PR TITLE
Added password-generator recipe.

### PR DESCRIPTION
**Pull request by zargener**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:

- Please remove the `:files` spec from the recipe. The default is fine here. Amend the commit and force-push it here to update the PR cleanly
- The symbols in the file itself are not well namespaced. `get-random-string-char` has no package-specific prefix, and `pass-` is not a good prefix for the others. I suggest command names like `password-generator-simple`, `password-generator-strong` etc. Use the prefix `password-generator--` for "private" symbols.
- You need to `(provide 'password-generator)`
- Add `;;;###autoload` cookie comments before each interactive function so that users can easily use them without needing to explicitly load the library first.

Hope that helps!

-Steve

**Comment by zargener** [comment]
I've made needed fixes.

**Comment by purcell** [comment]
Great. Those should be `password-generator-*`, though, not `password-generator/*`, as per the [elisp guidelines](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html).

**Comment by zargener** [comment]
Okay, fixed.

**Comment by purcell** [comment]
Super, thanks! The more consistent we can make things, the better, I think. Looks like a handy package, btw.

**Pull request merged**
