### PR TITLE
Adds a recipe for pass-mode

### PR DESCRIPTION
**Pull request by NicolasPetton**
This PR add a recipe for https://github.com/NicolasPetton/pass-mode.

`pass-mode` implements a major-mode for [pass](http://www.passwordstore.org/), displaying a dirctory-like list of the keychain entries.

### CODE REVIEW

**Comment by NicolasPetton** [comment]
up?

**Comment by purcell** [comment]
Usually only major modes for file types should be called `*-mode`, so it feels like `pass` (i.e. `pass.el`) would have been a better name for this package. The fact that a major mode is used for interaction with `pass` is not important to the user. How about renaming it?

Also, have you seen http://melpa.org/#/password-store ?

**Comment by NicolasPetton** [comment]
Steve Purcell <notifications@github.com> writes:

> Usually only major modes for file types should be called `*-mode`, so
> it feels like `pass` (i.e. `pass.el`) would have been a better name
> for this package. The fact that a major mode is used for interaction
> with `pass` is not important to the user. How about renaming it?

Yes, that makes sense, I will rename it.

>
> Also, have you seen http://melpa.org/#/password-store ?

Yes, `pass` is a layer on top of `password-store`.

**Comment by NicolasPetton** [comment]
@purcell I renamed the package and updated the PR.

**Comment by purcell** [comment]
> Yes, `pass` is a layer on top of `password-store`.

Doh, right! Missed that.

**Pull request merged**
