### PR TITLE
Add company-sourcekit

### PR DESCRIPTION
**Pull request by nathankot**
* Summary: completion for xcode swift projects using SourceKit
* Repo: https://github.com/nathankot/company-sourcekit
* Association: author

This package includes two files but one is dependent on the other so
feels okay to have them in the same package

### CODE REVIEW

**Comment by milkypostman** [comment]
is there any reason that someone would want the `sourcekit` package independent of the `company-sourcekit` package? in that case we would want to split them up but I'm ok with this for now as long as that is _not_ the case.

**Comment by nathankot** [comment]
I've decided to split it up into two packages :) Please see updated pull request

**Comment by purcell** [comment]
This is really the least possible text that would satisfy `package.el`, and it would be easily improved:

```el
;;; sourcekit.el --- library to interact with sourcekitdaemon -*- lexical-binding: t -*-
;; Package-Requires: ((emacs "24.3") (dash "2.12.1") (dash-functional "1.2.0"))

;;; Commentary:

;;; Code:
```

Try creating a fresh `sourcekit.el`, then running `M-x auto-insert` -- this will help you generate a more complete boilerplate. Paste the `Package-Requires` line and original code in there, and fill out the commentary a little bit, and things will be much better.

Same re. the headers in `company-sourcekit.el`, except that there you're also missing package dependencies on `cl-lib` (or `emacs` 24.3, as in `sourcekit.el`), and `sourcekit` itself.

**Comment by nathankot** [comment]
Thanks for the help @purcell, I've pushed those changes, please take a look and let me know if it's all good!

**Comment by purcell** [comment]
Looks great - merged!

**Pull request merged**
