### PR TITLE
add recipe for tide

### PR DESCRIPTION
**Pull request by ananthakumaran**
Provides Interactive Development Environment for TypeScript

link: https://github.com/ananthakumaran/tide
association: maintainer

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Seems like `typescript.el` should be a separate package, with `tide` providing a layer on top which depends on it, and integrates it with `flycheck` etc. (Where is the "original" `typescript-mode` anyway? It doesn't appear to be in MELPA or GNU ELPA.)

**Comment by purcell** [comment]
(Re. the recipe, `(:defaults "tsserver")` would be preferable to `("*.el" "tsserver")`.)

**Comment by ananthakumaran** [comment]
`typescript-mode` was released by microsoft http://blogs.msdn.com/b/interoperability/archive/2012/10/01/sublime-text-vi-emacs-typescript-enabled.aspx. There is no canonical repository for the package. The package present in my repo is a  stripped down version of it (without moz integration). I am not interested in maintaining `typescript-mode`,  just packaging it along with tide for convenience.

updated the recipe.

**Comment by purcell** [comment]
Yeah, I guess my concern is that if a user of the official `typescript-mode` installs `tide`, then he will suddenly be using your modified version of `typescript-mode`, which I think would be unexpected.

If `tide` needs the modifications you've made, then `typescript.el` should be released as a separate package upon which `tide` can depend. And if `tide` doesn't need those modifications (ie. it could work with the official `typescript-mode`) then it also seems like `typescript.el` shouldn't be bundled with `tide`.

**Comment by ananthakumaran** [comment]
I have removed typescript.el from tide repo.

Ideally I would like to add a dependency on typescript mode and be done with it. But as it is not available on melpha or anywhere, I can't do that.

I got three options,

* Add a link to microsoft release page and ask users to install it.
* Release typescript-mode on melpha and ask users to install it.
* Release typescript-mode on melpha and add a dependency on it.

I am inclined towards 2nd option.

**Comment by purcell** [comment]
Thanks, merged.

> I got three options,
> 
>     Add a link to microsoft release page and ask users to install it.
>     Release typescript-mode on melpha and ask users to install it.
>     Release typescript-mode on melpha and add a dependency on it.
> 
> I am inclined toward 2nd option.

I think option 3 would be best: if typescript-mode is in MELPA, then there should be a proper package dependency.

**Comment by caisah** [comment]
There already is a slightly modified version of `typescript-mode` in https://github.com/aki2o/emacs-tss but it's bundled with other stuff. Maybe there is something that can be done in order to avoid duplicates. 

I personally would like to see a stand alone version of `typescript-mode` in MELPA but given the fact that nobody wants to maintain it I don't think we'll see one soon. :smile_cat:

**Pull request merged**
