### PR TITLE
flycheck-typescript-tslint added

### PR DESCRIPTION
**Pull request by Simplify**
Package: flycheck-typescript-tslint
URL: https://github.com/Simplify/flycheck-typescript-tslint
Description: Adds TSLint stylistic and programming errors to flycheck in typescript-mode
I'm author.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks -- `(typescript-mode)` isn't a valid package dependency, because the version is required. `flycheck-package` can help you with this.

**Comment by Simplify** [comment]
Version number for typescript-mode added

**Comment by purcell** [comment]
There's a missing double quote.

**Comment by Simplify** [comment]
Fixed now

**Comment by purcell** [comment]
Cool, thanks. For next time: `flycheck-package`. ;-)

**Comment by Simplify** [comment]
I have it installed, but for some reason didn't get any error in buffer. Even C-c C-c in recipe installed package without version number without any problems. I still have it installed in GNU Emacs. As dependency is 'typescript-mode-0' listed.

**Comment by purcell** [comment]
Hmm, interesting - thanks for the info. I'll take a look.

**Comment by syohex** [comment]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

Emacs document says version part is number as string.

> Its format is a list of lists. The car of each sub-list is the name of a package, as a symbol. The cadr of each sub-list is the minimum acceptable version number, as a string. For instance: 
> ;; Package-Requires: ((gnus "1.0") (bubbles "2.7.2"))

However implementation of parsing `Package-Requirements` treat version as `0` if version part is missing.

https://github.com/emacs-mirror/emacs/blob/7cc233e1e3da297882c006c1f07c628fbd4e94d5/lisp/emacs-lisp/package.el#L960-L962

**Comment by purcell** [comment]
> However implementation of parsing Package-Requirements treat version as 0 if version part is missing.

If so, that's just a quirk of the implementation in recent Emacs versions, so people should *always* include the version number, because it is mandatory.

**Pull request merged**
