### PR TITLE
Add unkillable-scratch

### PR DESCRIPTION
**Pull request by EricCrosson**
Got another package here.
This one's pretty simple, but there isn't one like it yet on melpa. Let me know if you have feedback

### CODE REVIEW

**Comment by milkypostman** [comment]
* Don't think you need the first `autoload` since you have the minor mode autoloaded.
* The documentation for the `unkillable-scratch-buffer` is not formatted correctly. You can run `checkdoc` and it'll tell you how if you're interested. Not a big deal.

**Comment by milkypostman** [comment]
Just an idea: would be cool if this thing was generalizable. So that I could maybe customize a regexp or list buffers I never wanted to delete. Not sure where else I'd want that but just something easy.

**Comment by EricCrosson** [comment]
Interesting! I like it

**Comment by EricCrosson** [comment]
Said feature has been added

**Comment by milkypostman** [comment]
nice!

**Pull request merged**
