### PR TITLE
Add stash.el recipe

### PR DESCRIPTION
**Pull request by vermiculus**
A lightweight, persistent caching solution for elisp

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, looks good. Is `lexical-binding` required? If so, you'll need to declare a dependency on `(emacs "24")`. If not, which appears to be the case, you should remove that declaration to avoid confusion.

**Comment by vermiculus** [comment]
Looks like it was auto-inserted. I seem to have just gotten used to it, but you're right – it isn't required.

**Comment by purcell** [comment]
Yeah, it's included in the default `auto-insert-mode` template in recent Emacs versions, which is probably how it got there. :-)

**Comment by vermiculus** [comment]
Fixed :)

**Comment by purcell** [comment]
Merged :)

**Pull request merged**
