### PR TITLE
Add myanmar-input-methods recipes

### PR DESCRIPTION
**Pull request by yelinkyaw**
New recipe for myanmar-input-methods is added. Could you please check and let me know if there is additional requirements.
Thank you

### CODE REVIEW

**Comment by mrkkrp** [comment]
It's not that I'm going to type Myanmar, but this has been hanging here for almost 20 days without attention, so I wonder if @purcell just overlooked the thing...

**Comment by yelinkyaw** [comment]
Thank you @mrkkrp for getting attention on my pull request. Yes, I'm hoping the feedbacks from the maintainers even if there are some issues on my request.

**Comment by purcell** [comment]
Sorry, yes, just got overlooked. Has been a very busy few weeks.

Looks good: just sent you a small fix in https://github.com/yelinkyaw/emacs-myanmar-input-methods/pull/1.

**Comment by yelinkyaw** [comment]
Thank you @purcell I just update my repo with your fix.

**Comment by purcell** [comment]
thanks!

**Pull request merged**
