### PR TITLE
Add recipe for helm-core and update recipes/helm.

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
* recipes/helm: Use all files but the ones in helm-core.
* recipes/helm-core: New.

### CODE REVIEW

**Comment by purcell** [comment]
Cool, just let me know when you've added `helm-core-pkg.el` to your repo, and we'll be ready to merge.

**Comment by purcell** [comment]
Thanks. Squashed into a single commit and applied in dfd4ac0.

**Comment by purcell** [comment]
(Sorry, commented on wrong issue.)

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> Cool, just let me know when you've added helm-core-pkg.el to your repo, and we'll be ready to merge.

Done, you can merge!

Thanks.

Sorry for the confusion, I had to close the first PR and make a second
one from a clean melpa repo.
(packages/index.html have been deleted by error running make clean after
testing packages).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by purcell** [comment]
Great, done! :-)

I'll fix up the `Makefile` so that `make clean` doesn't remove the `index.html`.

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> Great, done! :-)
>
> I'll fix up the Makefile so that make clean doesn't remove the index.html.

Good.

Thanks a lot for your help ;-)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Pull request merged**
