### PR TITLE
js2-highlight-vars

### PR DESCRIPTION
**Pull request by unhammer**
from http://mihai.bazon.net/projects/editing-javascript-with-emacs-js2-mode/js2-highlight-vars-mode

### CODE REVIEW

**Comment by purcell** [comment]
The recipe points to a nonexistent repo. Did you test it locally before submitting? Please do so - there are corresponding instructions in the README, and it's very easy. :-)

**Comment by xuchunyang** [comment]
Maybe melpa can also check some common mistakes like this one with Travis CI or should not trigger Travis CI checks for a recipe summiting PR since now it is misleading.

**Comment by purcell** [comment]
@xuchunyang Yes, that would be great, but in this case it would involve trying to build the recipe, so we would need a way to detect which recipes had been changed or added since the last successful build -- do you know of a way to do that?

**Comment by unhammer** [comment]
Wow, that was a lot easier to test than I feared; sorry for the trouble.

**Comment by purcell** [comment]
Looks good, thanks.

**Comment by purcell** [comment]
Glad you found the testing easy in the end. I'd be pleased to have feedback if anything wasn't clear.

**Pull request merged**
