### PR TITLE
Update cask-package-toolset with forgoten files

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
My bad I forgot to specify the extra files I needed to package.

Sorry :/

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Would you mind changing this to `(:defaults "bin" "templates")`? It's a little more future-proof than `"*.el"`, and therefore preferred.

**Comment by AdrieanKhisbe** [comment]
for sure! :)
Doing it right now

**Comment by AdrieanKhisbe** [comment]
*Voilà* :)

**Comment by purcell** [comment]
Thanks. Tip for future: you can use `git-rebase --interactive` to squash commits together in your local branch and keep the history clean, then `git push --force` will update the pull request.

**Comment by purcell** [comment]
(Magit makes it quite easy, of course.)

**Comment by AdrieanKhisbe** [comment]
I would have amend I haven't push before :) 
(I have the three letter alias for that :D )

**Comment by AdrieanKhisbe** [comment]
Hey @purcell, folder have been included! (YEAAAAAH, i can run the script :D),

But just one file is missing, some `templates/.gitignore` (COINCIDENCE? ^^), which for sure is excluded by some melpa rule.
What should I do to include him?, explicitly put it in the `:files` list? :)

**Comment by purcell** [comment]
Why on earth would you want there to be a `.gitignore` file inside the installed package?

**Comment by AdrieanKhisbe** [comment]
because it's a `.gitignore` template ^^
(the only on earth reason I think could work)

**Comment by purcell** [comment]
Aha! Now it all makes sense... I'll have a look, because I'm a bit surprised it's not getting copied.

**Comment by AdrieanKhisbe** [comment]
HeHe, 
The goal of the package is to help setup a CI environment for developed package, hence the `.gitignore`, `.travis.yml` and `Makefile` that need to be included :)

**Comment by purcell** [comment]
Hmm. In `pb/create-tar` we explicitly exclude various files internal to version control systems (e.g. `_darcs`, `.svn`, `.git*`). I suspect we can remove this code, which dates from the early days of MELPA in late 2011. Hey @milkypostman, what do you think?

**Comment by AdrieanKhisbe** [comment]
@purcell Maybe I should post a dedicated issue, no? :)

**Comment by purcell** [comment]
Yes please.

**Comment by AdrieanKhisbe** [comment]
done ;)

**Pull request merged**
