### PR TITLE
airline-themes recipe

### PR DESCRIPTION
**Pull request by AnthonyDiGirolamo**
Hi there!
I'd like to propose adding my airline-themes package. It is a set of themes for the [powerline](https://github.com/milkypostman/powerline) package that are designed for use with evil-mode. It is a port of the themes from [vim-airline](https://github.com/bling/vim-airline). Please checkout the repo for more info and screenshots.

https://github.com/AnthonyDiGirolamo/airline-themes

I am the package maintainer/creator. Thanks for your help!

### CODE REVIEW

**Comment by purcell** [comment]
I feel like these should be defined using `deftheme`: each variant would go in a different `airline-*-theme.el` file, and could be loaded using `load-theme`. The theme customisation system allows multiple themes to be applied simultaneously. Even the `mode-line-format` var could be set using the theme mechanism. Is there a reason why you didn't follow that approach?

The `powerline-airline-set-modeline` function also looks out of place here: its name should really have the `airline-themes-` prefix to fit the rest of the file.

And since the whole package is very specific to evil, you might consider calling it `evil-airline-themes`. Many people install new themes out of curiosity, and I for one would be surprised to find `evil` getting installed as a side-effect of installing this one. :-)

**Comment by AnthonyDiGirolamo** [comment]
Thanks for your help! I'm still new to emacs and elisp and appreciate any
suggestions.

Having them in separate files makes a lot of sense. Will the deftheme
approach be able to only apply the colors to the mode-line? I don't specify
colors for syntax highlighting or anything else. Is there an example you
could point me towards? In vim if you switch colors and a theme doesn't
define some colors the existing settings go away.

**Comment by AnthonyDiGirolamo** [comment]
I think I got the deftheme method figured out. It really is a lot cleaner/easier! 

Regarding the naming I am going to make the themes work with or without evil-mode so I can remove evil from the requirements. Given that, what do you think the name should be? Either way it will require powerline.

**Comment by AnthonyDiGirolamo** [comment]
I've updated the package with the following:
- all themes are defined using `deftheme` and stored in separate theme files
- evil is no longer a requirement and airline-themes work without evil installed (only requires powerline)
- `powerline-airline-set-modeline` is renamed to `airline-themes-set-modeline` and all functions start with `airline-themes-*`

Do I need to push a change to trigger a new travis build before it can be reviewed? The recipe doesn't seem to need updating.

**Comment by purcell** [comment]
Looks great, thanks for taking the time to clean that all up. Glad it worked out. Recipe is merged - package should build in the next couple of hours.

**Pull request merged**
