### PR TITLE
Added sexp-move recipe

### PR DESCRIPTION
**Pull request by Elzair**
I added a recipe for a package that helps one navigate S-Expression based languages (and probably others too).

### CODE REVIEW

**Comment by purcell** [comment]
Hi - thanks for this, but that repo does not exist afaict. Did you mean "sexp-mode"? Please build and test this locally following the guidelines in the README.

**Comment by syohex** [comment]
@purcell The repository is in gitlab, not github.

https://gitlab.com/elzair/sexp-mode

**Comment by purcell** [comment]
@syohex Yes, but the recipe says "sexp-move", not "sexp-mode".

**Comment by syohex** [comment]
Oh, sorry.

**Comment by Silex** [comment]
@Elzair: just curious, how does this differ from https://github.com/Fuco1/smartparens ?

**Comment by Elzair** [comment]
I renamed the git repository to sexp-move. I apologize for the typo.

**Comment by Elzair** [comment]
Well, I have never used **smart-parens** (or most of those packages). 

   I wrote **sexp-move** to make it easier to tab-through my code. I use [ParEdit](http://emacswiki.org/emacs/ParEdit) to automatically add matching parentheses, brackets, and quotation marks to my code, and I want to press *TAB* to get out of them. However, I found inadequate the [default movement commands of ParEdit](http://pub.gajendra.net/src/paredit-refcard.pdf). Here is an example of **paredit-forward**.

```elisp
(foo| (bar baz) quux)
(foo (bar baz)| quux)
```
   
   The command **paredit-forward** skips over the nested S-Expression *(bar baz)*. ParEdit has two "undocumented" commands, **paredit-forward-down** and **paredit-forward-up** that move into and out of nested expression, but it does not have any command to DWIM when traversing the code.

To fill this need, I wrote **sexp-move**.

**Comment by Elzair** [comment]
Would changing the name to **lexeme-move** help to clarify its purpose?

**Comment by purcell** [comment]
Thanks, merged. The `char-code-property` code looks a bit odd to me. Seems like `syntax-ppss` should give you all the information you would need, though I could be wrong.

**Pull request merged**
