### PR TITLE
Add a recipe for crux

### PR DESCRIPTION
**Pull request by bbatsov**
crux is another package I've recently extracted from Prelude.

### CODE REVIEW

**Comment by purcell** [comment]
This looks great, but the `crux-default-keybindings` is a bit extreme -- most of those `C-c <letter>` combos are reserved for user customisation, and off-limits for packages. I'd say that part belongs in `prelude`.

**Comment by purcell** [comment]
There are a couple of things here I can use myself to tidy up some local config bits-and-pieces. Guess we all end up sharing and stealing snippets. :-)

**Comment by bbatsov** [comment]
> There are a couple of things here I can use myself to tidy up some local config bits-and-pieces.

Well, this is optional, so I don't think it's that extreme. I can easily introduce some global `crux-mode`, but that seems like an overkill to me. I'll extend the documentation at some point with more fine-grained setup instructions and I disclaimer about the nature of those keybindings.

> Guess we all end up sharing and stealing snippets. :-)

Indeed we do. :-)

**Comment by purcell** [comment]
> Well, this is optional, so I don't think it's that extreme. I can easily introduce some global crux-mode, but that seems like an overkill to me. I'll extend the documentation at some point with more fine-grained setup instructions and I disclaimer about the nature of those keybindings.

Like I say, the keybinding config belongs in Prelude only. These are very handy commands and functions, but only Prelude users are going to want that exact set of keybindings, and neither a global mode nor disclaimers is the solution here. I feel like you've been influenced by commands like `windmove-default-keybindings`, but in that case the commands are all closely related, whereas `crux-setup-default-keybindings` is just a grab-bag of bindings you want in Prelude.

**Comment by bbatsov** [comment]
OK, OK. I'm removing them right now. Although I still don't quite get what's wrong with having an **optional** way to setup everything in some manner, which may or may not be what you want. 

I'll just list all the commands in some table.

**Comment by bbatsov** [comment]
Done.

**Comment by purcell** [comment]
> Done.

Great - I sent you a fix for the table formatting. I don't see any code changes though.

**Comment by bbatsov** [comment]
If people don't know about this function it's like it doesn't exist. Do you want me to delete it?

**Comment by purcell** [comment]
Yes please.

**Comment by bbatsov** [comment]
Done.

**Comment by purcell** [comment]
Awesome - merging now. Looking forward to using some of these.

**Comment by bbatsov** [comment]
> Looking forward to using some of these.

And contributing some more. ;-) I'd love to get as much useful commands here as possible. Long term, this package can be viewed as a staging ground for things to be added to Emacs itself eventually.

**Comment by purcell** [comment]
Yeah, normally it's a bit of an anti-pattern to move lots of unrelated pieces of "personal" config into a package -- I've declined a few such packages previously, because they're usually not widely usable. In the case of `crux`, there are some genuinely useful functions and commands, but I'd still encourage looking for opportunities to group related functionality into distinct packages where possible.

**Pull request merged**
