### PR TITLE
Add history - History utility for source code navigation

### PR DESCRIPTION
**Pull request by boyw165**
Hi MELPA team,

Here's a recipe for this utility: https://github.com/boyw165/history
This tool is for source code navigation. It's similar to `pop-global-mark` but more powerful. You can go through the whole history without losing them. Actually, `pop-global-mark` will use the latest record but also discard it. But this tool will preserve all the history and smartly ignored killed buffers or invalid symbol string.

It's really convenient to use `his-add-history`, `his-prev-history` and `his-next-history` instead of built-in old way.

Cheers

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Some feedback:

- MELPA doesn't need the `-pkg.el` file, because we can read the metadata directly from the `history.el` file. So if you remove it, it will prevent duplication. (Also, the current `-pkg.el` file is invalid, because the version string has a leading space.)
- Don't use the `his-` prefix: use `history-` instead. Bytes are cheap in 2015, and this keeps the namespace consistent!
- You have an unprefixed symbol `remove-menu-items`. This also needs a `history-` prefix.
- In `his-same-line?` you can just use `line-number-at-pos`.

**Comment by purcell** [comment]
Also, I *believe* the regexp `"\*.*\*"` is equivalent to `"*.**"`. You *might* need `"\\*.*\\*"`.

**Comment by boyw165** [comment]
Oh thanks!

**Comment by boyw165** [comment]
Hi @purcell,

Thanks for feedback, I just updated it.

> MELPA doesn't need the -pkg.el file

I refer to `company` package and there's a `company-pkg.el` file. So it is automatically generated by MELPA server? And what kind of situation do I need to use multiple packaging, `-pkg.el`?

> In his-same-line? you can just use line-number-at-pos.

I use `beginning-of-line` for performance purpose instead of `line-number-at-pos`.

**Comment by purcell** [comment]
Yes, we generate the `-pkg.el` file. So for MELPA, you never need to provide that file yourself. (Marmalade requires it, though. A good option if you want to support Marmalade is to use Cask, which can generate a `-pkg.el` file from the `.el` file.)

> I use beginning-of-line for performance purpose instead of line-number-at-pos.

Cool, just wanted to check. That makes sense. I see that `line-number-at-pos` returns the narrowed line number, which isn't very useful!

**Comment by purcell** [comment]
Added in 51d2338.

**Comment by boyw165** [comment]
@purcell ,

I install `history` package from MELPA and found there're duplicated `.xpm` and `.png` files. Is it something wrong with my receipt?

```
(history
 :fetcher github
 :repo "boyw165/history"
 :files ("*.el" "images" "images/*.xpm" "images/*.png"))
```

**Comment by purcell** [comment]
Ah, yes. The recipe above says "copy the 'images' dir with its contents, and the files 'images/*.xpm' and 'images/*.png'.

You need the following instead:

```
("*.el" ("images" "images/*.xpm" "images/*.png"))
```

I've fixed it in f51d4cc.

**Comment by boyw165** [comment]
Thank you, @purcell ~

**Pull request closed without merging**
