### PR TITLE
adding recipe for projectile-speedbar

### PR DESCRIPTION
**Pull request by anshulverma**
This package enables integration between projectile and speedbar. More specifically, it scrolls to project view in speedbar and highlights the file in the current buffer. If the file is nested under some directories, the directory tree will be expanded.

### CODE REVIEW

**Comment by milkypostman** [comment]
@andrzejsliwa friendly ping.

**Comment by andrzejsliwa** [comment]
@milkypostman ?

**Comment by purcell** [comment]
@andrzejsliwa -- I think @milkypostman meant to ping @anshulverma here, not you. :-)

**Comment by anshulverma** [comment]
Hi guys,
Sorry for the late reply.
I've applied all suggestions by @purcell (thanks for reviewing my patch). Updating the pull request with those changes shortly.
Thanks.

**Comment by anshulverma** [comment]
Looks like it will be a new pull request since I created a separate branch for this patch in my fork. I hope thats ok.

**Comment by anshulverma** [comment]
Please find a new pull request #2402 for an updated patch

**Pull request closed without merging**
