### PR TITLE
Add emms-player-mpv

### PR DESCRIPTION
**Pull request by dochang**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

Since this is a single-file package, you can simply put the package metadata in the `.el` file and delete the `-pkg.el`, because it is unnecessary. Just add:

```
;; Package-Requires: ((emms "0"))
```

and the appropriate `;; Keywords:` to the headers in the `.el` file. Note that depending on snapshot versions should be avoided, so `0` is better in this case.

**Comment by dochang** [comment]
Thank you for your advice.  I fix these issues and release version 0.0.2 .  Please merge this PR.

**Comment by purcell** [comment]
Great, done. Thanks.

**Comment by purcell** [comment]
P.S. You should use `shell-quote-argument` when building the command strings, in case `emms-mpv-input-file` contains spaces or quotes.

**Comment by dochang** [comment]
Thank you.  Fix it.

**Pull request merged**
