### PR TITLE
Add stock-ticker recipe

### PR DESCRIPTION
**Pull request by hagleitn**
Stock-ticker let's you add stock information to the mode line.

The package lives here: https://github.com/hagleitn/stock-ticker

I am the author.

### CODE REVIEW

**Comment by purcell** [comment]
Pending https://github.com/hagleitn/stock-ticker/pull/1.

**Comment by purcell** [comment]
Looks good. Couple of suggestions:

- You might consider dropping the `dash` dependency and just using the built-in `mapcar` instead of `-map`.
- Consider turning `stock-ticker-symbols` etc. into `defcustom`s, with a `defgroup`, to make them easily customisable without needing to write elisp.

**Comment by hagleitn** [comment]
Thank you for the suggestions! I've added defgroup/-custom definitions and removed the dash dependency.

**Comment by purcell** [comment]
Cool - can you also remove the `json` dependency, as per the PR I sent?

**Comment by hagleitn** [comment]
Oic. Missed the PR. I've merged it now. There's no longer json listed as a required package. Thanks!

**Comment by purcell** [comment]
Great, merged -- thanks!

**Pull request merged**
