### PR TITLE
Evil ranger package

### PR DESCRIPTION
**Pull request by ralesi**
add package to convert dired to ranger style file browser.

### CODE REVIEW

**Comment by purcell** [comment]
Is this code ready for distribution? There's a lot of commented-out code in it, and trailing `)`.

**Comment by ralesi** [comment]
Yes, i believe so. I am trying a few things and commenting them out for the the time being and I will likely split that off into a test branch, but I think I have worked out the bugs I have found.

**Comment by purcell** [comment]
Okay, then - merged.

**Comment by ralesi** [comment]
@purcell,  I was getting pushes to remove `evil` dependencies to allow usage in standard emacs and modified all evil dependent code.  As such, I would like to rename my repo to just `ranger-mode`.  What is the preferred method for switching repo names?  Just create a new PR with the name change and then change the name in github?

**Comment by purcell** [comment]
Unless it's a major mode, don't use the `-mode` suffix in a package name. Just `ranger`/`ranger.el` would be best. Fix up the code accordingly, and file a new PR which renames and fixes up the recipe. Add `:old-names (evil-ranger)` to the recipe so that the old package page will redirect to the new one.

**Pull request merged**
