### PR TITLE
Add bbyac recipe.

### PR DESCRIPTION
**Pull request by baohaojun**
I'm the author of this package.

Bbyac means: Type a Bit, and Bang! Yet Another Completion method.

The project is hosted at https://github.com/baohaojun/bbyac. It used to be named https://github.com/baohaojun/skeleton-complete, but I changed the name to avoid confusion with skeleton.el before submitting it to melpa. The Bit Bang Completion sounds more cool too.

See the readme of this project and this blog post for skeleton-complete: http://baohaojun.github.io/blog/2013/04/13/skeleton-complete.html.

Signed-off-by: Bao Haojun <baohaojun@smartisan.cn>

### CODE REVIEW

**Comment by purcell** [comment]
Looks good. Quick feedback:

- Please remove the unnecessary `:files` spec from the recipe. The default is preferred when it works, as it does here. Amend the commit and force-push it back here if you can, please, because that keeps the commit history clean
- You should add `;;;###autoload` cookie comments before the `define-minor-mode` and `define-globalized-minor-mode` lines

**Comment by purcell** [comment]
Also, please put some information in the `Commentary:` section of the file -- this will be displayed on the MELPA package page, and in Emacs when a user presses `?` in the package menu. Emacs is supposed to be self-documenting, after all. :-)

**Comment by baohaojun** [comment]
Thank you, purcell.

I have updated as you advised, please help review again.

**Comment by purcell** [comment]
Looks great - merged!

**Comment by baohaojun** [comment]
Yay!
2015年1月29日 下午4:21于 "Steve Purcell" <notifications@github.com>写道：

**Pull request merged**
