### PR TITLE
Add grepint

### PR DESCRIPTION
**Pull request by kopoli**
This is a generic grep interface, which selects a grep-like program based on context. It uses helm to select candidates.

### CODE REVIEW

**Comment by milkypostman** [comment]
Any way I could persuade you to call this helm-grepint? This would be more
inline with other helm packages.

**Comment by kopoli** [comment]
Indeed that would be a more logical naming. I'll make the change.

**Comment by kopoli** [comment]
Name of the repo, package and the contents of this commit have been changed.

**Comment by purcell** [comment]
Yay, great - merged!

**Pull request merged**
