### PR TITLE
Update avy recipe

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by purcell** [comment]
It *should* be equivalent to say `:files (:defaults (:exclude "avy-init.el"))`, but in general we suggest putting non-distributable files like `avy-init.el` in a separate `examples` subdir or similar to avoid having to change recipes over time.

**Comment by abo-abo** [comment]
Fine, I moved it somewhere else.

**Comment by purcell** [comment]
Great, thanks.

P.S. I'm enjoying `swiper` - thanks for that! `avy` hasn't quite clicked for me yet, but I've never really used `ace-jump-mode` much.

**Comment by abo-abo** [comment]
Try the swiper finalizer `swiper-avy` (comes with `swiper`, but `avy` needs to be installed).  Bound to <kbd>C-'</kbd>, it will offer you to jump to visible swiper candidates.

**Comment by purcell** [comment]
Thanks - I'll give that a go.

**Pull request closed without merging**
