### PR TITLE
Move zotxt to gitlab

### PR DESCRIPTION
**Pull request by egh**
Nothing big here, just a move off bitbucket.

### CODE REVIEW

**Comment by purcell** [comment]
I think you meant "repo" instead of "url" in the recipe, hence the Travis failure. You can test recipes locally with `C-c C-c` as noted in the README. Please just amend this commit accordingly and force-push it to update the PR.

**Comment by egh** [comment]
Sorry! Fixed.

**Comment by purcell** [comment]
Great, thanks!

**Comment by egh** [comment]
Thank you!

**Comment by milkypostman** [comment]
Np

**Pull request merged**
