### PR TITLE
Add syntax-subword recipe

### PR DESCRIPTION
**Pull request by jpkotta**
syntax-subword makes word operations more fine-grained, by effectively
making all syntax boundaries word boundaries, and also adding
boundaries in CamelCase words.

https://bitbucket.org/jpkotta/syntax-subword

I'm the maintainer of this package.

### CODE REVIEW

**Comment by milkypostman** [comment]
/Ping. after a year we delete.

**Comment by jpkotta** [comment]
Sorry for being slow.

I've merged delete-things.el into syntax-subword.el and renamed the functions.  I don't really like the names though, they're too similar (e.g. syntax-subword-delete-word vs syntax-subword-delete, which do almost but not quite the same thing).  I'm probably going to rename them again, so maybe hold off on merging.

**Comment by gsingh93** [comment]
ping @jpkotta

**Comment by jpkotta** [comment]
Yeah, sorry I'm so slow.  I still can't think of a good naming scheme, so I just gave all the questionable names a "jpk-" prefix.  Should be OK to use now.

**Comment by gsingh93** [comment]
@purcell ping

**Comment by purcell** [comment]
I'd say the `jpk-` prefix is incongruous at best. Why not just `syntax-subword-` for those too? I think `syntax-subword-delete-word` is very much better than `jpk-delete-word`, for example.

**Comment by jpkotta** [comment]
I gave them the `syntax-subword-` prefix, but it didn't seem right.  The `jpk-` functions don't really have anything to do with the subword part; they operate on either chunks of similar syntax or traditional chunks like words or lines.  Which wouldn't be a big deal, but when some of them get the `syntax-subword-` prefix, they look way too similar to the functions that operate on subwords.  The `syntax-subword-` functions are deliberately named similarly to the functions in `subword.el`.  Maybe I should just get rid of all of the `jpk-` functions.

**Comment by purcell** [comment]
I thought perhaps that “delete” in the name made their purpose clear. But yes, if they don’t really belong there for general use, probably better to clear them out.

**Comment by jpkotta** [comment]
Functions removed.

**Comment by purcell** [comment]
Recipe merged! Thanks. :-)

**Pull request merged**
