### PR TITLE
add recipe for ob-http

### PR DESCRIPTION
**Pull request by zweifisch**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this. A short `;; Commentary:` section would be nice, because it's displayed on the MELPA package page and also when the user presses `?` in the `list-packages` buffer.

Also, it seems strange that this package includes an `http-mode.el`. If that code is generally useful elsewhere, it should perhaps be packaged separately. Otherwise, `ob-http-mode.el` would be a better name and would prevent possible name clashes with other packages.

In fact, the code in `http-mode.el` looks a bit odd to me: you've got a bunch of global variables (e.g. `http-methods-regexp`), and then as soon as you start `http-mode`, those global variables are permanently set to nil. It doesn't make sense to me -- am I missing something?

Hope that helps,

-Steve

**Comment by zweifisch** [comment]
Thanks for the code review! This is my very first emacs package, followed some bad tutorial... Just updated https://github.com/zweifisch/ob-http

**Comment by xuchunyang** [comment]
@zweifisch what's your copyright licence of this package?

**Comment by zweifisch** [comment]
@xuchunyang you can do whatever you want with it..

**Comment by purcell** [comment]
Looks good now, thanks - merged!

**Pull request merged**
