### PR TITLE
Add project-persist-drawer-adaptor-sr-speedbar

### PR DESCRIPTION
**Pull request by rdallasgray**
An adaptor to use [sr-speedbar](https://github.com/emacsmirror/sr-speedbar) with [project-persist-drawer](https://github.com/rdallasgray/project-persist-drawer).

### CODE REVIEW

**Comment by purcell** [comment]
As for #2756, I think a dependency on `project-persist` is in order.

I see that `sr-speedbar` doesn't have a stable release number, hence your dependency on a snapshot version. This could lead to this package being uninstallable if you version-tag it in order to have it appear in MELPA Stable. Solution would be to get `sr-speedbar` tagged with a version number, and then depend on the stable version here.

**Comment by rdallasgray** [comment]
It's hard to tell what's going on with the versioning of `sr-speedbar` at the moment, but I've gone instead with the version that's specified in the code (which is also a tag in the Github repo, although I think Melpa sources it from the Wiki). The version/tag looks like a snapshot ref, but it *is* available as a tag.

What happens with Melpa Stable if a stable package tries to depend on a package sourced from the wiki?

**Comment by purcell** [comment]
Oh, okay, great. What's the `github` home of `sr-speedbar`? We can switch to building from there if it's the canonical source.

**Comment by purcell** [comment]
Where I said this package should depend on `project-persist`, that should of course have been `project-persist-drawer` -- the latest stable version thereof

**Comment by tarsius** [comment]
I think @rdallasgray refers to the emacsmirror repository - so not the canonical source.

The reason the format of the version strings [changed](https://github.com/emacsmirror/sr-speedbar/tags) is that @tuhdo changed the `Version` header keyword in the source. I don't think he should have done that. As far as I can tell he is not the new maintainer, so it would have been better to stick with the old format and just bump that version accordingly.

You (@purcell) might remember that I have done something similar with the magit recipe and that it caused issues. Now that there is a "timestamp version string" there will be problems once the maintainer returns and creates a release using the version string format he has chosen for his package. (The update won't automatically be installed because the version "decreased").

@tuhdo maybe you want to become the new maintainer and host this on github?

**Comment by tuhdo** [comment]
Yeah I shouldn't have changed the version. It was because I used `ediff` and mistakenly applied the hunk. Sorry about that. At that time I was fixing some Helm compatibility. About maintaining it, I think it's good as it is now and I have other packages to maintain.

**Comment by purcell** [comment]
Well, in any case, nothing on the emacswiki gets into MELPA Stable, because we never trust the version strings there. This can lead to other packages being uninstallable: the only good fix is to host the code in a supported SCM and tag it with a version number.

**Comment by tarsius** [comment]
> Sorry about that.

It's okay :-)

> About maintaining it, I think it's good as it is now and I have other packages to maintain.

It was worth a try :-)

> nothing on the emacswiki gets into MELPA Stable, because we never trust the version strings there.

Ah yes, forgot about that.

**Comment by rdallasgray** [comment]
@purcell I've added the dependency on `project-persist-drawer` (and required it). Also renamed the private functions after seeing [this](http://www.reddit.com/r/emacs/comments/35kjmc/psa_devs_please_stop_using_weird_symbol_prefixes/) :). 

Re `sr-speedbar` -- I'm not against hosting it in my Github account, tagging it and doing some light maintenance, but I wouldn't be able to contribute a lot of time at present. Does anyone know the maintenance status of it? Is there any canonical version in VC somewhere?

**Comment by tarsius** [comment]
Ask [Sebastian Rose](https://github.com/emacsmirror/sr-speedbar/blob/master/sr-speedbar.el#L4) and [Peter Lunicks](https://github.com/emacsmirror/sr-speedbar/blob/master/sr-speedbar.el#L5). They both apparently don't have a Github account, but the last time I checked email still worked :-)

**Comment by rdallasgray** [comment]
I was lazywebbing :)

**Comment by purcell** [comment]
> Also renamed the private functions after seeing this :).

Yay! :-)

> Re sr-speedbar -- I'm not against hosting it in my Github account, tagging it and doing some light maintenance, but I wouldn't be able to contribute a lot of time at present. Does anyone know the maintenance status of it? Is there any canonical version in VC somewhere?

Not that I'm aware of. If the emacswiki version is vaguely actively maintained, though, moving the canonical location would require a bit of coordination with the author.

**Pull request merged**
