### PR TITLE
Add fcopy recipe

### PR DESCRIPTION
**Pull request by ataka**
fcopy is yet another copy mode, which set the past point HERE and then search the text you copy.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. The `fmodify-*` symbols should probably be called `fcopy-modify-*` instead, so that the namespace prefix is consistent.

Also, these days you should be using `define-minor-mode` instead of making a command and running hooks manually. It'll declare the keymap for you etc., so you can just modify the keymap at the top level after the `define-minor-mode` form.

**Comment by ataka** [comment]
@purcell 
Thank you for your advice.

>  The fmodify-* symbols should probably be called fcopy-modify-*

`fmodify-*` functions provide other feature, so I decided to remove `fmodify` code from fcopy.el and create a new elisp packack in other repository.  So, now, fcopy becomes simple and provide one feature; namespace is clear.

> these days you should be using define-minor-mode

Oh, yes.  I will try.

**Comment by milkypostman** [comment]
I think that it would be more appropriate to have something like `fcopy` be the function you call and then it should start the minor mode. Many packages---I'm thinking `multiple-cursors` here---use other commands that end up initiating the mode which then sets up all the keybindings.

**Comment by ataka** [comment]
@milkypostman Thank you for your advice.  I create new command `fcopy`, and call `fcopy-mode` from it.

**Comment by milkypostman** [comment]
@ataka are you planning to try an revamp the minor mode to be a *real* minor mode?

**Comment by ataka** [comment]
@milkypostman Sorry, I am poor at English.  What does **the minor mode** mean?  What does **a real minor mode** mean?

`fcopy.el` is an old emacs package, first written before Emacs 20.  Some codes are written in old fashion.

fcopy idea comes from view-mode.  fcopy prevents users from editing text, accidentally.  fcopy does not overwrite major-mode keymap, so that users can use commands in major-mode; `mark-defun` in EmacsLisp mode for example.

A minor-mode `fcopy-mode` may not be a good manner minor-mode.  `fcopy` command starts a minor-mode `fcopy-mode` to search copy text, and then insert copied text when exiting `fcopy-mode`.  In other words, `fcopy-mode` is a part of a `fcopy` command.  I couldn't find other way to archive my purpose.

If you mean that **using minor-mode as a part of a command** is not _a real minor-mode_ , my answer is yes, fcopy-mode is not _a real minor-mode_ , and I don't have a plan to make my `fcopy-mode` _a real minor-mode_ .

**Comment by milkypostman** [comment]
I just mean to use the function 'define-minor-mode'. As per Purcell
comments above.

**Comment by ataka** [comment]
@milkypostman Thanks for your reply.
I read NEWS files.
- `easy-mmode-define-minor-mode` is introduced in Emacs 20
- `define-minor-mode` is introduced in Emacs 21, renamed from `easy-mmode-define-minor-mode`

Actually, I would like to fix my fcopy.el to work with Emacs 19, because I used to login a remote machine which has only Emacs 19 (Unbelievable!).  Hmm, supporting old old Emacs should be developed in other branch, not in master branch.

**Comment by purcell** [comment]
> I would like to fix my fcopy.el to work with Emacs 19, because I used to login a remote machine which has only Emacs 19 (Unbelievable!).

Wow!

Merging now.

**Comment by ataka** [comment]
@purcell Thank you.

**Pull request merged**
