### PR TITLE
Alchemist Server has new directory structure

### PR DESCRIPTION
**Pull request by tonini**
Hi,

I separated the Alchemist Elixir server to it's own [repository](https://github.com/tonini/alchemist-server).
As you can see there is now a new directory structure, so I needed to update the Alchemist MELPA recipe.

I hope I made the correct recipe adjustments.

Cheers

### CODE REVIEW

**Comment by purcell** [comment]
Only `"alchemist-server"` is necessary there: the whole subdir will be copied into the package. Can you amend the commit to fix this & then force push it?

**Comment by tonini** [comment]
Ok, I made the adjustments. :+1:

**Comment by tonini** [comment]
@purcell Do you think we could merge this soon? I pushed the changes already to Alchemist and now the MELPA build doesn't work because the wrong directory assumption. I guess I was a bit impatient. :smile:

**Comment by tonini** [comment]
Thanks! :heart: :yellow_heart:

**Comment by milkypostman** [comment]
np. what was the change before the amend? i was just trying to see what purcell was talking about.

**Comment by tonini** [comment]
before amend:

```el
 (alchemist
  :fetcher github		  :fetcher github
  :repo "tonini/alchemist.el"		  :repo "tonini/alchemist.el"
  :files (:defaults "*.exs" "alchemist-server" "alchemist-server/lib"))
```

after amend:

```el
 (alchemist
  :fetcher github		  :fetcher github
  :repo "tonini/alchemist.el"		  :repo "tonini/alchemist.el"
  :files (:defaults "*.exs" "alchemist-server"))
```

**Comment by milkypostman** [comment]
thanks. was just curiosity. you had amended it correctly but wanted to double check that the new repo would build. and of course it would cause you're a master at this stuff.

**Pull request merged**
