### PR TITLE
Add pony-snippets recipe

### PR DESCRIPTION
**Pull request by SeanTAllen**
Provides Yasnippets for use with the Pony programming language.

https://github.com/seantallen/pony-snippets

I'm the package maintainer.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please could you amend the recipe commit to use `:defaults` instead of `"*.el"`? It's equivalent in this case, and somewhat preferred. You can just force-push the amended commit here to update the PR, and leave a "ping" comment so I know to merge. Thanks!

**Comment by SeanTAllen** [comment]
ping

**Comment by purcell** [comment]
Super, thanks Sean.

**Comment by SeanTAllen** [comment]
Thanks Steve.

**Pull request merged**
