### PR TITLE
Add emacs interface to Docker

### PR DESCRIPTION
**Pull request by Silex**
Hello,

**Don't merge this yet**

I created this PR as a motivation booster for me to finish my package https://github.com/Silex/docker.el :) And also to notice the world that this is a work in progress, and maybe get contributors.

I'm currently discussing with @emacs-pe wether the current `docker.el` package should be renamed to `docker-tramp`, see https://github.com/emacs-pe/docker.el/issues/1.

Several things needs to be done:

- [x] Get settled on the name of this package, maybe renaming it.
- [x] Make a basic implementation for containers manipulation.
- [x] Finish the various images tasks (right now only "rmi" works).

@purcell: I'll summon you when all these tasks are done for your little review magic :)

### CODE REVIEW

**Comment by Silex** [comment]
@purcell: I was reddited so this boosts me into making a basic implementation, just to notify you that you'd soon be able to do your quick review magic :)

**Comment by purcell** [comment]
`docker.el` requires `docker-containers`, which I don't see anywhere.

**Comment by Silex** [comment]
purcell: yeah it's in the containers branch, PEBKAC I'll merge it soon.

**Comment by Silex** [comment]
@purcell: okay, the basic functionnality is there now. Still *a lot* to improve but at least I think it's MELPA-able. Is the recipe good?

**Comment by purcell** [comment]
There's a recipe for a package called `docker-api`, but in the corresponding repo there isn't a `docker-api.el` or a `docker-api-pkg.el`. So that recipe isn't really valid. The other two recipes look fine.

**Comment by Silex** [comment]
Oops, right I forgot about this one. I'll remove it for now, it'll be an extra dependencies later on but I can just change the docker-pkg.el for this and make a new PR for the dependency.

Thanks!

**Comment by Silex** [comment]
A'ight, if things looks ok I think you can merge.

**Comment by purcell** [comment]
Done, thanks!

**Comment by Silex** [comment]
:+1:

**Pull request merged**
