### PR TITLE
Add evil-rsi, a port of vim-rsi

### PR DESCRIPTION
**Pull request by linktohack**
It brings some essential `emacs` motion bindings (and potentially [RSI]...) back.

### CODE REVIEW

**Comment by purcell** [comment]
- The line `(when (auto-complete-mode) ...)` will actually enable auto-complete-mode. :-)
- In any case you're testing for `auto-complete-mode` at the wrong time: you're testing it while defining the minor mode, not while trying to enable it. What you probably want is just to make the keymap a top-level variable, then use an `(eval-after-load 'auto-complete ...)` block to add those bindings.
- I'm not sure you should be setting the global value of `ac-use-menu-map` for the user. Ideally you wouldn't modify it at all.

**Comment by linktohack** [comment]
Ok, thanks for your advices. Updated.

**Comment by purcell** [comment]
Thanks. Just pending https://github.com/linktohack/evil-rsi/pull/2 now.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
