### PR TITLE
add tao-theme

### PR DESCRIPTION
**Pull request by 11111000000**

### CODE REVIEW

**Comment by milkypostman** [comment]
the recipe says `zenburn-theme`. It should say `tao-theme`. Please update this and make sure that the recipe builds locally.

**Comment by milkypostman** [comment]
1. could we remote the `rainbow-mode` stuff? I don't like all that changing of safe evals and such. I think it's dangerous.
2. Suggest that you add a screenshot to the repo.

**Comment by purcell** [comment]
> could we remove the rainbow-mode stuff? I don't like all that changing of safe evals and such. I think it's dangerous.

Yes, that's been copied from an old version of zenburn: the rainbow-mode tweak was removed by [this pull request](https://github.com/bbatsov/zenburn-emacs/pull/178) a while ago.

**Comment by 11111000000** [comment]
ok

**Comment by 11111000000** [comment]
I need to remove only eval at the end of file, yeah?

**Comment by 11111000000** [comment]
rainbow  mode stuff removed completely

**Comment by 11111000000** [comment]
Now it's ok?

**Comment by 11111000000** [comment]
@milkypostman: what wrong with this simple package now?

**Comment by purcell** [comment]
Hi. Thanks for your patience -- we have day jobs, so we're not constantly available to review and merge packages.

There are a number of issues with the code:

- All symbols should be prefixed with `tao-theme-`, so `phi`, `golden-grayscale` etc. need to be renamed. The [elisp coding conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html) cover this nicely.
- Using `setq` inside functions creates or modifies *global* bindings. Don't do that. Use `let` or `let*` instead.
- You can just delete the `rainbow-mode` code. No point leaving it commented-out.
- Since the theme is generated from an alist of colours, you can just provide a pair of themes rather than one which the user must edit to switch from dark to light: have `tao-yin-theme.el` and `tao-yang-theme.el`, put the core machinery in `tao-theme-common.el` (renamed to avoid it being listed as a theme) and provide a simple `tao-theme-pkg.el`. A good example to follow is [apropospriate-theme](https://github.com/waymondo/apropospriate-theme).

All this feedback is provided in the spirit of helping the community and authors to have the best possible code, consistent with our goal of providing a curated package repository.

Cheers,

-Steve

**Comment by 11111000000** [comment]
Thank you for detail feedback! I do not have a lot of experience with elisp, this is a very valuable comments! The thenme was a quick hack after I switch to Emacs from Vim. In the near future make it correct

**Comment by jasonm23** [comment]
I'll help you out with this Peter @11111000000

**Comment by jasonm23** [comment]
@11111000000 Work in progress https://github.com/emacsfodder/tao-theme-emacs/tree/fixup-for-melpa

**Comment by jasonm23** [comment]
The package has been reworked.

Steve, Donald, when you have time please review.

@purcell @milkypostman

**Comment by jasonm23** [comment]
Btw There were a couple things in https://github.com/waymondo/apropospriate-theme that didn't make sense, which I replicated.

Primarily, this  https://github.com/waymondo/apropospriate-theme/blob/master/apropospriate-theme.el

It seems redundant.  Please advise.

I've added similar as tao-theme but would be happier to remove it.

**Comment by purcell** [comment]
> Primarily, this https://github.com/waymondo/apropospriate-theme/blob/master/apropospriate-theme.el
> 
> It seems redundant. Please advise.
> 
> I've added similar as tao-theme but would be happier to remove it.

Yeah, you don't need that one.

(Sorry for the slow reply. Crazy week.)

**Comment by jasonm23** [comment]
Thanks very much, I thought so.

**Comment by 11111000000** [comment]
done

**Comment by purcell** [comment]
Thanks - merged! You can - and should - remove `tao-theme.el` now as discussed in the comments here. :-)

**Comment by jasonm23** [comment]
There's a pending pull request to remove tao-theme.el

**Comment by jasonm23** [comment]
Oh ... I see I'm moments behind the timeline :D

**Comment by 11111000000** [comment]
@purcell: already removed, thanks to @jasonm23

**Comment by purcell** [comment]
Thanks folks - a good result all round.

**Pull request merged**
