### PR TITLE
Add project-persist-drawer

### PR DESCRIPTION
**Pull request by rdallasgray**
Use a project drawer with the [project-persist](https://github.com/rdallasgray/project-persist) package.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

This will need to declare a package dependency on the latest stable version of `project-persist` via a `Package-Requires` header. It should probably also `(require 'project-persist)` in order to byte-compile cleanly.

**Comment by rdallasgray** [comment]
Cheers Steve -- added the dependency in the `-pkg.el`. Is that sufficient?

**Comment by purcell** [comment]
Yep. At first reading I was looking at the `.el` file in the root dir, which is why I suggested the `Package-Requires` header.

**Comment by rdallasgray** [comment]
Hey, when should I expect new packages to appear in the repo? (No rush of course, I just can't remember how long it took last time).

**Comment by purcell** [comment]
Build cycle is currently a couple of hours, I think.

**Comment by rdallasgray** [comment]
That's what I thought. The two new recipes you merged for me don't seem to be building, then -- they're not appearing at melpa.org or using `list-packages`.

**Comment by purcell** [comment]
Lemme take a look...

**Comment by purcell** [comment]
Looks like something funky with the submodules... perhaps they're inaccessible to anonymous users?

```
2015-05-14_08:24:00.51771 Updating /home/melpa/melpa/working/project-persist-drawer/
2015-05-14_08:24:00.86331 Command '(env LC_ALL=C /usr/bin/timeout -k 60 600 git submodule update --init --recursive)' exited with non-zero status 1: Fetching origin
2015-05-14_08:24:00.86754 HEAD is now at 2f26b1e Require project-persist
2015-05-14_08:24:00.86930 Please make sure you have the correct access rights
2015-05-14_08:24:00.86994 and the repository exists.
2015-05-14_08:24:00.87022 Clone of 'git@github.com:rdallasgray/el.mk.git' into submodule path 'el.mk' failed
```

**Comment by rdallasgray** [comment]
Aha. That's because somebody used ssh rather than https to add the submodules. Fixed. I'll have a look again after lunch. Thanks for looking into it!

**Comment by purcell** [comment]
Cool. It *should* fix itself when the next build runs.

**Comment by purcell** [comment]
Package still hadn't built, so I've just cleared out the working directory and force-built it. Looking at `project-persist-drawer-adaptor-sr-speedbar`, I'm wondering if we could maybe shorten the name slightly... it's getting a bit carried away. Maybe just drop the "adaptor" bit? Dunno.

**Comment by rdallasgray** [comment]
Thanks for that, I was going to ping you and see if you could take another look. 

I agree it's a terrible mouthful. Maybe ppd-sr-speedbar? In the same way that autocomplete uses ac as a plugin prefix?

**Comment by purcell** [comment]
Yep, anything that you're happy with is fine. Bonus of short package name is that it can be a reasonable symbol prefix, ie. `ppd-sr-speedbar-...`.

**Pull request merged**
