### PR TITLE
Add swiper

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by purcell** [comment]
* Needs dependency on `(emacs "24.1")` for `lexical-binding`
* The description line should mention `helm`, e.g. "Interactive `occur' using `helm'"
* Surely you need a function `swiper--no-swiping` somewhere ;-)

**Comment by abo-abo** [comment]
> Needs dependency on (emacs "24.1") for lexical-binding

Added.

> The description line should mention helm, e.g. "Interactive occur' using helm'"

Updated, although I'm working on an `ido` back end.

> Surely you need a function swiper--no-swiping somewhere ;-)

This will turn up at some point, maybe with a `swiper-mode` :).

**Comment by purcell** [comment]
> Updated, although I'm working on an ido back end.

Ideally, then, there would be a `swiper` which provides core functionality and `ido` support, and a separate `swiper-helm` for helm users.

**Comment by abo-abo** [comment]
> Ideally, then, there would be a swiper which provides core functionality and ido support, and a separate swiper-helm for helm users.

I don't like this approach. Keeping everything in one place makes the refactoring much easier.
And there's no issue ever with matching the front end / back end versions.

Helm's author seems to share my opinion, since I have to scroll my `dired` buffer just to see all
the files that `helm` provides.

**Comment by purcell** [comment]
You have to think about how that works with package dependencies. If you declare a dependency on `helm`, then people will get `helm` installed whether they want it or not, and many will choose to avoid your package for this reason.

`helm` has a big list of files, but it does not depend on optional packages like you are doing -- they are detected at runtime. Of course, this approach means that optional code cannot be cleanly byte-compiled at package installation time, because it refers to uninstalled packages.

So `helm`'s approach is also not ideal for packaging. The fact that the whole package gets updated every day, usually for only minor changes, is a warning sign in itself.

What's the point of `package.el` and the ability to declare dependencies if we just throw everything into one package with either non-existent or unnecessary dependencies?

**Comment by purcell** [comment]
I should add that before `package.el` came along, monolithic "packages" of related code made more sense. These days we can - and should - do better.

**Comment by Silex** [comment]
Note that you can keep all the files in the same repository but offer two PR for MELPA which package different files. See https://github.com/Fuco1/dired-hacks and https://github.com/milkypostman/melpa/blob/master/recipes/dired-rainbow with https://github.com/milkypostman/melpa/blob/master/recipes/dired-filter for examples.

That way you get to keep your funky refactoring and the dependencies are correct.

**Comment by abo-abo** [comment]
> I should add that before package.el came along, monolithic "packages" of related code made more
> sense. These days we can - and should - do better.

Having thousands of packages isn't "free":

- it puts a strain on `load-path`
- packages are harder to discover and keep track of

Until the category keywords that each package specifies start to work, and by work I mean both Emacs
package manager and MELPA website should display packages by category, more monolithic packages make sense to me.

**Comment by purcell** [comment]
Most authors are pretty random with their `;; Keywords:`, so that goal is some distance away.

I think discovery of elisp is easier now than at any previous time, so it's hard to argue that smaller packages make this more difficult.

Any suggestions you have for the MELPA website's usability would be appreciated.

It would be a mistake to reject the notion of packaging and proper dependencies simply because the current system isn't perfect. Better to embrace it and work to improve it IMO.

**Comment by Silex** [comment]
@abo-abo: do you at least agree that `M-x package-install swiper` installing helm despite me never using helm is kind of wrong? If it's an optional dependency then don't put it as a dependency... helm updates all the time and it's kinda annoying.

I was hoping to replace my use of `helm-swoop` by swiper and finally get rid of `helm`.

**Comment by purcell** [comment]
> I was hoping to replace my use of helm-swoop by swiper and finally get rid of helm.

There is a [swoop without helm](https://github.com/ShingoFukuyama/emacs-swoop), in case you hadn't seen it.

**Comment by Silex** [comment]
@purcell: nope I wasn't aware of it, thanks!

**Comment by abo-abo** [comment]
> I was hoping to replace my use of helm-swoop by swiper and finally get rid of helm.

It's possible as of now. The dependency on helm was removed, it's now just an option for the matching
back end. I depend on `ivy` now - my own back end for matching using the minibuffer.

**Comment by purcell** [comment]
Great. Perhaps the default for `swiper-completion-method` should only be `'helm` if `(locate-library 'helm)` is true?

**Comment by purcell** [comment]
And should `ivy` perhaps be a separate package, upon which `swiper` would depend? Looks like it's written to be generally useful.

**Comment by abo-abo** [comment]
> Great. Perhaps the default for swiper-completion-method should only be 'helm if (locate-library 'helm) is true?

There's a dispatch in `swiper` on `(featurep 'helm)`. I'll make `ivy` the default eventually, once
the two methods are on equal ground. Currently, the `ivy` method doesn't have anchoring, which isn't
essential but is nice to have.

**Comment by abo-abo** [comment]
> And should ivy perhaps be a separate package, upon which swiper would depend? Looks like it's
> written to be generally useful.

I'd like to keep them in a single repo for now, while it's not yet clear which functionality should
belong where.

But I could try out the mentioned feature of posting a single file from the repo to MELPA.  Should I
update this request to include only `swiper.el` and post another one with `ivy.el`?

**Comment by purcell** [comment]
> I'd like to keep them in a single repo for now, while it's not yet clear which functionality should
> belong where.
> 
> But I could try out the mentioned feature of posting a single file from the repo to MELPA. Should I
> update this request to include only swiper.el and post another one with ivy.el?

Yeah, sure, that would be great. Don't forget to add a `Package-Requires` entry for ivy in `swiper.el`. :-)

**Comment by abo-abo** [comment]
OK, now `swiper` depends on `ivy`, and both depend on emacs 24.1.

**Comment by purcell** [comment]
Thanks Oleh!

**Pull request merged**
