### PR TITLE
Add Bogdanp/ido-clever-match

### PR DESCRIPTION
**Pull request by Bogdanp**
An alternative matcher for ido.

https://github.com/Bogdanp/ido-clever-match

I am the maintainer.

### CODE REVIEW

**Comment by purcell** [comment]
Which `subr-x` functions are you using? It's possible you might need to depend on a specific newer version of Emacs.

**Comment by Bogdanp** [comment]
@purcell I'm using `hash-table-keys` from `subr-x`

**Comment by purcell** [comment]
In fact, since you're using the new advice system, you'll need to depend on Emacs 24.4 anyway.

**Comment by Bogdanp** [comment]
I bumped the requirement to `24.4`. I didn't realize `advice-{add,remove}` were only introduced that recently. Thanks!

**Comment by purcell** [comment]
In time I want to make `flycheck-package` detect and warn about things like that.

**Pull request merged**
