### PR TITLE
Recipes for latex-math-preview.el and latex-math-preview-extra-data.el

### PR DESCRIPTION
**Pull request by ytaka**
I add recipes for latex-math-preview.el and latex-math-preview-extra-data.el,
which define functions to preview parts of LaTeX files.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Why are these separate packages? It would be easy to include `latex-math-preview-extra-data.el` in the same `latex-math-preview` package. It's only small, and doesn't have any extra dependencies, so I think the two files really belong together.

**Comment by ytaka** [comment]
I didn't know whether pifont and textcomp LaTeX packages are common and popular.
I was afraid that if these packages are not installed in users' LaTeX system
then it causes some errors.
However, because the two packages are included in "texlive-latex-base" package of Ubuntu,
the packages are common.
According to your suggestion, I will unify them.
So, I would wonder if you pick up only the recipe of latex-math-preview.el.

**Comment by purcell** [comment]
Yep, don't worry -- I'll add the recipe myself, and include both files.

**Comment by purcell** [comment]
Added in bd632f7. Thanks!

**Pull request closed without merging**
