### PR TITLE
Add recipe for python-docstring-mode

### PR DESCRIPTION
**Pull request by lvh**
This adds a recipe for python-docstring-mode. python-docstring-mode is a minor mode that intelligently formats Python docstrings. It knows about various docstring conventions (epytext, Sphinx) and handles them all appropriately. Here's the commentary I added upstream:

```
;; python-docstring-mode.el is a minor mode for intelligently
;; reformatting (refilling) and highlighting Python docstrings. It
;; understands both epytext and Sphinx formats (even intermingled!),
;; so it knows how to reflow them correctly. It will also highlight
;; markup in your docstrings, including epytext and reStructuredText.
```

I am not the original author, @glyph is. This pulls it from the [canonical repo](https://github.com/glyph/python-docstring-mode). I did [submit a PR to that repo](https://github.com/glyph/python-docstring-mode/pull/2) in order to bring it in line with packaging standards.

This is my first PR submitted to MELPA, and my first time trying to package some elisp with package.el, so extra help is appreciated. Particularly, I'm just guessing that's an appropriate way to package that Python script. Furthermore, while I was able to generate the package with `make` and install it with `package-install-file`, it isn't loaded by default and evaling `(require 'python-docstring)` results in `byte-code: Wrong type argument: stringp, nil`; although that seems like it's probably a bug in upstream and not a consequence of the packaging?

### CODE REVIEW

**Comment by lvh** [comment]
Hm. Just checked, and this totally works:

```
(add-to-list 'load-path "~/Projects/python-docstring-mode")
(require 'python-docstring)
```

... so I guess I did screw something up with packaging?

**Comment by glyph** [comment]
Hooray!  Thanks @lvh, I was totally not clear on how to do this; if this gets landed hopefully I can blindly copy what this PR did for a number of other elisp libraries :)

**Comment by purcell** [comment]
Okay, so the package name must match the main `.el` filename, and the header/footer lines of the `.el` file should also match -- all of those things need fixing up currently: make everything `python-docstring`, please. (The `-mode` suffix is, by convention, for major mode packages only.)

Re. the code itself, all the top-level symbols should have the `python-docstring-` prefix, but many are currently just `docstring-`. (See the [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).)

Another small thing I noticed was that using `%s` to construct the python command line will fail horribly if `python-docstring-script` contains a space. Use `shell-quote-argument` to prevent this.

Hope that helps!

**Comment by lvh** [comment]
@purcell Thanks for all the feedback! I will try to address these ASAP.

**Comment by lvh** [comment]
@purcell For clarity, you're saying this should also have the mode suffix removed?

```lisp
(define-minor-mode python-docstring-mode
...)
```

**Comment by lvh** [comment]
Thanks again for your comments, @purcell. I have [submitted a PR upstream](https://github.com/glyph/python-docstring-mode/pull/5) with the changes you requested, and updated this PR with the relevant changes here.

**Comment by glyph** [comment]
I have merged the upstream PR.

**Comment by purcell** [comment]
Thanks - squashed and applied as a single commit in e159e59.

**Pull request closed without merging**
