### PR TITLE
Create new package helm-core and make helm depend of it.

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
Hi Steve ,

I would like to make a new package helm-core and make it a dependencie for helm.
The files of helm-core and helm are fetched from same repo, helm.
I made the recipes but I am not sure if they are right.

In helm I was using helm-pkg.el to specify dependencies.
For helm core where should I put the dependencies (emacs, cl-lib) ?

Thanks.

### CODE REVIEW

**Comment by purcell** [comment]
Salut Thierry!

To have a package called `helm-core`, you need either a `helm-core.el` or a `helm-core-pkg.el`, so that the package metadata can be located.

The various third-party `helm-*` packages depend on the `helm` package, so that one should probably contain the core `helm.el` functionality. Or is your intention that other authors should depend on `helm-core` if they don't need any of the other plugins? If your plan is to keep the core separate from the various standard plugins, the other option would be to keep `helm.el` where it is, and separate the non-core plugins into a `helm-plugins` package.

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> Salut Thierry!
>
> To have a package called helm-core, you need either a helm-core.el or
> a helm-core-pkg.el, so that the package metadata can be located.

Ah, ok.

> The various third-party helm-* packages depend on the helm package, so
> that one should probably contain the core helm.el functionality. Or is
> your intention that other authors should depend on helm-core if they
> don't need any of the other plugins?

Yes.

> If your plan is to keep the core separate from the various standard
> plugins, the other option would be to keep helm.el where it is, and
> separate the non-core plugins into a helm-plugins package.

I want a helm-core package containing only 4 files and a helm package
containing all other files and depending on helm-core.
I don't want to split the helm git repo (if possible, I could of course
if really necessary).

So to resume:

helm-core: Need the 4 source *.el files + the helm-core-pkg.el file.

helm: Need all *.el but the helm-core files + the helm-pkg.el with added
helm-core as dependency.

Is this right ?

Many thanks for your help on this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Ok I have modified the helm-core recipe and added the helm-core-pkg.el,
the helm-pkg.el is modified too (added helm-core dependencie).
I am waiting now you merge the recipes (if they are correct) to merge
the changes to *.pkg.el files in helm master.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by purcell** [comment]
I think it's weird that the `helm` package would not provide `helm.el`. I personally think that what you've called `helm-core` should be `helm`, and that `helm` should be `helm-plugins`. This way, no changes would need to be made to third-party `helm-*` packages, though end users would need to install `helm-plugins` additionally.

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> I think it's weird that the helm package would not provide helm.el. I
> personally think that what you've called helm-core should be helm, and
> that helm should be helm-plugins. This way, no changes would need to
> be made to third-party helm-* packages,

Doing so (i.e helm+helm-core) will provide the same to what people have
actually, both for end users and third-party helm packages maintainers.

If third-party packages maintainers need only helm-core they will modify
their packages to have only helm-core.
I.e some third-party packages actually need more than helm-core (some
need helm-buffers.el or helm-files.el etc...).

And end-users will have what they have actually when they install helm.

> though end users would need to install helm-plugins additionally.

Yes, I don't want this, I want end-users don't feel the transition.

Also the name helm-plugins is not wanted as it is confusing with a
deprecated feature of helm which is called helm-plugins.

Gradually, in the future, I may move other helm files in independent
packages if needed.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by purcell** [comment]
Okay, cool -- just wanted to make sure everyone's on the same page before we proceed.

Apart from adding `helm-core-pkg.el` to your repo, then, we just need to fix up this PR a bit: in its current form it removes an unrelated `html` file from our repo. Can you please fix up and squash the commits?

**Comment by thierryvolpiatto** [comment]
I made a new PR on a clean repo.

**Pull request closed without merging**
