### PR TITLE
Add recipe for gildas-mode

### PR DESCRIPTION
**Pull request by smaret**
[gildas-mode](https://github.com/smaret/gildas-mode) is a major mode written by myself to edit Gildas scripts in Emacs. [Gildas](http://www.iram.fr/IRAMFR/GILDAS/) itself is a software that is used to reduce and analyze data from several radio telescopes.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Pending https://github.com/smaret/gildas-mode/pull/5

**Comment by smaret** [comment]
I've just merged PR smaret/gildas-mode#5.

**Comment by smaret** [comment]
Is there any other pending issues in gildas-mode?

**Comment by syohex** [comment]
I have sent PR(https://github.com/smaret/gildas-mode/pull/6). Please check it.

**Comment by smaret** [comment]
@syohex Thanks for the PR, I've just merged it.

**Comment by purcell** [comment]
Looks good, thanks - merged!

**Pull request merged**
