### PR TITLE
Add octopress-mode.

### PR DESCRIPTION
**Pull request by aaronbieber**
Tested using the `make' approach, everything looks OK. Open to style suggestions as always!

### CODE REVIEW

**Comment by purcell** [comment]
Thanks - looks handy. It's generally frowned upon to use the `-mode` suffix for packages which don't provide a major mode, so the better name here would be `octopress.el`. The symbol prefix `om-` should also then be `octopress-` (or `octopress--` for "private" symbols) in order to follow the [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).

**Comment by aaronbieber** [comment]
Thanks for the style advice, Steve. I renamed the repo "octopress.el," which actually also brings it in line with my other one, "sunshine.el." There is some missing documentation and other errata from `flycheck-package` that I'll clean up later, but I think it's ready to be used.

**Comment by purcell** [comment]
Thanks - squashed into a single commit in 7205d3d.

You should also fix up the face definitions to avoid illegibility for users with themes: either explicitly provide dark/light variants of the faces with both `:foreground` and `:background`, or - better - inherit from a suitable default font, e.g. `highlight`, `font-lock-comment-face` etc.

**Comment by aaronbieber** [comment]
Thanks again. I opened issue #6 to do that.

**Pull request closed without merging**
