### PR TITLE
Update jedi(auto-complete) and add company-jedi recipe

### PR DESCRIPTION
**Pull request by syohex**
`emacs-jedi` supports both `auto-complete` and `company-mode`.
So I update jedi recipe and add `company-jedi` recipe.

See
 - https://github.com/tkf/emacs-jedi/pull/180
 - https://github.com/tkf/emacs-jedi/pull/202

### CODE REVIEW

**Comment by purcell** [comment]
But now `jedi-common.el` is in two packages. That doesn't seem optimal to me: seems like there should be a package dependency instead.

**Comment by syohex** [comment]
@purcell Thanks for reviewing. I create package `jedi-core` which is common library for using from `auto-complete` jedi and `company-jedi`. And I move `company-jedi` to [another repository](https://github.com/syohex/emacs-company-jedi) because it is difficult to manage `auto-complete` and `company-mode` package at same repository.

Would you please review again ?

**Comment by purcell** [comment]
Great, thanks! -- that's much better, in my opinion. :-)

**Comment by syohex** [comment]
Thanks

**Comment by purcell** [comment]
Might need a fresh version tag in order for the recipes to work correctly on MELPA Stable.

**Comment by syohex** [comment]
Thanks again

**Pull request merged**
