### PR TITLE
Add recipe for jazz-theme

### PR DESCRIPTION
**Pull request by donderom**
A warm dark color theme initially based on zenburn-theme (https://github.com/donderom/jazz-theme).

I'm a maintainer of the package, let me know if anything else is required. Thanks Steve!

### CODE REVIEW

**Comment by milkypostman** [comment]
Merging with another commit. Please update the following though:

1. make the `Installation` section a  `;;; Commentary:` section so that it follows the standard elisp file structure.
2. Add a colon to the `;;; Code` line, so it's `;;; Code:`

Thanks for the PR

**Comment by milkypostman** [comment]
@purcell are themes not supposed to be compiled?

**Comment by milkypostman** [comment]
Closed with da25345df9d8d567541ed6b0ec832310cde67115

**Comment by purcell** [comment]
> @purcell are themes not supposed to be compiled?

I'm not aware of any reason to suppress compilation of themes. This is yet another theme where the boilerplate has been copied from that of zenburn, so the `no-byte-compile` presumably came from there.

**Comment by milkypostman** [comment]
@donderom can you remove the bottom `no-byte-compile` nonsense then too?

**Comment by donderom** [comment]
@milkypostman I've updated the file structure and removed `no-byte-compile` nonsense. Thanks for the notes! Btw in which cases `no-byte-compile` would make sense?

**Comment by purcell** [comment]
> Btw in which cases no-byte-compile would make sense?

There aren't many use cases, but there are some files which you might like to edit in `emacs-lisp-mode` which are not actually compilable code. An example would be the MELPA recipe files.

But a more common case is a `.emacs` file which you'd like to be able to use with multiple installed emacs versions -- if you byte-compiled it with one version of Emacs, you wouldn't be able to start a different version of Emacs because the byte-compiled version of `.emacs` would be loaded first, and its byte-code would likely be considered invalid.

**Comment by donderom** [comment]
@purcell Good to know, thanks a lot!

**Comment by Fanael** [comment]
> But a more common case is a `.emacs` file which you'd like to be able to use with multiple installed emacs versions -- if you byte-compiled it with one version of Emacs, you wouldn't be able to start a different version of Emacs because the byte-compiled version of `.emacs` would be loaded first, and its byte-code would likely be considered invalid.

Emacs bytecode is backward compatible, so one could compile it with the oldest Emacs version used.

**Pull request closed without merging**
