### PR TITLE
Includes missing lenticular.org file.

### PR DESCRIPTION
**Pull request by phillord**
This file includes the documentation for lentic and is needed as part of
the package.

### CODE REVIEW

**Comment by purcell** [comment]
Why's it needed? We don't normally bundle documentation unless it is in `info` format, otherwise it's just a file buried down in the package directory.

**Comment by purcell** [comment]
Is it for the `Edit->Lentic->Read Doc` command mentioned in the README?

**Comment by phillord** [comment]
Yes. All the documentation files are generated client side from the source which is lenticular.org and the .el files.

**Comment by purcell** [comment]
Alles klar. Thanks!

**Pull request merged**
