### PR TITLE
Add recipe for 'logview' package.

### PR DESCRIPTION
**Pull request by doublep**
I would like to add recipe for 'logview' package. The package is meant to highlight and interactively filter log files similar to those generated by Log4j or Logback, though with configuration it can parse many different formats as well. I'm the author.

Repository: https://github.com/doublep/logview

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this. Quick feedback:

- The regexp for `auto-mode-alist` is too general to be autoloaded: it will cause `logview-mode` to be the default for all `.log` files whenever the user has installed this mode, but that's a common extension. This setting should be at the discretion of the user.
- I don't see anything specific to Emacs 24.5, so perhaps you could just depend on `24.1`, which is the oldest version with `lexical-binding` support. Most users don't yet have 24.5.
- Consider using `cl-lib` instead of `cl`, which is now deprecated. Just add `(cl-lib "0.5")` to the list of dependencies in the `Package-Requires` header. Usually it's just a case of prefixing the functions and macros from `cl` with `cl-`.

Hope that helps!

-Steve

**Comment by doublep** [comment]
* `auto-mode-alist`: what is the general rule?  E.g. old `log4j-mode` package also claims all `.log` files, even if it understands fewer formats than `logview` (especially after customization). Various packages for programming languages grab relevant extensions, though `.log` is admittedly different. I ask because this is really not something package should change often, so if I do remove the default now, I will not be able to put it back, so I want to be sure I need to do it first.
* Emacs version: OK, down to 24.1 now. I just put the latest stable there and I have no idea how to test compatibility.
* `cl-lib`: done. I already added `cl-` prefix to function names before because `flymake` would bark otherwise.

**Comment by doublep** [comment]
Regarding `auto-mode-alist`, I committed some changes to the mode that should make it much nicer to log files it doesn't understand:
* if you switch a buffer to read-write mode (`C-x C-q`), all Logview commands are deactivated and you can edit the buffer as if it was in Fundamental mode.
* if Logview fails to guess appropriate format for the buffer, it will not place the buffer into read-only mode by itself and its commands are correspondingly not activated.

**Comment by purcell** [comment]
> auto-mode-alist: what is the general rule? E.g. old log4j-mode package also claims all .log files, even if it understands fewer formats than logview (especially after customization). Various packages for programming languages grab relevant extensions, though .log is admittedly different. I ask because this is really not something package should change often, so if I do remove the default now, I will not be able to put it back, so I want to be sure I need to do it first.

log4j-mode shouldn't do that either. The rule of thumb is that packages shouldn't confuse installation with activation: a user should be able to install a package and choose not to enable it, so aggressive autoloads are out. As an exception, it's *just* about okay to autoload `auto-mode-alist` entries for very specific file extensions associated with a particular major mode. So in the case of `.log` it would be better to just tell people to make that association themselves.

**Comment by doublep** [comment]
I have checked several packages. Every single major mode I checked adds itself to `auto-mode-alist`. Would it be enough if `logview` added itself to the *end* of the list, so that it doesn't override any other grabs, either done before or after the mode itself? I.e. `(add-to-list 'auto-mode-alist '("..." . logview-mode) t)`.

I think this is very important. As a user I (and I guess many others) certainly expect a major mode package to be active without any further configuration. Yes, I will likely want to customize its behavior, but when it "is not even there", it feels broken from the start. Maybe it's different for hardcore Emacs users (though I've been on Emacs for over 10 year already), but I don't feel like I need to read through documentation for every single thing. Moreso as package manager doesn't provide any hints of what I should do or expect after installing given package.

I'm pretty sure that 3% of users that want this mode, but activatable by explicit `M-x logview-mode` etc. will manage to add a few lines to their `.emacs` to remove standard injected mapping. Or even just put something in front of it, since it would be appended at the end.

**Comment by doublep** [comment]
Can you please reply?

**Comment by purcell** [comment]
Thanks for checking back in - sorry that this has just sat here. Having thought about it, I agree with you in this case. Will merge the recipe now.

**Comment by doublep** [comment]
Thank you.

**Pull request merged**
