### PR TITLE
Change repo to myuhe/org-toodledo

### PR DESCRIPTION
**Pull request by myuhe**
christopherjwhite/org-toodledo is no loger maintained
https://github.com/christopherjwhite/org-toodledo/issues/45

### CODE REVIEW

**Comment by purcell** [comment]
I think the default `:files` spec would be fine here, so perhaps you could remove it?

**Comment by myuhe** [comment]
`w3mexcerpt.el` is not needed. So I removed it.

**Comment by purcell** [comment]
Great -- can you also amend the recipe to completely remove the `:files` list? I don't think it's necessary.

**Comment by myuhe** [comment]
Thank you !
get rid of files property.

**Comment by purcell** [comment]
Super, thanks.

**Comment by myuhe** [comment]
:+1:

**Pull request merged**
