### PR TITLE
Add status recipe

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Recipe for emacs status

https://github.com/tromey/emacs-status/issues/1

### CODE REVIEW

**Comment by purcell** [comment]
Presumably you'd want the `.py` file too? This recipe will only include the `.el` files by default.

**Comment by AdrieanKhisbe** [comment]
indeed!!

**Comment by AdrieanKhisbe** [comment]
voilà :)
solved.

**Comment by AdrieanKhisbe** [comment]
resolved: cf @milkypostman comment

**Comment by milkypostman** [comment]
i don't know what I said. but ok. :)

**Comment by AdrieanKhisbe** [comment]
@milkypostman  ooops. I mean @purcell. ^^
(that was before the nap)

**Pull request merged**
