### PR TITLE
Add omni-scratch recipe

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**

### CODE REVIEW

**Comment by purcell** [comment]
To follow the [coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html), all the symbols should start with `omni-scratch`, so how about these renamings:

* new-scratch-buffer => omni-scratch-new-buffer
* new-scratch-major-buffer => omni-scratch-new-major-buffer

And `;;;###autoload` cookie comments for those commands would be a good idea too.

Hope that helps!

**Comment by AdrieanKhisbe** [comment]
Just applied your recommandations ;)

**Comment by purcell** [comment]
Thanks! Merged.

**Comment by AdrieanKhisbe** [comment]
:)
Tack ska du ha!

**Pull request merged**
