### PR TITLE
add recipe myTerminal-controls

### PR DESCRIPTION
**Pull request by myTerminal**
This package can be used to save key-bindings by grouping them into a single controls window. The controls window can be opened with a key-binding and the rest key-bindings are displayed within the controls window, where you can have quick-toggles or commands that you do not need to interactively call that often.

The package repository can be found at [https://github.com/myTerminal/myterminal-controls](https://github.com/myTerminal/myterminal-controls).

I am the creator and maintainer of this package.

### CODE REVIEW

**Comment by purcell** [comment]
Looks good, but the capitalisation in the filename isn't permissible, unfortunately: `myterminal-controls.el` will have to do, together with renaming the recipe and the symbols.

You'll also need a `;; Package-Requires: ((emacs "24") (cl-lib "0.5"))` header in the metadata to declare the necessary dependencies.

**Comment by myTerminal** [comment]
I have made the changes including capitalization, and adding the package dependencies. Thanks for your suggestions.

**Comment by myTerminal** [comment]
I think we're good with this, could you please merge the pull request? :)

**Comment by purcell** [comment]
Squashed into 1 commit and applied.

**Comment by dgutov** [comment]
@myTerminal Please don't put a largely unrelated URL into the URL field.

And putting two of them, separated by comma, doesn't work at all in the package description buffer.

**Comment by myTerminal** [comment]
@dgutov Sure. Will take care of that.

**Comment by myTerminal** [comment]
Thanks @purcell, one more to go.

**Pull request closed without merging**
