### PR TITLE
add recipe for DamienCassou/beginend

### PR DESCRIPTION
**Pull request by DamienCassou**
summary: Redefine M-< and M-> for some modes (e.g., dired-mode and
  message-mode)

link: https://github.com/DamienCassou/beginend

association with package: author

### CODE REVIEW

**Comment by milkypostman** [comment]
I think our general rule for packages is that even when they are installed they shouldn't modify the builtin behavior. So this package would need something like `beginner-setup` that actually sets up all the defaults for the different modes that you want setup. It's basically just to try and avoid things changing and the user not understanding why.

At least this is all my perception of how our gatekeeper (@purcell) normally does things.

**Comment by purcell** [comment]
Yup, though nothing happens unless the user loads this file, so it's kinda okay.

But rather than directly modifying all these other keymaps, it feels like there should be a `beginend-mode` local minor mode, and possibly a `beginend-dired-mode`. That way, users can just enable the minor modes to get this functionality.

**Comment by DamienCassou** [comment]
I applied your change proposal in DamienCassou/beginend@3dd05b092db1ad86ecfdf46344b26b8bd1ee642c. Please consider merging the recipe again.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
