### PR TITLE
vc-darcs: fix version detection

### LINKED ISSUE #2129: vc-darcs not migrating into melpa-stable
`vc-darcs` has been in MELPA for ages, and while it has version numbers and tags (it's currently at version 1.16), it is not available in MELPA-stable.  Note that `vc-darcs` is maintained in a `darcs` repository — perhaps that is the problem?

### PR DESCRIPTION
**Pull request by dunn**
Fixes #2129.

Should have caught this during #3423 :see_no_evil:

### CODE REVIEW

**Comment by vyp** [comment]
btw, #3421 also has a similar ci build error. Not sure if related, but mentioning in case it is. (Perhaps somehow the result of your recent contributions?)

**Comment by dunn** [comment]
Looks just like the VC software isn't being installed; darcs here and fossil in #3421. @milkypostman should Travis make sure to install them before running tests? I can't think what could have caused this to start showing up now, though.

**Comment by milkypostman** [comment]
the reason it's failing is that the test tries to build only the latest recipes added/changed. Since we only have two darcs packages, we normally don't see these errors because we never try to build darcs packages.

**Comment by milkypostman** [comment]
@dunn can you try rebasing this onto HEAD? then we can check if the changes I made to travis build fixes this?

**Comment by dunn** [comment]
:ok_woman:

**Pull request merged**
