### PR TITLE
Ponylang mode

### PR DESCRIPTION
**Pull request by abingham**
This adds a mode for editing the Pony programming language.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- `:files` is unnecessary here. Please remove it by amending the recipe commit accordingly and force-pushing the PR branch.
- The header line should read `;;; ponylang-mode.el ---`, but the `.el` is missing, which stops `package.el` from parsing it. You can use `flycheck-package` to get feedback on that sort of thing ahead of time, and enabling `auto-insert-mode` will offer to help you insert standards-compliant boilerplate when you create new elisp files.
- An `;;;###autoload` for the `define-derived-mode` form would make sense
- In Emacs 24 a better parent mode is `prog-mode` -- you can use [this trick](https://github.com/nex3/haml-mode/blob/master/haml-mode.el#L487-L492) to do that but keep Emacs 23 compatibility.
- Don't use `setq` to introduce new symbols when you can use `defvar` or `defconst` instead and document them at the same time.

Hope that helps!

**Comment by abingham** [comment]
OK, I think everything in shape now. Thanks!

**Comment by purcell** [comment]
Yes, almost: https://github.com/abingham/ponylang-mode/pull/4 was what I meant about the parent mode.

**Comment by purcell** [comment]
(Recipe added in a single commit in 8b80df0.)

**Pull request closed without merging**
