### PR TITLE
Add helm-lobste.rs

### PR DESCRIPTION
**Pull request by julienXX**
I added a recipe for my package helm-lobste.rs.el: https://github.com/julienXX/helm-lobste.rs.
It fetches stories from http://lobste.rs in an helm buffer.
Let me know if there's anything wrong with it.
Cheers!

### CODE REVIEW

**Comment by puffnfresh** [comment]
:+1:

**Comment by purcell** [comment]
Thanks! Sorry for the dealy responding: very busy week at work. Can we maybe drop the `.` from the file, package and symbol names? It's really not idiomatic.

**Comment by julienXX** [comment]
Sure, doing it right away.

**Comment by julienXX** [comment]
It should be fixed minus the repo name.

**Comment by purcell** [comment]
Thanks, that's much nicer!

**Pull request merged**
