### PR TITLE
Add helm-mu recipe

### PR DESCRIPTION
**Pull request by xuchunyang**
URL: https://github.com/emacs-helm/helm-mu

### CODE REVIEW

**Comment by tmalsburg** [comment]
Hi, I'm the author of this software and at this time I'm not in favor of the inclusion in Melpa. There is currently a serious bug in the software and I don't want to encourage people to use it as long as it isn't fixed.

**Comment by xuchunyang** [comment]
OK, I'm closing this PR.

**Comment by tmalsburg** [comment]
Thanks.  I'll see that I find a fix for this issue.  Suggestions welcome.

**Comment by xuchunyang** [comment]
helm-mu is now ready to be added to melpa.

#2815 can be closed.

**Comment by tmalsburg** [comment]
The bug that I mentioned above is fixed.  As far as I'm concerned, this can be merged.  Thank you.

**Pull request merged**
