### PR TITLE
Add gitolite-clone recipe

### PR DESCRIPTION
**Pull request by IvanMalison**
- Summary: Clone repositories from a gitolite host
- Repository: https://github.com/IvanMalison/gitolite-clone
- Association: Author/Maintainer

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- Declare `(emacs "24")` as a dependency since you're enabling `lexical-binding`
- Use `-`, not `:` in the symbol prefixes in order to match the [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html). (Your main autoloaded command can simply be called `gitolite-clone`.)
- Don't use `%s` to substitute values into strings without also using `shell-quote-argument`, otherwise substituted elements (e.g. paths) containing spaces will break your code
- Consider turning your `defvar`s into `defcustom`s where appropriate
- `M-x checkdoc` will help you ensure that you have good docstrings.

Hope that helps. :)

**Comment by IvanMalison** [comment]
> Thanks. Quick feedback:
> 
> Declare (emacs "24") as a dependency since you're enabling lexical-binding
> Use -, not : in the symbol prefixes in order to match the elisp coding conventions. (Your main autoloaded command can simply be called gitolite-clone.)
I did this, but I must say that I've never understood this convention. I like having a separator that isn't the default '-' that just separates words between the 'namespace' portion of the string and the function portion of the string. Can you shed some light on why this is preferred?
> Don't use %s to substitute values into strings without also using shell-quote-argument, otherwise substituted elements (e.g. paths) containing spaces will break your code
> Consider turning your defvars into defcustoms where appropriate
I also did this, but I must say that I've never really cared for customize very much. I don't really know very many serious emacs users that actually use it.
> M-x checkdoc will help you ensure that you have good docstrings.
Man checkdoc is strict. The requirement that arguments appear in order forced me into some very unnatural explanations of my functions behavior.
> Hope that helps. :)

**Comment by purcell** [comment]
Looks great! Merged.

Not sure of the historical background for those conventions, but if everyone just did what they preferred, the average elisp code would be harder to understand. Conventions are really just an opinionated set of rules for readability, after all.

**Comment by IvanMalison** [comment]
> Looks great! Merged.
> 
> Not sure of the historical background for those conventions, but if everyone just did what they preferred, the average elisp code would be harder to understand. Conventions are really just an opinionated set of rules for readability, after all.

Hah of course. Thanks for reviewing my code! I really appreciate it.

**Pull request merged**
