### PR TITLE
Add light theme to existing recipe

### PR DESCRIPTION
**Pull request by Malabarba**

### CODE REVIEW

**Comment by milkypostman** [comment]
something is wrong with the recipe...

**Comment by Malabarba** [comment]
> something is wrong with the recipe...

Could you help me understand the [Travis error](https://travis-ci.org/milkypostman/melpa/builds/94174087#L3122)?

It says:

> ;;; python-mode
> Fetcher: gitlab
> Source: python-mode-devs/python-mode
> Cloning https://gitlab.com/python-mode-devs/python-mode.git to /home/travis/build/milkypostman/melpa/working/python-mode/
> Command '(env LC_ALL=C /usr/bin/timeout -k 60 600 git clone https://gitlab.com/python-mode-devs/python-mode.git /home/travis/build/milkypostman/melpa/working/python-mode/)' exited with non-zero status 124: Cloning into '/home/travis/build/milkypostman/melpa/working/python-mode'...

But I have no idea what python-mode has to do with this... :(

**Comment by purcell** [comment]
Why not just use `themes/*.el`?

Re. the travis failure, probably your branch is outdated relative to our `master` -- our travis job currently builds all recipes touched in a branch. We need to fix that up.

**Comment by Malabarba** [comment]
Ok. Reformatted, rebased to current master, and switched to themes/*.el.

**Comment by purcell** [comment]
Great. Actually, I'm wondering why the light theme isn't just a separate package...? The two files don't appear to share anything, unless I'm missing something.

**Comment by Malabarba** [comment]
I don't know. Do you think it would make more sense as separate? The only thing they share is a dependence on powerline.

**Comment by purcell** [comment]
No, actually this is fine, I think.

**Comment by Malabarba** [comment]
All right; Thanks!

**Pull request merged**
