### PR TITLE
Add recipe for transpose-mark

### PR DESCRIPTION
**Pull request by AtticHacker**
Hello, apologies in advance if made any mistakes, first time and all!
https://github.com/AtticHacker/transpose-mark

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- You probably don't need `lexical-binding`, so you should remove the declaration. If it *is* needed, you must declare a `Package-Requires` dependency on emacs 24.
- You should use the standard boilerplate; enable `auto-insert-mode`, create a fresh `transpose-mark.el`, then put the existing code into that boilerplate. This will help you get the metadata right. Fill in a bit of text in the resulting `Commentary:` block.
- `transpose-mark` needs a docstring. `M-x checkdoc` will help you get docstrings standard-compliant. (`flycheck` shows checkdoc hints -- definitely worth using.)
- You've got `insert-at-point`, which should be prefixed with the package name, i.e. `transpose-mark--insert-at-point`. (`--` is a convention for marking private identifiers.)

Hope that helps!

-Steve

**Comment by AtticHacker** [comment]
Hi, thanks for the feedback!
I updated my repository by following your comments, hope this will do.

**Comment by purcell** [comment]
Great, much better! Just needs https://github.com/AtticHacker/transpose-mark/pull/1 now. :-)

**Comment by AtticHacker** [comment]
Thank you for the help, I merged your PR :)

**Comment by purcell** [comment]
Thanks then!

**Pull request merged**
