### PR TITLE
simplify auto-yasnippet recipe

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by tarsius** [comment]
There's a lot more where that came from :-)

(But I will create just one big pr for the rest, for your convenience).

**Comment by purcell** [comment]
Cool. I don't know if you noticed, but the code actually detects cases where the default `:files` spec would be equivalent, and prints out a message -- is that what you're using to inform these changes?

**Comment by tarsius** [comment]
No, it's all manual. I am not out to fix these things, I just run into them when doing what I am doing right now (adding as many packages included in Melpa to the Emacsmirror too).

Could you maybe run these automatic tests now, and fixup recipes with unnecessary `:files` entries? Would save me some time.

**Comment by purcell** [comment]
Yes, possibly. It'd involve gathering and parsing the server logs, since that's the only place we go through all the recipes.

**Comment by tarsius** [comment]
My goal for today is to mirror as many of the packages which Melpa holds but are missing from the Emacsmirror. About 2/3 I did without any inspection what-so-ever. (There where >1100 such packages, so it's not like I had a choice). But since Melpa is about libraries~=packages but the Emacsmirror only knows about repositories, I had to inspect recipes that explicitly set `:files`. I am almost done with that now, so there's no reason to rush the removal of unnecessary `:files` values.

**Comment by milkypostman** [comment]
I found the logs and can do it later with a carefully crafted shell line.
Will post an issue about it later.

**Comment by milkypostman** [comment]
The process of removing `:files` specs is painstaking because the logs are a mishmash of builds; we are doing things in parallel so its hard to connect the log message with the notice.

Fixed some in 091dcc3775ec2137cb61d66df4e72aca4900897a

will fix the rest when a build with cbac2df5cc50064e4dc5d987e9a4a77c527ce3f9 runs its course.

**Pull request merged**
