### PR TITLE
Add commify recipe.

### PR DESCRIPTION
**Pull request by ddoherty03**
Have added a small package to toggle insertion of commas or other grouping characters to a number in the buffer.

https://github.com/ddoherty03/commify

I am the package author.

My first package, so beware!

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! The `-package.el` file is unnecessary here (and would have had to be called `-pkg.el` anyway) so you should delete it please. Also, `:commify` should be `'commify` [here](https://github.com/ddoherty03/commify/blob/master/commify.el#L73).

**Comment by ddoherty03** [comment]
Wow.  That was fast.  Thanks.  Changes committed to 

https://github.com/ddoherty03/commify

**Comment by purcell** [comment]
Great, thanks - merged!

**Comment by ddoherty03** [comment]
That wasn't as painless as I feared.  Thanks.

**Pull request merged**
