### PR TITLE
Add pyenv-mode-auto package

### PR DESCRIPTION
**Pull request by ssbb**

### CODE REVIEW

**Comment by ssbb** [comment]
Build is now passing thanks to @syohex :+1:

**Comment by purcell** [comment]
Thanks. Can you rebase your pull request to remove the spurious "Trigger" commit please? We don't need/want that one! :-)

And you don't need the `-pkg.el` file -- since this is a tiny single-file package, it'd be cleaner to just add a `Package-Requires` header to the main `.el` file in order to declare your package dependencies.

**Comment by purcell** [comment]
(When you've cleaned up the PR commits, just force-push them back here to update the PR.)

**Comment by ssbb** [comment]
@purcell just done, thanks! :)

**Comment by purcell** [comment]
Super, thanks

**Pull request merged**
