### PR TITLE
ncl-mode:  add :files property to get missing files and directories.

### PR DESCRIPTION
**Pull request by yyr**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please also address my [previous comments about the `-load.el` file](https://github.com/milkypostman/melpa/pull/375#issuecomment-10234526), because I'd like to exclude it from the package. It shouldn't be necessary if all the autoloads are set up correctly. Additionally, I see that `ncl-mode` is a derived mode of `prog-mode`, which means you need to declare a package dependency on Emacs 24 in your `-pkg.el` file.

**Comment by yyr** [comment]
I tried to do as you suggested in the other thread (my recent commits in the repo has it). But it seems eval-after-load is not good idea. As I see it It assumes ncl-mode file is loading before auto-complete (or may be I am missing something obvious.).

I used the following
````
;;;###autoload
(eval-after-load 'auto-complete
...
(find-library-name "ncl-mode"
...
````
So now a cookie being picked up to eval body part in which after loading auto-complete.
The body part contains (find-library-name "ncl-mode"). Imagine loading auto-complete before ncl-mode where body part has to run. Since ncl-mode hasn't been loaded yet `find-library-name`.
simply fails.

At least thats what happening with my init which uses el-get to install packages. I am not sure about package.el.

**Comment by yyr** [comment]
With my manual tests, installing with package.el has no problems. I think you can merge now.
The issue with el-get needs some more thought. I will do it out of here.

BTW, thanks for the pull request.

**Comment by purcell** [comment]
Done.

P.S. I'd suggest getting rid of the `lisp` subdirectory, and just placing all the `.el` files together in the root. This way, the `snippets` and `dict` directories will always be in the same place relative to the `.el` files, even if the code is loaded directly from the files in the repo.

**Comment by yyr** [comment]
Thanks,

> P.S. I'd suggest getting rid of the lisp subdirectory, and just placing all the .el files together in the root

I was also thinking that. That may require another change in Melpa I guess.

**Comment by purcell** [comment]
Yep, but that's no problem for us.

**Pull request merged**
