### PR TITLE
add recipe for repeatable-motion

### PR DESCRIPTION
**Pull request by willghatch**
I made a package called repeatable-motion.  It's for wrapping motion commands to make them repeatable with commands called `repeat-motion-forward` and `repeat-motion-backward`.  So naturally I want to put it on Melpa!

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:

- `repeat-motion.el` would be a better name, since the identifier prefix should match the file and package name.
- You need to declare a package dependency on `dash`, since `common-repeatable-motions.el` uses it
- `common-repeatable-motions.el` should ideally be `repeat-motion-[something].el`, to match the package name more closely
- `repeatable-motion-pkg.el` is redundant for the purposes of MELPA: we suggest just using the standard boilerplate in the main `.el` file and filling in the appropriate metadata there. (`cask` can be used to make a `-pkg.el` file if you still need one later for Marmalade.)
- You're declaring `lexical-binding`, which implies that Emacs 24 is necessary: declare a package dependency on `(emacs "24")` or drop `lexical-binding`.
- Identifiers like `make-repeatable-motion` and `define-repeatable-pair` are not named according to the [elisp conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html): they should have a package-specific name prefix, ie. `repeat-motion-`.

Hope that helps!

-Steve

**Comment by willghatch** [comment]
Thanks for your feedback.  I've renamed things to fit a convention better, and added a Package-Requires: ((emacs "24")).  Is there anything else you think I should do before merging?  This is the first time I've actually tried packaging my elisp, and I've mostly been doing it in a hurry in some free time, so I appreciate your advice about it.

**Comment by purcell** [comment]
Sure, looks better. Sent you a couple of small fixes in https://github.com/willghatch/emacs-repeatable-motion/pull/2.

The naming is still a bit random: you've got `-` at the beginning of symbols sometimes, and after the `/` in others. Why not just use the conventions: `repeatable-motion-some-public-thing` and `repeatable-motion--internal-detail`? Consistency across projects helps everyone.

**Comment by willghatch** [comment]
Thanks for the fixes.  The one that still started with a dash was an oversight in my editing.  When I was cleaning this up having a / seemed like a good idea (a see a lot of packages use them and I thought I would as well), but since emacs convention is to just use a dash... I guess I'll just change over to that as well real quick.  I guess nobody's using my package yet to be affected by my current erratic changes in the interface.

Thanks for your help, I appreciate it.

**Comment by purcell** [comment]
Yeah, the `/` tends to be sprinkled into elisp written by people from a Clojure background. Prior to Clojure, `/` was *occasionally* used to denote private symbols: using it for public symbols is a new development. In any case, I'll go ahead and merge this recipe now - thanks for your patience. :-)

**Comment by willghatch** [comment]
Thanks, this is a feature I was looking for for a long time before I made it, so I'm hoping at least someone else in the emacs world will find it helpful.

**Comment by purcell** [comment]
+1. It's great that github and the package.el ecosystem makes it much easier to put code out there than it used to be.

**Pull request merged**
