### PR TITLE
Add evil-magit

### PR DESCRIPTION
**Pull request by justbur**
This is a new set of vim-like key bindings for magit

cc @tarsius

### CODE REVIEW

**Comment by tarsius** [comment]
As I said in https://github.com/magit/evil-magit/issues/1, my hope was that several implementations would be contributed, which could then be compared before we crown a winner. Based on https://github.com/magit/magit/issues/1968 I was hopeful, that this would happen. But it didn't and so it is only fair that the only candidate wins the race :-)

But I would like to move this out of the Magit organization. I created this repository as a organization repository to make it the "official place to forge vilified magit bindings", but now that there is an implementation, I don't want to give that an "official" blessing - not because I don't think it is good enough, but because my judgment would necessarily be rather superficial, coming from someone who is not familiar with Vim/Evil bindings. (From an Elisp perspective things look good.)

Also my experience with contributed extensions (`magit-{stgit,svn,topgit}`) wasn't so good in the past - the contributors disappeared after a while and I was stuck maintaining utilities I am not interested in using myself. And finally, since you wrote this, why not get all the praise for it?

(By the way, you might want to change the copyright and add author and maintainer header keywords. Personally I would also scrape the current history and start with a new "initial commit" at this point.)

You should have the necessary permissions to transfer the repository to your user account. Moving the repository also moved the issues. And Github redirects from the old location to the new.

**Comment by justbur** [comment]
@tarsius not a problem at all. I'm happy to do this. I was surprised when
you gave me access in fact. Just one question for you quickly. Is it ok to
keep the name evil-magit?

**Comment by tarsius** [comment]
Well, you showed initiative and also that you were taking other users' concerns into account, so I felt this was safe in your hands. And of course you can name this `evil-magit`. It's a good name, so why not use it?

**Comment by justbur** [comment]
Great, thank you, and if you change your mind, I'd be happy to give ownership back

**Comment by justbur** [comment]
This PR is now updated with the new repository

**Comment by purcell** [comment]
Thanks folks - merged.

**Pull request merged**
