### PR TITLE
Add recipe org-tfl

### PR DESCRIPTION
**Pull request by storax**
Hi, I would like to contribute my org-tfl package.

With org-tfl you can plan journeys with the [Transport for London API](https://api-portal.tfl.gov.uk/)
powered by helm and org mode.
See [org-tfl on github](https://github.com/storax/org-tfl).

### CODE REVIEW

**Comment by purcell** [comment]
Nice! Re. the recipe, please use `:defaults` rather than `"*.el"`. The former includes the latter, but is preferred.

Re. the code itself, the Helm dependency feels heavy and incongruous. Many people don't get along with helm and would be surprised/dismayed that they (apparently) couldn't use this package without it. Can the helm sources be optional? How far could you get just using an explicit command-oriented workflow and `completing-read`? That way, the user's preferred completion framework will have an opportunity to helm them perform input.

**Comment by storax** [comment]
Hi, thanks for the review. Your suggestions all seem reasonable. I hope i can manage to make helm optional and will try to use `completing-read`. I will get back as soon as I fixed it.

**Comment by storax** [comment]
I implemented your suggestion and removed the helm dependency. It is now using `completing-read`. So far I've tested it with `icicles`, the default and `helm` and it is usable with all of them.

**Comment by purcell** [comment]
Great! Sent you a further minor fix in https://github.com/storax/org-tfl/pull/3.

I tried this out locally in a recent Emacs on OS X, and the use of SVG stopped it from working for me: it seems like that format is not supported by all emacsen, so it might be something worth trying to work around.

**Comment by storax** [comment]
Thank you so much for your work and the inclusion in melpa. I'll try a workaround or worst-case make icon support optional.

**Pull request merged**
