### PR TITLE
add recipe for cloc package

### PR DESCRIPTION
**Pull request by cosmicexplorer**
This is a small attempt at cloc integration for Emacs. The functionality is
exposed through two functions: cloc, an interactive function which performs
a search through file-visiting buffers whose filepaths match the given regex
(or the current buffer, as desired), and cloc-get-results-as-plists, which
does the same thing, but parses and organizes it all into a list of plists
for easier analysis.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You'll need to depend on version 0.5 of `cl-lib`, not 1.0 -- you probably saw the latter in the list of built-in packages, but 1.0 is not installable from any package archives, and 0.5 in GNU ELPA is equivalent to the built-in 1.0.

**Comment by purcell** [comment]
(P.S. `flycheck-package` actually detects that particular issue, so you might find it helpful.)

**Comment by cosmicexplorer** [comment]
Thanks for the prompt response! I apologize about cl-lib; I was actually using flycheck, but didn't actually have cl-lib listed as a dependency at first, so when I went over it with flycheck first it was fine, but I didn't check it again after I realized I needed to add cl-lib as a dependency. That's fixed.

I also just uploaded a change which counts tramp'd buffers or buffers not visiting files (scratch buffers, for example) to be counted as well.

**Comment by purcell** [comment]
No problem. :-) Merging now.

**Comment by cosmicexplorer** [comment]
Sorry, just realized I had somehow reverted the cl-lib version back to 1.0. I checked it over again to make sure nothing else weird was happening, and it seems fine. Fixed that.

Thanks!

**Pull request merged**
