### PR TITLE
Add envdir-mode recipe.

### PR DESCRIPTION
**Pull request by proofit404**

### CODE REVIEW

**Comment by purcell** [comment]
Since this is a minor mode, can we rename this file/package to just `envdir` please? The convention is to use `-mode` only for packages which provide major modes. Looks good otherwise. Feel free to close this and open a fresh PR if it's more convenient than modifying the recipe and squashing commits etc.

**Comment by proofit404** [comment]
Should I rename all my packages to meat this convention (anaconda-mode,  edbi-minor-mode,  pyenv-mode)?

Actually I don't like `envdir.el` name. Can I leave `envdir-mode` for this?

**Comment by purcell** [comment]
> Should I rename all my packages to meat this convention (anaconda-mode, edbi-minor-mode, pyenv-mode)?

In theory, yes, because that's the convention. In practice, I'm not going to force this. But following conventions is good for everyone.

> Actually I don't like envdir.el name. Can I leave envdir-mode for this?

Yes, if you really prefer, but I'd advise against it. `envdir` is a good enough name, and almost everything in emacs is a mode anyway, so the suffix is redundant.

**Comment by purcell** [comment]
(Disclaimer: I [broke the rule myself](https://github.com/purcell/whitespace-cleanup-mode/) before becoming aware of - and accepting - the convention!)

**Comment by proofit404** [comment]
I think Principle of least astonishment is really important. What exactly I need to rename? Package filename, recipe filename, custom group name. Missing something? Should I keep `envdir-mode-` prefix for every function and variable inside my package?

If in future I'll rename my other packages downloads info will be migrated automatically? If there will be `anaconda` package with `old-names` specified and user try to install `anaconda-mode` what will exactly happens?

**Comment by purcell** [comment]
> I think Principle of least astonishment is really important. What exactly I need to rename? Package filename, recipe filename, custom group name. Missing something?

Also the package name inside the recipe file.

> Should I keep envdir-mode- prefix for every function and variable inside my package?

That's your choice: the only requirement is that all symbols should have (at least) the `envdir-` prefix. I think the `-mode-` part would be redundant for most symbols, though obviously the minor mode itself should be `envdir-mode`. :-)

> If in future I'll rename my other packages downloads info will be migrated automatically? If there will be anaconda package with old-names specified and user try to install anaconda-mode what will exactly happens?

Well, this is the problem - `:old-names` is really only for the MELPA web site (and future analysis). `package.el` won't handle it smartly, which might confuse existing users. So for this reason I wouldn't advise renaming the older packages.

**Comment by proofit404** [comment]
Done.

**Comment by purcell** [comment]
Super, thanks. Don't forget to add a `(provide 'envdir)` form.

**Comment by proofit404** [comment]
Ouch. Forgot `require`. Thanks for notice.

**Pull request merged**
