### PR TITLE
redirected request recipe to new repo

### PR DESCRIPTION
**Pull request by abingham**
Per [this discussion](https://github.com/milkypostman/melpa/issues/3459), I've redirected the request.el recipe to my fork. Hopefully @tkf will resume responsibility for this project at some point, but this fork allows us to get in some fairly critical patches in his absence.

### CODE REVIEW

**Comment by milkypostman** [comment]
just fyi, there is no autoload in this file and it's kinda bad that it wraps some of the builtin functions. but *shrug*.

**Comment by milkypostman** [comment]
looks like the original author spent a lot of time setting this package up to not want to maintain it.. lol

**Comment by abingham** [comment]
Yeah, it's really strange the way he's left it to dry like this. He's a really good developer - way better at emacs lisp than me! - so I hope he eventually decides to take it up again. Thanks for merging it in.

**Comment by milkypostman** [comment]
np

**Pull request merged**
