### PR TITLE
Added the projectile-codesearch recipe.

### PR DESCRIPTION
**Pull request by abingham**
I've added a new file to the codesearch repository, and it'll get its own recipe. This keeps the files separate.

### CODE REVIEW

**Comment by purcell** [comment]
The recipe says "codesearch" in it, rather than "projectile-codesearch". Can you please amend it to match the filename, and force-push it back here?

**Comment by purcell** [comment]
Also, you can already go ahead and add `Package-Requires` entries for the dependencies on `codesearch` and `projectile`.

**Comment by abingham** [comment]
Everything should be fixed now.

**Comment by purcell** [comment]
Squashed into a single commit and applied in aa69679. For future reference, you can `git commit --amend` and then `git push -f` to keep the commit history clean.

**Pull request closed without merging**
