### PR TITLE
Added recipe for autumn-light color theme

### PR DESCRIPTION
**Pull request by aalpern**
Another color theme, which I've been using as my primary color theme since...back when Emacs 19 was the new hotness.  Passes basic `flywheel-package-setup` and MELPA build checks. 

https://github.com/aalpern/emacs-color-theme-autumn-light

### CODE REVIEW

**Comment by purcell** [comment]
You won't actually be able to load this with `load-theme` in its current form: the `color-theme-...` naming is for the old pre-Emacs-24 `color-theme` system, whereas what you need here is `autumn-light-theme.el`. So just rename the file (and the references in it to its filename), and add the following magic incantation before the `(provide ...)` form:

```el
;;;###autoload
(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))
```

The recipe would then also need to be fixed to match the name, which you can do by amending the commit and force-pushing it back here, or simply by creating a fresh PR with a new recipe.

Hope that helps,

-Steve

**Comment by aalpern** [comment]
D'oh! They're named correctly in the `.emacs.d` I extracted them from. I guess I got over-enthusiastic about classifying by filename :)

Changes made, and thanks!

**Comment by purcell** [comment]
Filename is still `color-theme-autumn-light.el`... :-)

**Comment by aalpern** [comment]
It's definitely `autumn-light-theme.el` now - you must have seen a cached page render or something.

**Comment by purcell** [comment]
Yep, must have done, thanks. Squashed and applied as a single commit in 52a7598.

**Pull request closed without merging**
