### PR TITLE
add ac-php

### PR DESCRIPTION
**Pull request by xcwen**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.

The package name must match the file name, but `ac-php` != `auto-complete-php`.  You're using the `ac-php-` prefix internally, so you should probably rename your `.el` files.

Also, I'm surprised at the amount of functionality here, including regenerating tags etc. It doesn't seem like it all belongs inside an auto-complete plugin.

**Comment by xcwen** [comment]
ok， i will change file name .
it use phpctags gen  vim like tag,  and use  this tag files  for work.

**Comment by xcwen** [comment]
changed .

**Comment by xcwen** [comment]
(ac-php :repo "xcwen/ac-php" :fetcher github :files ("*.el" "phpctags"))
---------------
add  phpctags into package ..

**Comment by purcell** [comment]
Thanks.

**Comment by xcwen** [comment]
Thanks:>

**Pull request closed without merging**
