### PR TITLE
Added recipe for paren-completer

### PR DESCRIPTION
**Pull request by MatthewBregg**
1 A brief summary of what the package does.
===========================================

  This package enables one to insert the next closing delimiter, with a
  single command, or insert all unmatched delimiters.

2 A direct link to the package repository.
==========================================

  https://github.com/MatthewBregg/paren-completer

3 Your association with the package (e.g., are you the maintainer? have you contributed? do you just like the package a lot?).
==============================================================================================================================

  I am the creator of the package

4 Testing
=========

  I tested the package via
  ,----
  | make recipes/paren-completer
  `----
  and then installed via a fresh emacs -q, and from the make sandbox.

### CODE REVIEW

**Comment by milkypostman** [comment]
some comments,

1. your public functions shouldn't contain a double dash. that is normally reserved for private functions.

2. as a possible user of this package, could I suggest removing the `process-and-` portion of the function names. it doesn't add much to the description and they seem a bit unwieldily. you could also remove the `in-`. So you would have `paren-completer-add-delimeters-with-newline` and then `paren-completer-add-single-delimeter-with-newline` and similarly you could just have `paren-completer-add-delimeters` and then `paren-completer-add-single-delimeter`. 

3. there seem to be a lot of global variables where they should probably just be passed down. also `paren-completer--last-processed-point` isn't used.

4. you can use `defvar-local` instead of having to both declare a variable buffer local and defining that variable.

this looks pretty cool. @purcell may be aware of something that already does this "on demand" functionality?

**Comment by MatthewBregg** [comment]
Thanks for the advice, I will try to make those changes. The reason it doesn't pass down the stack is that I originally had it eagerly compute which one to add, which required it to keep a state.

**Comment by MatthewBregg** [comment]
Thank you again for the tips, I
1) Removed -in from the names.
2) Removed paren-completer--last-processed-point, and paren-completer--delimiter-stack, the stack is now passed around
3) Use defvar-local
4) I removed process-and from the public function names, and removed the double dash from the double function names.

**Comment by purcell** [comment]
> Use defvar-local

But declare a package dependency on emacs 24.3 if doing this -- `defvar-local` was only added then. If you want to retain wider compatibility, just leave the code as it is (was)

I'd also suggest tidying up the header boilerplate so it looks more conventional. The layout of the header and the number of `;` for various lines is non-standard. Try enabling `auto-insert-mode` and then creating a new `.el` file -- that's the layout you should be following, in order to enable automatic parsing by tools including `package.el`.

**Comment by MatthewBregg** [comment]
Thank you for the advice, I added a dependency on emacs 24.3, and used auto-insert to generate a new.el file, hopefully that now has the correct formatting.

**Comment by milkypostman** [comment]
ok thanks for addressing everything! merged.

**Comment by MatthewBregg** [comment]
Thank you, especially for all the formatting/code advice!

**Pull request merged**
