### PR TITLE
Add resize-window

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Add recipe for @dpsutton [resize-window](https://github.com/dpsutton/resize-window)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, but `rw-` is not a good prefix -- if everyone chose a 2-character symbol prefix, we'd only have ~600 different ones. Bytes are cheap, so can we just replace `rw-` with `resize-window-` throughout please? /cc @dpsutton.

**Comment by dpsutton** [comment]
done. thanks for the heads up.

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

**Comment by purcell** [comment]
Awesome, thanks folks!

**Comment by AdrieanKhisbe** [comment]
:)

**Pull request merged**
