### PR TITLE
Add recipe for cider-eval-sexp-fu.el

### PR DESCRIPTION
**Pull request by syl20bnr**
Hi Steve,

This PR adds a recipe for [cider-eval-sexp-fu](https://github.com/syl20bnr/cider-eval-sexp-fu).

@bbatsov Are you ok to move this to clojure-emacs ?

Cheers,
syl20bnr

### CODE REVIEW

**Comment by bbatsov** [comment]
Sure.

**Comment by bbatsov** [comment]
@syl20bnr You should now be able to transfer the repo.

**Comment by syl20bnr** [comment]
@bbatsov Done.
@purcell I updated the repo of the recipe to point on clojure-emacs.

Thank you guys!

**Comment by purcell** [comment]
Thanks guys!

**Pull request merged**
