### PR TITLE
Add discover-clj-refactor.el

### PR DESCRIPTION
**Pull request by maio**
I'm author of discover-clj-refactor.el (https://github.com/maio/discover-clj-refactor.el) and I would like it to be included in MELPA.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- Please depend on stable versions of the other packages -- you can find those version numbers on stable.melpa.org.
- The `;; Package: discover-clj-refactor` header is non-standard and redundant.

**Comment by maio** [comment]
Thanks for the feedback. I did remove package header and changed dependency on discover to stable one. But I had to leave clj-refactor dependency as it was because I'm using stuff which isn't available in stable version of this package yet. Is that OK or is there some other solution?

**Comment by purcell** [comment]
You should probably list the next `clj-refactor` version number, then. Non-snapshot version numbers in dependencies help to make sure that users who prefer MELPA Stable will still be able to install packages.

**Comment by maio** [comment]
Done.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
