### PR TITLE
Add recipe for chinese-word-at-point

### PR DESCRIPTION
**Pull request by xuchunyang**
This package mainly adds `chinese-word` thing to `thing-at-point` function.

Link: https://github.com/xuchunyang/chinese-word-at-point.el

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

Interesting that this is needed: I would have hoped that `(thing-at-point 'word)` would have worked for Chinese in standard Emacs.

**Comment by Fanael** [comment]
[Variadic arithmetic comparison operators](https://github.com/xuchunyang/chinese-word-at-point.el/blob/4697803c24f2e4b6f92271a84ee03c9aaa98b067/chinese-word-at-point.el#L68) were introduced in Emacs 24.4.

**Comment by purcell** [comment]
@xuchunyang Yes, so you should either specify `(emacs "24.4")` in the `Package-Requires:` header, or adjust the code so it will work on older versions.

**Comment by xuchunyang** [comment]
I've fixed it by using old style comparison function in [this commit](https://github.com/xuchunyang/chinese-word-at-point.el/commit/d5156cf7dba7f043e6012b633d0b4a03dec1cff4). Thank you for reminding.

**Comment by purcell** [comment]
Great - thanks!

**Pull request merged**
