### PR TITLE
get wiki last-modified date directly from http headers

### PR DESCRIPTION
**Pull request by steckerhalter**
Addresses https://github.com/milkypostman/melpa/issues/3033

It could be solved better I guess (with some more refactoring) but I want to do some other things too :)

The good thing about it is that it doesn't need two wiki requests any longer and the whole stamp-file business is also not necessary.

### CODE REVIEW

**Comment by purcell** [comment]
Looks like a big improvement - thanks a lot for this!

**Comment by milkypostman** [comment]
only thing to note is that this b0rked all the wiki packages to have a different date. i don't know why. i'm guessing something to do with timezone maybe? anyways, i'm taking this opportunity to do a clean of the temp checkouts. this should resolve my errors. there should be no issue because any new changes will overwrite even the newer dates. but just an FYI

**Comment by steckerhalter** [comment]
ok. sorry, I should have checked that before making the PR

**Comment by steckerhalter** [comment]
Are the dates higher or lower?

**Comment by milkypostman** [comment]
lower. but it's ok. it doesn't matter really.

**Comment by steckerhalter** [comment]
allright. have a nice day then :)

**Comment by milkypostman** [comment]
thanks for the PR!

**Comment by steckerhalter** [comment]
YW. I had another look at the [code](https://github.com/milkypostman/melpa/blob/master/package-build.el#L167):

```cl
(defun package-build--parse-time (str)
  "Parse STR as a time, and format as a YYYYMMDD.HHMM string."
  ;; We remove zero-padding the HH portion, as it is lost
  ;; when stored in the archive-contents
  (let* ((s (substring-no-properties str))
         (time (date-to-time
                (if (string-match "^\\([0-9]\\{4\\}\\)/\\([0-9]\\{2\\}\\)/\\([0-9]\\{2\\}\\) \\([0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\)$" str)
                    (concat (match-string 1 str) "-" (match-string 2 str) "-"
                            (match-string 3 str) " " (match-string 4 str))
                  str))))
    (concat (format-time-string "%Y%m%d." time)
            (format "%d" (or (string-to-number (format-time-string "%H%M" time)) 0)))))
```

format-time-string doc says:

```
The third, optional, argument UNIVERSAL, if non-nil, means describe TIME
as Universal Time; nil means describe TIME in the local time zone.
```

It looks like we currently get localized time out of this so it would probably be better to make it return universal time.

**Comment by purcell** [comment]
Yes. IIRC there's another issue in which we suggested using UTC throughout, but decided that it would be disruptive to do so, and therefore not desirable to rush into... :-) But it's clearly the right thing to do.

**Comment by steckerhalter** [comment]
I understand what you mean :)
Cheers

**Comment by milkypostman** [comment]
I think we should just do it. People already hate our versioning system.
Why not cause upgrades to al packages?

**Comment by steckerhalter** [comment]
Sounds like a plan :)

If it should turn out nasty I could help you out if possible somehow.

**Comment by purcell** [comment]
> I think we should just do it. People already hate our versioning system. Why not cause upgrades to al packages?

I continue to like your style...

**Comment by milkypostman** [comment]
ok so what happened here is that we actually STOPPED pulling UTC and that is why all the new times were < the old times. see https://github.com/milkypostman/melpa/issues/1661

**Comment by steckerhalter** [comment]
right, I think it is now getting GMT in the date string from the headers and before it was getting UTC which wasn't understood by `date-to-time`

**Pull request merged**
