### PR TITLE
I have added a recipe for evil-dvorak

### PR DESCRIPTION
**Pull request by jbranso**
**brief summary of what the package does:**
evil-dvorak is an emacs minor mode that lets a user use evil-mode with key-bindings that work better with a dvorak keyboard. For example in normal mode, "a" and "u" are equivalent to "^" and "$" respectively.  It can be enabled as buffer local or globally, much like evil-surround.

**A direct link to the package repository**
https://github.com/jbranso/evil-dvorak

**Your association with the package**

I am the creator and current maintainer.

**Relevant communications with the upstream package maintainer (e.g., package.el compatibility changes that you have submitted).**

I'm not sure what this means, but I am using the latest version of emacs.  I have only tested evil-dvorak mode on the latest version of emacs, and I have not contacted the maintainer of evil-mode to tell him about evil-dvorak.el  If you need to contact me, you can email me at jbranso@purdue.edu
(with the subject "evil-dvorak-mode" please).  Thank you!

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this.

This recipe will also pull in `evil-web.el`. I'm not clear what that file is for, though I note that some of it has been copied and pasted from `evil-dvorak`, e.g. [here](https://github.com/jbranso/evil-dvorak/blob/master/evil-web.el#L42).

If that file is specific to dvorak, then it would be better named `evil-dvorak-web.el`, and the public symbols in it renamed to match.

**Comment by jbranso** [comment]
You are very welcome, and evil-web.el is my next project and is not needed for evil-dvorak.el.  I must have included it in the repo by mistake.  I've removed evil-web.el from the repo.

**Comment by purcell** [comment]
Super, thanks. Merged. :-)

**Comment by jbranso** [comment]
Awesome! Also, I love your .emacs.d. I forked it a couple of weeks ago, and it rocks! Cheerio!

**Comment by purcell** [comment]
I'm happy you're finding it helpful. I'm glad I put it up on github... :-)

**Pull request merged**
