### PR TITLE
add recipe for on-parens

### PR DESCRIPTION
**Pull request by willghatch**
On-parens is a wrapper for smartparens for use in evil-normal-state.  It supplies sexp movement commands that work the way I feel such movements should work in vim/evil, respecting the notion of the cursor being on a character rather than between characters.

It's pretty hacky and I mostly threw most of it together in a few hours this morning, but I've been looking for a package like this forever, and I figure someone else may want this as well.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Looks okay, but:

- The declared dependencies `(evil) (smartparens)` are invalid, because the version numbers are mandatory. Please use the latest stable versions listed on melpa.stable.org.
- I think it's more idiomatic to append the `-*- lexical-binding: t -*-` declaration to the end of the description line. Both the description and that declaration should strictly be on the first line of the file.

**Comment by willghatch** [comment]
Done.


On June 25, 2015 2:37:59 PM MDT, Steve Purcell <notifications@github.com> wrote:
>Thanks. Looks okay, but:
>
>- The declared dependencies `(evil) (smartparens)` are invalid, because
>the version numbers are mandatory. Please use the latest stable
>versions listed on melpa.stable.org.
>- I think it's more idiomatic to append the `-*- lexical-binding: t
>-*-` declaration to the end of the description line. Both the
>description and that declaration should strictly be on the first line
>of the file.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/milkypostman/melpa/pull/2882#issuecomment-115390234

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by purcell** [comment]
Thanks, merged.

**Comment by willghatch** [comment]
Melpa has said it's rebuilt various times since this merge, but it hasn't shown up yet.  I can build it locally with no problems.  Is something going wrong with Melpa?  I know there was some issue a few weeks ago that was presumed to be from package overload during the build process or something...

**Comment by purcell** [comment]
Disk on build server is full, sorry. Working on a solution.

**Comment by willghatch** [comment]
No worries. Just wondered what was up. Good luck, I really appreciate you guys keeping up melpa. Thanks for all your work.

On June 27, 2015 5:24:36 PM MDT, Steve Purcell <notifications@github.com> wrote:
>Disk on build server is full, sorry. Working on a solution.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/milkypostman/melpa/pull/2882#issuecomment-116165418

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
