### PR TITLE
Add recipe for simple-highlight

### PR DESCRIPTION
**Pull request by rranelli**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. How does this differ from the built-in `highlight-symbol-at-point` function?

**Comment by rranelli** [comment]
Mostly the ability to `unhighlight` the symbol at point in the same way you can highlight. Also, you can unhighlight everything with a single command. I couldn't find this functionality built in.

**Comment by purcell** [comment]
`highlight-symbol` (to which `highlight-symbol-at-point` is aliased) itself toggles highlighting. And there's a `highlight-symbol-remove-all` command. So I feel like this code is redundant.

**Comment by rranelli** [comment]
I couldn't reproduce the behavior you mentioned.
Calling `highlight-symbol-at-point` twice does not remove the highlight, and I couldn't find `highlight-symbol-remove-all`.

I'm using emacs 24.5.1.

**Comment by rranelli** [comment]
Hm...

Are you talking about: https://github.com/nschum/highlight-symbol.el/blob/master/highlight-symbol.el ??

In my mind you were talking about built-in functions only

**Comment by purcell** [comment]
Yes, my mistake. Not a built-in, just a very widely-used package for this.

**Comment by rranelli** [comment]
Yep. It seems you sir are absolutely right. All the functionality I needed is available in `highlight-symbol.el` and none of it conflicts with magit's, wl's and org-agenda's color (which was the reason I wrote simple-highlight).

Hence, I'm closing this PR.

Thanks for the attention and sorry for the blunder.

**Comment by purcell** [comment]
No problem -- I'm sure you had fun writing this package, and it's a nice piece of work.

**Pull request closed without merging**
