### PR TITLE
Add omni-log recipe

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**

### CODE REVIEW

**Comment by milkypostman** [comment]
the only problem I see is that all the functions are prefixed with `l-` but the package name is `omni-log`. So there is a little oddity here.

That is the only thing I can see technically. Is this package intended in the long-run to be something used by another package or something?

**Comment by AdrieanKhisbe** [comment]
Yep that's the point. I'm already using it in my [omni-quotes](https://github.com/AdrieanKhisbe/omni-quotes.el) package for which I haven't made the recipe yet.

**Comment by purcell** [comment]
Yeah, that prefix should really be `omni-log-` to fit the elisp conventions... I doubt it would be a problem for usability, because that's still a pretty short prefix.

**Comment by AdrieanKhisbe** [comment]
I won't resist :)
Modif done

**Comment by purcell** [comment]
Great, thanks!

**Comment by AdrieanKhisbe** [comment]
c'est moi :)

**Pull request merged**
