### PR TITLE
recipes/general-close added

### PR DESCRIPTION
**Pull request by andreas-roehler**

### CODE REVIEW

**Comment by andreas-roehler** [comment]
melpa was requested several times

See https://github.com/emacs-berlin/general-close/issues/2

**Comment by purcell** [comment]
Thanks. The symbol naming is a bit random in these files. There are prefixes like `gen--`, `gen-`, `gc--` etc. -- the code should instead follow the [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html) and prefix all top-level symbols with `general-close-` (or `general-close--` for package-private symbols).

**Comment by andreas-roehler** [comment]
Am 24.07.2015 um 14:41 schrieb Steve Purcell:
>
> Thanks. The symbol naming is a bit random in these files. There are 
> prefixes like |gen--|, |gen-|, |gc--| etc. -- the code should instead 
> follow the elisp coding conventions 
> <https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html> 
> and prefix all top-level symbols with |general-close-| (or 
> |general-close--| for package-private symbols).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/milkypostman/melpa/pull/2958#issuecomment-124507413>.
>

Done, thanks!

**Comment by purcell** [comment]
There's also some code which is creating and setting unprefixed top-level variables, e.g. `(setq done (member (char-before) (list ?\t ?\n ?\ ?=)))` [here](https://github.com/emacs-berlin/general-close/blob/master/general-close-modes.el#L74). You should be using `(let ...)` to set values locally for a block like that, and if you need to refer to them elsewhere (as you appear to [here](https://github.com/emacs-berlin/general-close/blob/master/general-close-modes.el#L83)) then they should be declared as proper top-level `defvar`s with the full package prefix.

**Comment by andreas-roehler** [comment]
Am 25.07.2015 um 00:42 schrieb Steve Purcell:
>
> There's also some code which is creating and setting unprefixed 
> top-level variables,
>

Not really.

`done' is not a top-level variable, but let-bound by the top-level command.
Settings here should effect environment, can't introduce a local let.

> e.g. |(setq done (member (char-before) (list ?\t ?\n ?\ ?=)))| here 
> <https://github.com/emacs-berlin/general-close/blob/master/general-close-modes.el#L74>. 
> You should be using |(let ...)| to set values locally for a block like 
> that, and if you need to refer to them elsewhere (as you appear to 
> here 
> <https://github.com/emacs-berlin/general-close/blob/master/general-close-modes.el#L83>) 
> then they should be declared as proper top-level |defvar|s with the 
> full package prefix.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/milkypostman/melpa/pull/2958#issuecomment-124753179>.
>



The value is expected to be bound inside a let, it should not conflict 
with parellel runs of general-close.

Can't savely use defvar AFAIU.

**Comment by purcell** [comment]
> The value is expected to be bound inside a let, it should not conflict
> with parellel runs of general-close.

Eww, right, I didn't notice that it was a `let`-bound parameter implicitly passed from the other file.

**Comment by andreas-roehler** [comment]
Am 25.07.2015 um 08:55 schrieb Steve Purcell:
>
> Merged #2958 <https://github.com/milkypostman/melpa/pull/2958>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/milkypostman/melpa/pull/2958#event-365139752>.
>
Thanks a lot!

**Pull request merged**
