### PR TITLE
Add recipe for edit-at-point

### PR DESCRIPTION
**Pull request by enoson**
This package provides functions to edit(copy,cut...) things(word,symbol..) under cursor.

repo: https://github.com/enoson/edit-at-point.el

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. The `;; Author:` etc. metadata block should come before the `;;; Commentary:` section. Also, don't use the prefix `ep/*` -- as per the [elisp coding guidelines](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html), you should instead use `edit-at-point-*`.

**Comment by enoson** [comment]
Is prefix `eap-` ok? since `edit-at-point` is a little long..

**Comment by purcell** [comment]
Please, no. Following the conventions is better for everyone. Bytes are cheap, and readable names are important.

**Comment by enoson** [comment]
@purcell fixed

**Comment by purcell** [comment]
Looks good!

**Pull request merged**
