### PR TITLE
Add ghq recipe

### PR DESCRIPTION
**Pull request by rcoedo**
This package is an emacs interface for the [ghq](https://github.com/motemen/ghq) command. It uses `async-shell-command` to execute the actions. It also offers integration with helm. I made this small package to ease project navigation in emacs.

The package can be found [here](https://github.com/rcoedo/emacs-ghq)

### CODE REVIEW

**Comment by syohex** [comment]
What's different from [helm-ghq](https://github.com/masutaka/emacs-helm-ghq) ?

**Comment by rcoedo** [comment]
Even though I am giving a helm helper to list the project, I aim to implement most of ghq's features like fetching repositories with asynchronous shell commands.

**Comment by syohex** [comment]
> Even though I implement a helm helper to list the projects, I aim to implement other ghq's features like fetching repositories, which are completely unrelated to helm.

I see.

**Comment by purcell** [comment]
Thanks. In that case, `helm` should be a soft dependency, ie. installing `ghq` shouldn't automatically install `helm` too.

**Comment by rcoedo** [comment]
@purcell Makes sense, I removed the dependency.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
