### PR TITLE
Add recipe kroman

### PR DESCRIPTION
**Pull request by cheunghy**
Kroman is a package that romanize Korean hangul.

### CODE REVIEW

**Comment by purcell** [comment]
I don't see any elisp in that repo...

**Comment by syohex** [comment]
I guess the repository is https://github.com/cheunghy/kroman-el

**Comment by purcell** [comment]
Ah, right. In that case, quick feedback:

- Needs to declare a dependency on `(emacs "24")` because it declares `lexical-binding: t`
- `(setq debug-on-message t)` doesn't belong in there at all

**Comment by cheunghy** [comment]
Thanks.
I've fixed repo name in the recipe.
I removed ```lexical-binding: t```.
It should work for older emacs.

**Comment by purcell** [comment]
Thanks - added as a single commit in 07ff16d.

**Pull request closed without merging**
