### PR TITLE
remark-mode: Add missing remark.html file

### PR DESCRIPTION
**Pull request by torgeir**
Be specific about which files to include. This file is needed as it is the html skeleton for the slideshow remark-mode produces.

### CODE REVIEW

**Comment by torgeir** [comment]
Sorry for the multiple prs, I'm not that well wandered in melpa packages :)

**Comment by purcell** [comment]
Could you please amend this to `:files (:defaults "remark.html")`? It's a little more general because `:defaults` includes `"*.el"`, and therefore preferred.

**Comment by torgeir** [comment]
Indeed, done!

**Comment by torgeir** [comment]
Anything else missing?

**Comment by purcell** [comment]
Thanks for the reminder - this one fell through the cracks. :-)

**Comment by torgeir** [comment]
:thumbsup:

**Pull request merged**
