### PR TITLE
Added a new recipe for Org-sync.

### PR DESCRIPTION
**Pull request by arbox**
I'm trying to package this abandoned Org-mode package which I'll maintain for the community from now.
I have little knowledge in Elisp so please correct me during my first steps.

I think I have to change the namespace for all functions from `os-` to `org-sync-` and rename files appropriately.
Could you please provide me with other compulsory steps before the package could be taken to Melpa!

Thanks a logt in advance!

### CODE REVIEW

**Comment by purcell** [comment]
Great that you're picking up this code and moving it forward.

I'd definitely recommend the renaming you suggested. "os-" is much too generic.

It's not clear where `omd.el` came from, or how general it is. It should probably either be `org-sync-omd`, or event a separate package upon which `org-sync` would depend.

If you feel like cleaning up the code, you can get rid of `cl` and use the modern `cl-lib` instead -- just remember to declare a package dependency via a header in `org-sync.el` like this:

```
;; Package-Requires: ((cl-lib "0.5"))
```

I noticed that the `os-*.el` don't have `(provide ...)` forms at the end: you should make sure all `.el` files have one.

Hope that helps for now -- happy to look again when you've made a bit of progress.

-Steve

**Comment by arbox** [comment]
Thank you a lot, it's great help for me at the beginning!

**Comment by arbox** [comment]
@purcell could you please review the current state of the code, it seems like to be ready for the initial packaging.

**Comment by purcell** [comment]
Looks good - thanks! Sorry for the delay.

**Comment by arbox** [comment]
Thank you a lot!

**Pull request merged**
