### PR TITLE
Add recipe for erc-yt

### PR DESCRIPTION
**Pull request by yhvh**
This package adds title, description and clickable thumbnails when
youtube links are sent on irc.

https://github.com/yhvh/erc-yt

I am the maintainer.

Tested package builds properly with make recipes/erc-yt.

Tested pacakge installs properly in sandbox.

### CODE REVIEW

**Comment by purcell** [comment]
Great, thanks. Presumably the `(define-erc-module youtube ...)` form makes the module *available for use* rather than automatically enabling it? Asking because installed packages shouldn't auto-enable themselves, in the same way that the elisp bundled with Emacs isn't all enabled at start-up.

**Comment by yhvh** [comment]
Yes sir, you must still enable this module by doing M-x customize-option erc-modules RET and adding the 'youtube' module.

**Comment by purcell** [comment]
Great. Also: `M-x checkdoc` will help you fix up some of the non-standard docstring formatting. :-)

**Comment by yhvh** [comment]
Thanks, fixed in https://github.com/yhvh/erc-yt/commit/43e7d49325b17a3217a6ffb4a9daf75c5ff4e6f8

**Pull request merged**
