### PR TITLE
Add govc recipe

### PR DESCRIPTION
**Pull request by dougm**
Emacs interface to govc for managing VMware ESXi and vCenter

### CODE REVIEW

**Comment by purcell** [comment]
Hi! Since this refers to a github-hosted package, please use the `github` fetcher rather than `git` -- please see the examples in README, which also describes how to check the recipe is working.

And re. the code itself, I [submitted a few fixes upstream](https://github.com/vmware/govmomi/pull/435).

**Comment by purcell** [comment]
(You can amend the recipe commit and force-push it here to update the PR cleanly.)

**Comment by dougm** [comment]
Fixed, thanks @purcell

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
