### PR TITLE
Remove several packages that conflict with built-in packages

### PR DESCRIPTION
**Pull request by tarsius**
See the commits for the reasoning in each case. Drop the package *or* the commit as you see fit :-)

/cc @sigma @byplayer @mooz @jrockway

### CODE REVIEW

**Comment by milkypostman** [comment]
will let this one breath a bit before commiting but seems fine.

**Comment by jrockway** [comment]
I'm not really maintaining cperl-mode anymore, so I think it's fine to drop the package.

**Comment by byplayer** [comment]
Original author never answer me.
Please drop table.


Thank you.

2015-12-13 6:12 GMT+08:00 Jonas Bernoulli <notifications@github.com>:

**Comment by tarsius** [comment]
We've gotten an okay for `cperl-mode` and `table`. For `tabulated-list` and `shadow` we've gotten no reply, but it seems pretty clear to me that those have to be removed. Can we remove now?

**Comment by byplayer** [comment]
OK, thank you for your following up.

Regards,
Yukio Goto

**Comment by lurdan** [comment]
I've contacted the author of shadow.el (@mooz), and he acked to change its name soon.
So please wait a bit.

**Comment by tarsius** [comment]
@lurdan Great. Thanks!

**Comment by sigma** [comment]
that's fine with me (for tabulated-list). I guess nobody cares about emacs 23 anymore, and it's not like it'll be unavailable anymore (people can still find it on marmalade)

**Comment by milkypostman** [comment]
we waiting on @mooz then?

**Comment by tarsius** [comment]
> we waiting on @mooz then?

I've just rebased and removed the commit which removes `shadow`. So you can just merge this now.

The commit which removes `shadow` has to be recreated anyway, since it should also add the renamed package at the same time.

**Comment by tarsius** [comment]
It has been a while...
Do you want me to send a new pr which removes `shadow`.
We can still add the renamed package back later, iff @mooz gets around to the renaming.

**Pull request merged**
