### PR TITLE
[new] celery

### PR DESCRIPTION
**Pull request by ardumont**
Hello,

- Repository: https://github.com/ardumont/emacs-celery
- The package permits to extract some stats from celery command
- I'm the maintainer.
- Compiled with the emacs buffer and installed it -> ok

Cheers,

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Your `defgroup` is wrong: it specifies itself as its parent (ie. `:group 'celery)`. Specify one of the standard built-in groups instead. Looks good otherwise.

**Comment by ardumont** [comment]
@purcell As always, thanks for your feedback!

I'll fix the defgroup.

**Comment by ardumont** [comment]
Fixed.

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
