### PR TITLE
Added recipe for green phosphor color theme

### PR DESCRIPTION
**Pull request by aalpern**
A retro color theme that harkens back to the days of old-school monochrome monitors. If I still had any of my grade-school Apple ][e code, I would totally hack on it with this theme. 

https://github.com/aalpern/emacs-color-theme-green-phosphor

### CODE REVIEW

**Comment by purcell** [comment]
Same feedback as #2766 here. :-)

**Comment by purcell** [comment]
(Nice-looking theme, by the way!)

**Comment by aalpern** [comment]
Changes made on both - thanks!

**Comment by purcell** [comment]
Thanks - recipe added as a single commit in c6770f5.

**Pull request closed without merging**
