### PR TITLE
Add go-playground recipe

### PR DESCRIPTION
**Pull request by grafov**
Add new recipe with go-playground mode for Go language. Under GPLv3.

### CODE REVIEW

**Comment by milkypostman** [comment]
This looks good. Only thing that I saw was possibly that you don't need lexical binding?

@purcell are we still trying to sway people into avoiding lexical binding?

**Comment by purcell** [comment]
Yes, use `;; Package-Requires: ((emacs "24"))` explicitly if `lexical-binding` is required, otherwise I'd strongly suggest removing that declaration.

**Comment by grafov** [comment]
Thank for advice, I removed lexical-binding declaration from the source.

**Comment by purcell** [comment]
Thanks - merged!

**Pull request merged**
