### PR TITLE
Add Hydra

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by purcell** [comment]
This looks great!

I think [these functions](https://github.com/abo-abo/hydra/blob/master/hydra.el#L101-L127) should have a name prefix, though. And perhaps even put them in a separate `hydra-examples.el`.

**Comment by abo-abo** [comment]
OK, updated. I'm autoloading only `hydra-create`. Should I just autoload everything to avoid a require on the user-side? What's your opinion?

**Comment by purcell** [comment]
> I'm autoloading only hydra-create. Should I just autoload everything to avoid a require on the user-side? What's your opinion?

I think the way you have it now is the best. Merging now...

**Comment by Fanael** [comment]
[`cl-mapcar`](https://github.com/abo-abo/hydra/blob/a179f3157c378de073a96bd244499ca85988b327/hydra.el#L71) requires either the package to depend on either `cl-lib 0.5` or `emacs 24.3`.

**Comment by purcell** [comment]
Ah, good catch. Yes, @abo-abo, please `(require 'cl-lib)` and use `;; Package-Requires: ((cl-lib "0.5"))`.

**Comment by abo-abo** [comment]
OK, done.

**Pull request merged**
