### PR TITLE
Name change request: reveal-in-osx-finder

### PR DESCRIPTION
**Pull request by kaz-yos**
This is a package name change request (reveal-in-finder.el -> reveal-in-osx-finder.el). No functional changes were introduced.

A brief summary of what the package does.

If M-x reveal-in-osx-finder is invoked in a file-associated buffer, it will open the folder enclosing the file in the OS X Finder. It will also select the file the buffer is associated with within the folder.

If M-x reveal-in-osx-finder is invoked in a buffer not associated with a file, it will open the folder defined in the default-directory variable.  In a dired buffer, this should open the current folder in the OS X Finder.

Your association with the package (e.g., are you the maintainer? have you contributed? do you just like the package a lot?).

I am the author and the maintainer.

A direct link to the package repository.

The repository URL has been changed to reflect the new name.

NEW: https://github.com/kaz-yos/reveal-in-osx-finder
OLD:  https://github.com/kaz-yos/elisp

Relevant communications with the package maintainer (e.g., package.el compatibility changes that you have submitted).

I am the maintainer.

Test that the package builds properly via make recipes/<recipe>.
Using OS X 10.10.4 and emacs 24.5.1, it built properly as seen below..

$ make recipes/reveal-in-osx-finder
 • Building recipe reveal-in-osx-finder ...
/usr/local/opt/coreutils/libexec/gnubin/timeout -k 60 600 emacs --no-site-file --batch -l package-build.el --eval "(let ((package-build-stable nil) (package-build-write-melpa-badge-images t) (package-build-archive-dir (expand-file-name \"./packages\" pb/this-dir))) (package-build-archive 'reveal-in-osx-finder))"

;;; reveal-in-osx-finder

Fetcher: github
Source: kaz-yos/reveal-in-osx-finder

Updating /Users/kazuki/Documents/programming/emacs-lisp-repos/melpa/working/reveal-in-osx-finder/
Saving file /Users/kazuki/Documents/programming/emacs-lisp-repos/melpa/packages/reveal-in-osx-finder-20150802.1257.el...
Wrote /Users/kazuki/Documents/programming/emacs-lisp-repos/melpa/packages/reveal-in-osx-finder-20150802.1257.el
Wrote /Users/kazuki/Documents/programming/emacs-lisp-repos/melpa/packages/reveal-in-osx-finder-readme.txt
File: /Users/kazuki/Documents/programming/emacs-lisp-repos/melpa/packages/reveal-in-osx-finder-20150802.1257.entry
Contacting host: img.shields.io:80
Wrote /Users/kazuki/Documents/programming/emacs-lisp-repos/melpa/packages/reveal-in-osx-finder-badge.svg
Built in 0.393s, finished at Sun Aug  2 13:02:21 2015
 ✓ Wrote 8.0K -rw-r--r-- 1 kazuki staff 4.3K Aug  2 12:54 ./packages/reveal-in-osx-finder-20150802.1146.el
4.0K -rw-r--r-- 1 kazuki staff  196 Aug  2 12:54 ./packages/reveal-in-osx-finder-20150802.1146.entry
8.0K -rw-r--r-- 1 kazuki staff 4.3K Aug  2 13:02 ./packages/reveal-in-osx-finder-20150802.1257.el
4.0K -rw-r--r-- 1 kazuki staff  196 Aug  2 13:02 ./packages/reveal-in-osx-finder-20150802.1257.entry
4.0K -rw------- 1 kazuki staff  750 Aug  2 13:02 ./packages/reveal-in-osx-finder-badge.svg
4.0K -rw-r--r-- 1 kazuki staff 1017 Aug  2 13:02 ./packages/reveal-in-osx-finder-readme.txt 
 Sleeping for 0 ...
sleep 0

### CODE REVIEW

**Comment by milkypostman** [comment]
@kaz-yos is there anyway you can squash these into a single commit? If not I'll submit something when I get back to my computer.

**Comment by kaz-yos** [comment]
I'm not sure why all of these commits came up. The very last commit (d377f97) is all I need to submit. I'll try to rewrite these into a single commit.

**Comment by kaz-yos** [comment]
I think I messed up my local MELPA repo... Is it an option to drop my entire Github fork of MELPA, re-fork MELPA, and re-create a single commit corresponding to d377f97?

**Comment by milkypostman** [comment]
Don't worry about it. I'll make the change not biggy.

But you can do a hard reset to our version then force push yours up. Or
delete the fork and refork

**Comment by kaz-yos** [comment]
I've dropped my folk, and reforked. I can send another single-commit pull request if that's necessary. How should I handle this?

**Comment by milkypostman** [comment]
sorry for the delay. fixed now.

**Comment by kaz-yos** [comment]
Thank you so much!

**Pull request closed without merging**
