### PR TITLE
Add org-wunderlist recipe

### PR DESCRIPTION
**Pull request by myuhe**

### CODE REVIEW

**Comment by myuhe** [comment]
ping

**Comment by purcell** [comment]
Thanks, sorry -- I missed this because I had a busy weekend!

The symbol prefix here should really be `org-wunderlist-`, not `org-wlist-`, according to the [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html). I also think that prefix would be clearer. What do you think?

**Comment by myuhe** [comment]
Thank you for your response.
prefix `org-wunderlist` is too long. prefix should be shorter.
For instance `yasnippet` uses prefix `yas-` .  I think it is appropriate.

https://github.com/capitaomorte/yasnippet

**Comment by purcell** [comment]
`yas` is much too short, especially compared to `yasnippet`, so they're doing it wrong too, and setting a bad example. The conventions are there to help the community, and they only say that the prefix and filename should match: so `yas` would be okay if the package were called `yas.el`, and the `org-wlist-` prefix suggests that your package should be called `org-wlist.el`.

I'm not going to argue, but since you're the author of several packages I'd encourage you to set a good example by following the conventions. (A compromise would be to just use `org-wunderlist-` for the public symbols: there aren't many.)

Just let me know what you prefer.

**Comment by purcell** [comment]
Note that there are some really badly-behaved packages out there like `multiple-cursors` and its awful `mc-` and `mc/` prefixes, so I realise I'm being picky here. :-)

**Comment by myuhe** [comment]
Thanks.
I renamed wlist to wunderlist. https://github.com/myuhe/org-wunderlist.el/commit/58e3695c877b3edcde659b1724446670403ad486

check it.

**Comment by purcell** [comment]
Awesome - thanks for your patience. I really think the consistency is worth the longer identifiers.

**Pull request merged**
