### PR TITLE
update xml-rpc

### PR DESCRIPTION
**Pull request by hexmode**
Switching to github.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. There are 2 apparently unrelated commits here, right?

**Comment by hexmode** [comment]
Right.  I didn't know how to remove the magit-gerrit one from the pull request.

**Comment by purcell** [comment]
You'd need to do a bit of selective branching and rebasing. Let me just cherry-pick the xml-rpc one.

**Comment by purcell** [comment]
Applied as cf0d657. Thanks!

**Pull request closed without merging**
