### PR TITLE
Add recipe for helm-img

### PR DESCRIPTION
**Pull request by l3msh0**
helm-img is an library for making helm-sources which return images as candidates.

https://github.com/l3msh0/helm-img

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Sent you a fix in https://github.com/l3msh0/helm-img/pull/2.

**Comment by purcell** [comment]
Also, `:files ("*.el")` is redundant and should be removed from the recipe -- all `.el` files are included by default.

**Comment by purcell** [comment]
(Ideally, amend the recipe commit and force-push it here to cleanly update the PR.)

**Comment by l3msh0** [comment]
Thank you for reviewing.
Merged your PR and amended the recipe commit.

**Pull request merged**
