### PR TITLE
Apropospriate Theme recipe

### PR DESCRIPTION
**Pull request by waymondo**
a colorful, low-contrast, light & dark theme for emacs.

https://github.com/waymondo/apropospriate-theme

### CODE REVIEW

**Comment by purcell** [comment]
Same as #2633 -- please see comments there. :-)

**Comment by waymondo** [comment]
cool, thanks for the feedback. updated the repo and squashed the commits

**Comment by purcell** [comment]
Okay, cool, but you'll need the metadata to be in the `.el` file which matches the package name, ie. `apropospriate-theme.el`. I see you've put the guts of the theme into `apropospriate.el`, which makes sense, but then that leaves `apropospriate-theme` which could then get wrongly listed as a loadable theme. Why not get rid of that file, and instead just provide an `apropospriate-theme-pkg.el` containing a `(define-package ...)` form?

**Comment by purcell** [comment]
P.S. That word is extraordinarily hard to type. ;-)

**Comment by waymondo** [comment]
yes, it is quite an obnoxious name! wasn't familiar with `(define-package)`. is this correct?
https://github.com/waymondo/apropospriate-theme/commit/5e24947b66d967d2483d8fd2151d983a0cf76a71

**Comment by purcell** [comment]
> yes, it is quite an obnoxious name! 

It's really easy to say, and awful to type. I think that's an achievement!

> wasn't familiar with (define-package). is this correct?
> waymondo/apropospriate-theme@5e24947

Yes, looks good. Merging this now. Thanks for your patience.

**Comment by purcell** [comment]
> It's really easy to say, and awful to type.

I take that back. It's not easy to say *out loud*, only in my head.

**Comment by waymondo** [comment]
hahaha i :100:% agree.

**Pull request merged**
