### PR TITLE
Add cljr-helm.

### PR DESCRIPTION
**Pull request by philjackson**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

- Please remove `:files` from recipe. Amend commit and force-push, ideally.
- Needs to declare `Package-Requires` dependencies on `cljr` and `helm`
- Suggest you add an `;;;###autoload` for `cljr-helm`

**Comment by philjackson** [comment]
Hey, hopefully all done.

**Comment by purcell** [comment]
great, thanks

**Comment by philjackson** [comment]
Thank *you*.

**Pull request merged**
