### PR TITLE
Add projectile-sift

### PR DESCRIPTION
**Pull request by nlamirault**
Add projectile-sift and update recipe for sift.
Project homepage : https://github.com/nlamirault/sift.el

### CODE REVIEW

**Comment by purcell** [comment]
The first element of the recipe for `projectile-shift` says `sift`, rather than `projectile-shift`, which is why the build failed: you should be able to just amend that commit and force push it back here to fix the PR.

**Comment by bbatsov** [comment]
You should probably squash the first and the third commits together.

**Comment by milkypostman** [comment]
^^^ yes please

**Comment by nlamirault** [comment]
Done.

**Comment by milkypostman** [comment]
This looks like a bad rebase. I'll just merge the recipe.

**Pull request closed without merging**
