### PR TITLE
add aozora-view

### PR DESCRIPTION
**Pull request by ksato9700**
This is a view mode to show Aozora bunko text, a text-based ebook format.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please use `:defaults` instead of `"*.el"`. Also, does this code require `lexical-binding: t`? If so, please add `;; Package-Requires: ((emacs "24"))`. If not, I suggest removing the `lexical-binding` declaration.

**Comment by ksato9700** [comment]
Thank you, Steve. I fixed the receipt as you suggested. As for the lexical-binding, I would leave it to the original author to decide. A pull request was made kawabata/aozora-view#2, and I hope he will respond to it soon.

**Comment by purcell** [comment]
Thanks.

**Comment by ksato9700** [comment]
Thank you!

**Pull request merged**
