### PR TITLE
Add jst-mode

### PR DESCRIPTION
**Pull request by cheunghy**
`jst-mode` is an intelligent javaScript testing minor mode.
See [here](https://github.com/cheunghy/jst-mode) for more information.

### CODE REVIEW

**Comment by purcell** [comment]
Since this package provides a minor mode, and not a major mode, it should not normally have the `-mode` suffix. How about just calling this `jst.el`?

**Comment by cheunghy** [comment]
Does it mean the package has name "jst" in packages list, and when using, it's named "jst-mode"?

**Comment by purcell** [comment]
Both the filename and package name would be `jst`, and the file would `(provide 'jst)`.

**Comment by purcell** [comment]
And yes, the minor mode would still be called `jst-mode`.

**Comment by cheunghy** [comment]
Thanks, I renamed the file and README.

However, I want the github repo to remain "jst-mode", because "jst" is so short and doesn't seem like a emacs plugin, "jst.el" seems like old way of naming.

How to specify it in the recipe?

**Comment by purcell** [comment]
> Thanks, I renamed the file and README.
> 
> However, I want the github repo to remain "jst-mode", because "jst" is so short and doesn't seem like a emacs plugin, "jst.el" seems like old way of naming.
> 
> How to specify it in the recipe?

This should do the trick:

```
(jst :fetcher github :repo "cheunghy/jst-mode")
```

**Comment by cheunghy** [comment]
Updated the commit

**Comment by cheunghy** [comment]
I have a question. What to do if Package Requires header are too long, the dependency list?

And I don't want it to exceed 80 chars.

**Comment by purcell** [comment]
> I have a question. What to do if Package Requires header are too long, the dependency list?
> 
> And I don't want it to exceed 80 chars.

As far as I know, there's no way to wrap it, unfortunately.

**Comment by cheunghy** [comment]
Any other requirements?

**Comment by purcell** [comment]
Nope, looks good.

**Comment by cheunghy** [comment]
Thanks!

**Pull request merged**
