### PR TITLE
Update swiper recipe

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by purcell** [comment]
Wouldn't it be neater to just wrap the contents of `ivy-hydra.el` in an `(eval-after-load 'hydra ...)` form? Having that [auto-install magic](https://github.com/abo-abo/swiper/blob/master/ivy-hydra.el#L32) seems clunky.

**Comment by abo-abo** [comment]
Since `defhydra` is a macro, all instances of it need to be byte-compiled and reloaded.  Hence the auto-install magic. If you know a better way, I'd be glad to hear it, but `eval-after-load` won't work.

**Comment by abo-abo** [comment]
Maybe you have another suggestion for this code.
It's kind of out-of-place:

- Too small to be standalone.
- Too useful not to be easy-to-install.
- Can't have swiper depend on hydra, since a completion engine probably shouldn't depend on a key binding facility.
- Can't have hydra depend on swiper, and don't really want to bundle this code with hydra even without the dependency on swiper.

So I went with this approach: bind <kbd>C-o</kbd> to `hydra-ivy/body`.  On calling, self-install hydra and recompile+reload hydra-ivy.el.  If the user doesn't want an install, keep `hydra-ivy/body` as an entry point to self-install, and the user will have to remember not to press <kbd>C-o</kbd>.

I've seen a similar approach in projectile, where it simply issues an error with the github address of an optional package required.  But I had to do better, since there will be errors if hydra-ivy.el isn't re-compiled, and it may be hard to explain to users how to do that.

**Comment by purcell** [comment]
Yeah, I think it's a cool hack, but ultimately it feels like ivy-hydra is an optional add-on package.

I was thinking of this kind of thing:

```el
(require 'ivy)
(eval-after-load 'hydra
  '(defhydra hydra-ivy (:hint nil
                              :color pink)
     "
^^^^^^          ^Yes^     ^No^     ^Maybe^
^^^^^^^^^^^^^^---------------------------------------
^ ^ _k_ ^ ^     _f_ollow  _i_nsert _c_: calling %s(if ivy-calling \"on\" \"off\")
_h_ ^+^ _l_     _d_one    _o_ops   _m_: matcher %s(if (eq ivy--regex-function 'ivy--regex-fuzzy) \"fuzzy\" \"ivy\")
^ ^ _j_ ^ ^
"
     ;; arrows
     ("h" ivy-beginning-of-buffer)
     ("j" ivy-next-line)
     ("k" ivy-previous-line)
     ("l" ivy-end-of-buffer)
     ;; actions
     ("o" keyboard-escape-quit :exit t)
     ("i" nil)
     ("f" ivy-alt-done :exit nil)
     ("C-j" ivy-alt-done :exit nil)
     ("d" ivy-done :exit t)
     ("C-m" ivy-done :exit t)
     ("c" ivy-toggle-calling)
     ("m" ivy-toggle-fuzzy)))

(provide 'ivy-hydra)
```

**Comment by purcell** [comment]
Anyway, I'll leave that decision to you. :-)

**Comment by abo-abo** [comment]
> I was thinking of this kind of thing:

But doesn't this construct mean that `ivy-hydra.el` essentially won't be byte-compiled?  It will work, but there are >12 functions being defined within this single macro, mostly wrappers.  It would be a shame not to byte-compile the wrappers.

**Comment by purcell** [comment]
Probably, yes. But IMO the only reliable way to be sure your code will be cleanly byte-compiled is to require that the code it depends on must also be installed. I'm a bit wary of auto-self-recompiling magic, clever thought it is.

**Pull request merged**
