### PR TITLE
new package: helm-mu

### PR DESCRIPTION
**Pull request by stsquad**
Please merge this handy helm package from @tmalsburg.

### CODE REVIEW

**Comment by xuchunyang** [comment]
https://github.com/emacs-helm/helm-mu/issues/14

**Comment by stsquad** [comment]
@xuchunyang ah I should have checked if there had been another attempt. I did test the package for searching emails and contacts so I didn't realise this bug existed.

**Comment by tmalsburg** [comment]
Sorry for the inconvenience.  It's still not clear to me how I can reliably trigger the bug.  Initially I suspected that the problem was the absence of a headers-view but that does not (anymore?) seem to be the case.  When I forward a message opened via helm-mu, it either works or the text of the previously viewed message is quoted.  Perhaps the fix is easier than I originally thought.

**Comment by purcell** [comment]
Merged alternate PR.

**Pull request closed without merging**
