### PR TITLE
Add asilea

### PR DESCRIPTION
**Pull request by Fanael**
It's me doing silly things a text editor shouldn't be capable of again.

### CODE REVIEW

**Comment by purcell** [comment]
The package description line is blank. (Aside: remind me to make `flycheck-package` warn about that...)  Can you put a short desc in there please?

**Comment by Fanael** [comment]
Oops. Fixed.

**Comment by Fanael** [comment]
By the way, do you have an idea how to sort [this function's](https://github.com/Fanael/asilea/blob/921c588f14e010c90e0f7bf6b36436cae750a971/asilea.el#L226) tons of closures mess out?

**Comment by purcell** [comment]
Hehe. Well, the usual process would be to extract each closure into a separate function, and make all the arguments explicit.

**Comment by Fanael** [comment]
Functions with hundreds of arguments are exactly what I'm trying to avoid.

**Comment by purcell** [comment]
Then either separation of concerns or grouping of data into structs is the usual solution.

**Comment by Fanael** [comment]
> grouping of data into structs

And that's doing closures by hand.

I'll worry about it sometime else.

**Comment by purcell** [comment]
> I'll worry about it sometime else.

Often a good strategy.

**Pull request merged**
