### PR TITLE
Add forecast.el

### PR DESCRIPTION
**Pull request by cadadr**
Forecast.el prepares weather reports from Forecast.io data.

### CODE REVIEW

**Comment by purcell** [comment]
Looks good, thanks. I wonder if it might make sense to use `special-mode` as the parent mode rather than `fundamental-mode`?

**Comment by cadadr** [comment]
Thanks for the merge. I'll look into special-mode as soon as I have time.

**Comment by purcell** [comment]
> I'll look into special-mode as soon as I have time.

Yeah, it's basically for the things like `help-mode`: it gives you the `q` binding for free, and it's the standard parent mode in many cases dealing with temporary buffers unconnected to files.

**Comment by cadadr** [comment]
Then I'll have to switch to it ASAP. Thanks.

**Pull request merged**
