### PR TITLE
add farmhouse-theme

### PR DESCRIPTION
**Pull request by mattly**
New theme with light/dark variants.

### CODE REVIEW

**Comment by mattly** [comment]
I removed some files from my repository that caused the build to fail. Is there a way to get travis to re-build with the new files without having to change things here?

**Comment by purcell** [comment]
The Travis failure was unrelated: the build does not actually build new packages.

You'll need to add a `farmhouse-theme-pkg.el` package manifest file in this repo to provide the basic package metadata. Other than that, looks good.

**Comment by mattly** [comment]
OK, I added this based on some other installed themes. Looking at other themes' github repos, I didn't think it was needed in the repo itself.

**Comment by purcell** [comment]
If you have a package `x`, then you need to have either an `x.el` or an `x-pkg.el` in order to provide package metadata.

**Comment by purcell** [comment]
So if a theme repo contains only a `foo-theme.el`, and the package is to be called `foo-theme`, then that will be fine -- that's probably what you've seen elsewhere.

**Comment by mattly** [comment]
OK. The file is there now, btw.

**Comment by purcell** [comment]
Excellent, thanks.

**Pull request merged**
