### PR TITLE
Adding test-kitchen-mode

### PR DESCRIPTION
**Pull request by jjasghar**
I created test-kitchen-mode so I can run my
[test-kitchen](http://kitchen.ci) runs inside of Emacs. This is just an
MVP, but it does automate around somethings.

:metal:

Thanks!

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. A few issues here:

- There's no mode, so calling this `*-mode` isn't appropriate. The convention is to use the `-mode` only when defining a major mode.
- You're defining symbols like `locate-root-dir` and `chef-kitchen-destroy` which don't have the package-specific prefix `test-kitchen-` - see the [elisp conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html) here.
- Don't use `global-set-key`. Instead, define a global minor mode and put those bindings inside its map. The user can then toggle the mode and/or redefine the bindings as desired.
- You're missing a `(provide ...)` form

Hope that helps.

**Comment by jjasghar** [comment]
@purcell thanks for the followup. Should i update my .el with these changes and re-open a PR? Or should I just comment back here saying i'm ready for another review?

**Comment by purcell** [comment]
Since you'll probably be renaming the file (and hence package) to remove the `-mode` suffix, it's probably easier to just file a fresh PR once you're ready, but it's also fine with me if you'd like to just comment here for a follow-up review -- I can trivially commit a fresh recipe myself.

**Comment by milkypostman** [comment]
@jjasghar any updates?

**Comment by jjasghar** [comment]
I need to pick this back up. Thanks for the ping, i'll get some fixes/issues resolved asap.

**Comment by jjasghar** [comment]
Updated per: https://github.com/milkypostman/melpa/pull/3245 going to close this PR.

:metal:

**Pull request closed without merging**
