### PR TITLE
add recipe for clipmon

### PR DESCRIPTION
**Pull request by bburns**
Clipmon is a clipboard monitor - it watches the system clipboard for changes and pastes them into Emacs. It's useful when you're copying a lot of text from the web. 

https://github.com/bburns/clipmon

I'm the owner/maintainer - this is my first package so feedback is welcome.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks -- mostly looks good, and a useful idea.

Any time you have an "on" flag, and code which inspects and switches it, you probably want either a local or a global minor mode instead. Can I therefore suggest you introduce a `clipmon-mode` in place of some of the existing code?

**Comment by purcell** [comment]
Also: the `package-version` in the `defgroup` doesn't really serve any purpose. It won't match the resulting package version, so it's only really a source of potential confusion.

**Comment by bburns** [comment]
Okay, thanks for your suggestions - it's now a global minor mode, and I added a couple more tests. And thanks for Melpa -

**Comment by bburns** [comment]
Oh, I guess I wasn't supposed to click that button...

**Comment by purcell** [comment]
Great, merged - thanks!

**Pull request merged**
