### PR TITLE
Add build start information

### PR DESCRIPTION
**Pull request by Silex**
Following #3192.

This is not finished but is enough to start discussing it :)

I need to check wether `\d` is supported in sed (probably not), and then I need to add the extrapolations.

### CODE REVIEW

**Comment by purcell** [comment]
`[0-9]+` should always work, I guess.

**Comment by Silex** [comment]
@purcell: is `service/builder` the right file to add this info? The same logic seems duplicated in several other files.

**Comment by milkypostman** [comment]
Yeah I think it's fine where you have it. I want to rereview this when I'm on a laptop but I think it looks OK and we can probably merge it in.

**Comment by Silex** [comment]
A'ight, I'll summon you when it's all done.

**Comment by Silex** [comment]
@milkypostman, @purcell: okay, I think I'm done. I didn't test, do you have an easy way to test this?

**Comment by purcell** [comment]
One thing to beware of is that this will temporarily break the MELPA site because the newly-added info won't be available in the build status json until the first new build completes. So perhaps add a quick snippet in the JS to handle it. I'll probably tidy up the JS a bit afterwards anyway.

**Comment by Silex** [comment]
Oh, good catch. I'll do that.

**Comment by Silex** [comment]
Alright, the part to remove when `build-status.json` is correct is the `FIXME` if block

**Comment by purcell** [comment]
Hey, thanks - your work here was really helpful. In the end I've currently committed some more minimal changes based on yours. I don't yet handle remembering the duration between builds, but I'll probably do that in due course. The main difference between your code and mine is that I'm trying to keep the display of the information more compact on the page. I also had to update the MELPA Stable build script to make sure that keeps working. Guess we'll find out in a couple of hours what (if anything) I've broken. :-)

**Comment by milkypostman** [comment]
@Silex thank you so much for the help! i think you should see the fruits of your labor now on the site. I fixed some stupid things I had done on the server which made your change get delayed (require manual intervention) and future changes should resolve this issue.

**Comment by purcell** [comment]
Yep. I plan to handle calculating durations so that we can display not just "Current build started: 2 hours ago", but "Current build started: 2 hours ago (last took 130 minutes" or something similar.

**Comment by Silex** [comment]
:+1: 

Nice to see alternative implementation, I like the `update_json` idea. Glad the idea got through :)

**Comment by purcell** [comment]
It's really helpful to be able to see at a glance more information about the build. I'm a bit surprised that the build time is currently 4-5 hours, actually.

**Comment by milkypostman** [comment]
I am too. Will have to dig in further.

**Pull request closed without merging**
