### PR TITLE
Add recipe for dyalog-mode.

### PR DESCRIPTION
**Pull request by harsman**
Please consider adding dyalog-mode to MELPA.

Dyalog mode is a major mode for editing Dyalog APL (http://dyalog.com/) source code, it lives here: 

https://bitbucket.org/harsman/dyalog-mode

I am the author and maintainer.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback, some of which you can get in-buffer if you install & use `flycheck-package`:

- `lexical-binding` should be set on the first line. It's not guaranteed to work otherwise.
- If you need `lexical-binding`, you should declare a package dependency on `(emacs "24.1")`
- Don't define `setq-local` if it's not there. Define it with a prefix, ie. `dyalog-mode-setq-local`, as the [elisp manual's coding conventions section](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html) says. Or depend on emacs 24.3, which will always have it.
- Should you be autoloading an `auto-mode-alist` entry for `.apl`? Unless this is the only major mode for `.apl` source, you shouldn't make this unconditional by autoloading it.

**Comment by purcell** [comment]
Another thing: calling `eval-after-load` [inside a function](https://bitbucket.org/harsman/dyalog-mode/src/963599f4f8358939d1f70849931f594186631ee9/dyalog-mode.el?at=default#cl-1070) isn't what you want. that form should be at the top level.

**Comment by harsman** [comment]
Thanks for the free code review!

I fixed all of these, except adding a dependency on Emacs 24.3. I don't
really need lexical binding, but it provided a small but measurable
performance boost for some things, so it's still nice to have it enabled
when it's available.

**Comment by purcell** [comment]
Great, merging now.

**Pull request merged**
