### PR TITLE
add magit-popup recipe

### PR DESCRIPTION
**Pull request by tarsius**
/cc @Silex @mickeynp

### CODE REVIEW

**Comment by purcell** [comment]
Why the `next` branch? The regular `magit` recipe doesn't use that branch. Should it? MELPA would ideally track wherever development is taking place.

**Comment by tarsius** [comment]
Yes, that's what I *should* have done. It's not what I *have* done. I am tired of discussing it.

Once `2.1.0` is released that will be corrected and releases will start happening more frequently. The roadmap is here: https://github.com/magit/magit/issues/1645.

**Comment by tarsius** [comment]
I am releasing `magit-popup` from the `next` branch as a separate package, because it can be used outside of Magit. Magit from Melpa / the `master` branch, still uses `magit-key-mode` instead.

**Comment by Silex** [comment]
:+1:

**Comment by purcell** [comment]
> Yes, that's what I should have done. It's not what I have done. I am tired of discussing it.

Alright, alright, I trust your judgement. Just wanted to ask. ;-)

**Pull request merged**
