### PR TITLE
recipe to create rope-read-mode

### PR DESCRIPTION
**Pull request by marcowahl**
Acked-by: Marco Wahl <marcowahlsoft@gmail.com>

### CODE REVIEW

**Comment by marcowahl** [comment]
Thanks for your work!

Please consider to include the rope-read-mode package into melpa.

(Please note that this is my first pull request.  Hopefully I did not make too many errors.)

rope-read-mode reverses every other line in the visible part of a
buffer.  When every other line has been reversed reading is like
following a rope.

https://github.com/marcowahl/rope-read-mode.git

I'm the maintainer.

**Comment by purcell** [comment]
Looks good, thanks. Please can you remove the `:files` spec from the recipe? - the default is fine here, and therefore preferred. You can amend the commit and force-push it back here to update the PR cleanly.

And the last line of `rope-read-mode.el` is invalid: it needs to not have the extra `;; ` before the `;;; rope-read-mode.el`.

Finally, I'd suggest removing the `rope-read-version` variable. It's never really going to contain a useful or accurate value.

**Comment by marcowahl** [comment]
Hello Steve,

Thanks for your feedback and thanks in particular for your hints.

AFAICS the issues have been fixed now.

Best wishes for 2015!

**Comment by purcell** [comment]
Thanks - merged. Best wishes for 2015 to you too.

**Pull request merged**
