### PR TITLE
add big-fringe

### PR DESCRIPTION
**Pull request by EricCrosson**

### CODE REVIEW

**Comment by milkypostman** [comment]
I think this package needs a demo picture.

**Comment by EricCrosson** [comment]
Added! Thanks for the suggestion.

**Comment by purcell** [comment]
This looks very similar to `visual-fill-column`, and `writeroom-mode` (which uses `visual-fill-column`). If that's the case, we'd generally prefer to avoid adding packages which don't provide anything new.

**Comment by EricCrosson** [comment]
So it is similar. I hadn't seen writeroom mode before. 

Thanks for the tip gentlemen

**Pull request closed without merging**
