### PR TITLE
Add org-beautify recipe

### PR DESCRIPTION
**Pull request by jonnay**
Org-Beautify is a theme you load on top of your current theme to make org-mode buffers more typographically appealing. 

It is part of the Emagicians Starter Kit, but can be included separately, It is available here: 
https://github.com/jonnay/emagicians-starter-kit/tree/master/themes

I am the author. ;)

BTW, I'll take this opportunity to thank you very much for all your hard work on MELPA and Emacs!

### CODE REVIEW

**Comment by purcell** [comment]
Themes should be in files with the `-theme.el` suffix, so that they can be found by the theme system. Also, you really shouldn't specify font families in a theme -- it's simply not going to work well for the majority of users.

**Comment by jonnay** [comment]
Thanks for the comments, I'll update it and ping you when I'm ready.

**Comment by purcell** [comment]
Additionally, you're defining this theme by inspecting the value of the current faces, which means it will have a different effect depending on when it is loaded relative to other code. This is bad practice.

And you should be careful about redefining colors for `org-done` and `org-checkbox`, particularly since the background may end up being either light or dark.

I'm kinda thinking overall that this isn't going to be sufficiently widely useful to be worth packaging. It feels like (neatly-grouped) personal configuration to me.

**Comment by jonnay** [comment]
Well, that is kind of the point of this theme.  You load your main theme, and this one tweaks the typography and removes the angry fruit salad of org-mode headings.

I've re-named the file, fixed the font definition, and removed most of the color customizations, with exception to the checkbox, which sets both the background and foreground.   So if you want it here you are; if not, that's cool too!

Thanks for the pointers.

**Comment by milkypostman** [comment]
@jonnay there is a concept of having multiple themes selected in emacs. such things are crazy IMO but it's possible and some packages we have do go this route. Is this now what your package does?

I think now we need to rename the recipe so that it is org-beautify-theme

**Comment by jonnay** [comment]
That is exactly the point of the package,  A small, targeted theme to work with other themes. :)

**Comment by milkypostman** [comment]
happy birthday

**Comment by jonnay** [comment]
:+1:

**Pull request merged**
