### PR TITLE
Change nim-mode's repository

### PR DESCRIPTION
**Pull request by yuutayamada**
Hi, nim-mode's repository moved to [here](https://github.com/nim-lang/nim-mode) and now the package has several files, so I just changed the recipe accordingly.

### CODE REVIEW

**Comment by reactormonk** [comment]
Yes, can confirm.

**Comment by purcell** [comment]
Thanks. `*.el` is included in the default file patterns, so please can you just remove the `:files` spec altogether? Ideally you'd do that by amending the commit and force-pushing the branch here to keep the commit history clean.

**Comment by yuutayamada** [comment]
Thanks for kind reply. I pushed as you suggested.

**Comment by purcell** [comment]
Yay, great - thanks.

**Pull request merged**
