### PR TITLE
Add Recipe for link-hint

### PR DESCRIPTION
**Pull request by noctuid**
[`url-hint.el`](https://github.com/noctuid/url-hint.el) is a package written by myself that provides commands for pentadactyl/keysnail/etc. style url hinting to open and copy urls.

### CODE REVIEW

**Comment by purcell** [comment]
Nice, thanks.

**Comment by noctuid** [comment]
I've decided to change the package name (and repo name) since I'm going to expand the functionality to links that aren't urls, so please don't merge this until I've updated the recipe.

**Comment by noctuid** [comment]
Okay, I've fixed the name.

**Comment by purcell** [comment]
Thanks.

**Pull request merged**
