### PR TITLE
add Chinese wubi input method.

### PR DESCRIPTION
**Pull request by andyque**
This recipe mainly add the Chinese Wubi(五笔) Input Method.

Here is the package repository: https://github.com/andyque/chinese-wbim

I'm the maintainer of this package.

Thanks.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. A few small issues here:

- Please use `:defaults` in the recipe instead of `"*.el"`
- The first line of `chinese-wbim.el` is malformed: it should say `chinese-wbim.el ---`, not `chinese-wbim ---`
- `chinese-wbim.el` introduces symbols named `eim*`. They should be called `chinese-wbim*`, to follow the [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).

Hope that helps. :-)

**Comment by andyque** [comment]
@purcell  Thanks for your suggestions, I will change  all of this. After everything is done, I will ping you.

**Comment by andyque** [comment]
@purcell  Hi, please check. I have changed the name prefix and the recipe.
Thanks.

**Comment by purcell** [comment]
Super, thanks.

**Comment by andyque** [comment]
@purcell  Thanks

**Pull request merged**
