### PR TITLE
Add recipe for cycle-resize

### PR DESCRIPTION
**Pull request by pierre-lecocq**
Hello Steve,

Here is a recipe for the "cycle-resize" package.

Thanks in advance !

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Please can you rename all the `cr/` identifiers to `cycle-resize-`? That would be much more conventional. If you want to indicate that symbols are private, you can use `cycle-resize--`. Also, `first-element-at-the-end` needs the `cycle-resize-` prefix too, to avoid possible clashes with other code.

**Comment by pierre-lecocq** [comment]
Done via https://github.com/pierre-lecocq/cycle-resize/commit/357b2314a630fac01c21003f98d38642f9580987

Thanks Steve !

**Comment by purcell** [comment]
Thanks. I added the recipe in a slightly simpler format in 8806af6.

**Comment by pierre-lecocq** [comment]
Fine !
I'll use this format next time.
Thanks again for your work.

**Pull request closed without merging**
