### PR TITLE
Emacs' own autocorrect-mode

### PR DESCRIPTION
**Pull request by jbranso**
This package just abbrev-mode to store in some 130 abbreviations.  For example it expands "teh" into "the".

I'm not sure why web-mode got in the commit list, but that won't be a problem will it?  I just deleted a line.

### CODE REVIEW

**Comment by syohex** [comment]
You need to rebase and squash commits. And I recommend you to use topic branch instead of master branch to send PR.

See also
- https://yangsu.github.io/pull-request-tutorial/
- https://help.github.com/articles/using-pull-requests/
- https://www.atlassian.com/git/tutorials/rewriting-history
- https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by syohex** [comment]
And your package does not follow emacs packaging convention. Please see Emacs packaging documentation.

- https://www.gnu.org/software/emacs/manual/html_node/elisp/Packaging-Basics.html
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html

**Comment by purcell** [comment]
Have you looked at the built-in `flyspell` library? It provides the option `flyspell-auto-correct-word`, and I feel like that would be the idiomatic way to solve this problem.

**Comment by jbranso** [comment]
That's true.  I'll change the package to add an advice before/after the space is pressed.  If the last word was composed of only letters, then I'll call flyspell-auto-correct-word.  Thanks for the tip.

**Comment by purcell** [comment]
I assumed `flyspell-auto-correct-word`

**Comment by jbranso** [comment]
That doesn't seem to be the case.  The variable "flyspell-auto-correct-word" is not documented. bummer...  I've set it "flyspell-auto-correct-word" to t and to 1.  But both times "teh" did not autocorrect to "the".  But when I typed "teh" and called flyspell-auto-correct-word, "teh" changed to "the".  

So I could write my own package that adds an advice to call the function "flyspell-auto-correct-word" after the user presses the space key, but before emacs inserts the space char.  

Or I could just hack flyspell to do what I want to do, and try to push that change upstream.

**Pull request closed without merging**
