### PR TITLE
use master branch for flycheck-protobuf, not develop

### PR DESCRIPTION
**Pull request by edvorg**

### CODE REVIEW

**Comment by xuchunyang** [comment]
There is no develop branch in your repo (https://github.com/edvorg/flycheck-protobuf/branches).

**Comment by edvorg** [comment]
But now it is :)

**Comment by edvorg** [comment]
I found that, melpa uploads my packages from every branch which I push into.
So I need to specify manually which branch to use.

**Comment by purcell** [comment]
Please don't specify the branch. We always use the default branch for your repo, to avoid confusion, so that users who visit your github page will see the same code in the corresponding MELPA package. In the case of this repo, we will use `master`.

**Pull request closed without merging**
