### PR TITLE
Add recipe for pyfmt

### PR DESCRIPTION
**Pull request by aheaume**
Hi!

This package is a simple interface to [pyfmt](https://github.com/Psycojoker/pyfmt) for formatting Python buffers.

You can find the repo here: [aheaume/pyfmt.el](https://github.com/aheaume/pyfmt.el). I'm the maintainer.

Thanks & have a nice day.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You should add a `defgroup` to define the `pyfmt` customization group, and place that in the correct top-level group (`languages`, perhaps?).

Also, it would be better to call `error` when the command can't be found, so you can just say:

```el
(defun pyfmt ()
  "Format the current buffer according to the pyfmt tool."
  (interactive)
  (unless (executable-find pyfmt-command)
    (error "Can't find %s in the exec path" pyfmt-command))
  (call-process-region (point-min) (point-max) pyfmt-command t t nil (buffer-file-name)))
```

(Note that `error` and `message` both work like `format`.)

In fact, I think the check is redundant, because `call-process-region` should fail anyway if the command can't be found.

**Comment by aheaume** [comment]
Thanks for the review!

I'll add the group in `tools`. (`programming`/`tools`).

The test is necessary because I call `call-process-region` with the `DELETE` argument. It wipes the buffer before calling the command. When the executable can't be found, it just deletes the buffer contents and fails.

**Comment by purcell** [comment]
> The test is necessary because I call call-process-region with the DELETE argument. It wipes the buffer before calling the command. When the executable can't be found, it just deletes the buffer contents and fails.

Ah, makes sense. In that case, the code I posted in my previous comment would be a more idiomatic way to do things.

**Comment by aheaume** [comment]
Alright, idiomatic is better! I pushed the changes to [aheaume/pyfmt.el](https://github.com/aheaume/pyfmt.el).

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
