### PR TITLE
Add recipe for perl6-mode

### PR DESCRIPTION
**Pull request by hinrik**
Hi. This adds a recipe for a new major mode for Perl 6.

https://github.com/hinrik/perl6-mode

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Mostly looks good, but regular major modes shouldn't usually modify `magic-mode-alist`. Keep that for personal configuration if necessary.

**Comment by hinrik** [comment]
Yeah. It's hard to avoid because `.pm` and `.pl` are the conventional and most-used extensions for Perl 6 code, but Perl 5 already claims them in `auto-mode-alist`.

**Comment by purcell** [comment]
I see. Instead of a regexp in `magit-mode-alist`, you can provide a function which could check both the buffer's filename *and* its initial content. That might be safer, otherwise I can see things like "module" matching all sorts of content.

(P.S., is `usev6` valid? The current regexp matches it.)

**Comment by hinrik** [comment]
Ah, I didn't realize `magic-mode-alist` could take a matcher function. And no, `usev6` is not valid. :)

Both changes are now pushed: https://github.com/hinrik/perl6-mode/commit/3cf62b8383e3a3d77516c70725ad6d49bbf9d0d9

**Comment by purcell** [comment]
I think that making `perl6--content-pattern` breaks the autoload: the matcher function might run before `perl6-mode` has been loaded, meaning `perl6--content-pattern` wouldn't yet be defined. Perhaps just inline it for now.

**Comment by hinrik** [comment]
Good catch. I added the missing `;;;###autoload`s for the `defvar`/`defun` and verified that the `magic-mode` detection works with autoload now.

https://github.com/hinrik/perl6-mode/compare/0fc63c3...6a4269e

**Comment by purcell** [comment]
Great, recipe merged!

**Pull request merged**
