### PR TITLE
Create linedupe

### PR DESCRIPTION
**Pull request by sableloki**
adds my linedupe package to MELPA

### CODE REVIEW

**Comment by purcell** [comment]
Did you try building this locally? As the failed travis build notes:

```
Recipe 'linedupe' contains mismatched package name 'hipster-theme'
```

:-)

But in any case, this functionality is available in a more general, robust and documented form in other packages like `move-dup`, so I'm going to go ahead and decline to merge this. Thanks anyway, though!

-Steve

**Comment by sableloki** [comment]
That's odd but ok :)

**Comment by sableloki** [comment]
@purcell  I have fixed up the error and while i was at i had a look at the move-dup package and while i can see what you mean, my package is a more general, straight up, duplicate this line down

**Comment by purcell** [comment]
Yes, that's what `move-dup`'s `md/duplicate-down` function does.

**Comment by purcell** [comment]
Well, it's not quite the same: with an argument, `md/duplicate-down` makes N copies of the current line, so you'd need a combination of `whole-line-or-region` and `md/duplicate-down` to be able to duplicate N lines once.

But my main reservation here is that this package is a single function, written in an unidiomatic way, and without any of the standard boilerplate which would provide metadata like author, keywords etc.

Re. "unidiomatic", it's not necessary (or desirable IMO) to change the user's kill-ring during functions like this. It's also not appropriate to call `global-set-key` on behalf of the user: that's a matter of personal preference, and key bindings provided by packages belong inside keymaps for a local or global minor mode.

So while I'm delighted that you've taken the time to submit code to us, I just don't think this single function is worth adding as a package -- it's more of a personal helper function in its current form.

But... I think with a little work we could tidy this up, create a pair of `linedupe-up` and `linedupe-down` functions which do the right thing, and then get it added. First step would be to enable `auto-insert-mode` and create a fresh empty `linedup.el` -- this will help you get the boilerplate right.

**Comment by purcell** [comment]
The tricky thing is that if a region is selected, then the region should be duplicated, not the current line. This would need to be handled.

**Comment by sableloki** [comment]
yeah i know what you mean, like i said this a much more generic approach but ill look into handling the region specific copies as well

**Pull request closed without merging**
