### PR TITLE
Add evil-tutor recipe

### PR DESCRIPTION
**Pull request by syl20bnr**
Hi Steve,

This PR adds the recipe for [evil-tutor](https://github.com/syl20bnr/evil-tutor).

Cheers,
syl20bnr

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! The symbol prefixes here seem very random and unidiomatic to me: you've got `evil-tutor-`, `evil-tutor/` and `evil-tutor//`. Can I suggest just using `evil-tutor-`, and perhaps `evil-tutor--` for "private" symbols?

**Comment by syl20bnr** [comment]
Ooops, should be more conventional now :-)
Thank you!

**Comment by syl20bnr** [comment]
mmmmh make me think that I maybe need to declare the dependency on the file `tutor.txt`

**Comment by syl20bnr** [comment]
Ok file dependency added. Should be good to go now.

**Pull request merged**
