### PR TITLE
adapt recipes for magit v2.1.0

### PR DESCRIPTION
**Pull request by tarsius**
As you probably know I am going to release version 2.1.0 of Magit on the 1th of July.

This pull request should be merged *after* I have created and pushed the release tag.

The release steps are outlined in magit/magit#1645. Once I have pushed the tag, I will let you know here.

I currently intend to do that at approximately 13:00 Greenwich time, possibly later. @purcell @milkypostman is one of you going to be online around that time? If not, when do you expect to be online on that day?

----

* `git-commit-mode` has been renamed to `git-commit`. It is now part of the magit repository instead of the git-modes repository. But it is still distributed as a separate elpa package.
* `git-rebase-mode` has been renamed to `git-rebase`. It is now part of the magit repository instead of the git-modes repository. And it no longer is distributes as a separate elpa package. It now depends on some magit libraries and is distributed as part of the magit package.
* `org-magit` is not compatible with magit v2.1.0. Because it has a successor, `orgit`, I am removing it now.

----

Also please check that this pr is sound, preferable before the release date.

* Will all files appear at the top-level as I intend?
* The repository contains no `info` files only `texi`. Will the `info` files be created as needed?
* There is no `dir` file. I expect that won't cause any problems.
* There are no `PACKAGE-pkg.el` files, but all "main libraries" set the `Package-Requires` keyword in their headers. That should do it right?

Edit: Just remembered that I should be able to test this locally. I will do that tomorrow - but that shouldn't keep you from commenting :-)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this. I won't be online at that time: will be 1am for me locally, because I'm GMT+12.

**Comment by milkypostman** [comment]
i can do it sometime that day. I don't know when i will be online though. i
am -6 atm so maybe i can try to remember to login around then, but am on
vacation.

**Comment by purcell** [comment]
@tarsius If you could ping us here when the release is done, then it'll come into our inbox, and one of us will merge it ASAP.

**Comment by tarsius** [comment]
> GMT +12/-6

I figured you guys wouldn't be online at that time, but can't hurt to ask. Anyway I am going to release a few hours later - probably around GMT 17:00 or so. I hope that makes it more likely that @milkypostman will be around soon after I have tagged the release.

Anyway I have generated a dummy release using `make recipes/magit ...` and was able to successfully install that using `package.el`. So I expect things will go smoothly once this is merged.

**Comment by milkypostman** [comment]
Sounds good.

**Comment by tarsius** [comment]
It took me a little longer than I hoped but I have now pushed the new versions. Wiiiiiiiii

@milkypostman Please merge this asap. Thank a lot!

**Comment by milkypostman** [comment]
Good timing. Thanks.

**Comment by tarsius** [comment]
> Good timing.

That's the upside :-)

> Thanks. 

Thank you!

**Comment by zenspider** [comment]
Confusion! I can see magit in stable.melpa on the website, and I can see the entry for 2.1.0 in `~/.emacs.d/elpa/archives/melpa-stable/archive-contents`, but I don't see a 2.1.0 entry in the package listing itself. And the unstable listing is for `20150608`. Not sure how to resolve this so I can use the newer/stable version.

**Comment by tarsius** [comment]
It sometimes takes an hour or more until a new version appears on Melpa.

**Comment by zenspider** [comment]
@tarsius I get that, but I think you missed part of my confusion: I *see* the entry from stable in the archive-contents (ie, my local cache of package info), but it isn't listing in `package-list-packages`.

**Comment by purcell** [comment]
@zenspider package.el currently hides lower versions of installed packages from view IIRC. You probably have the snapshot version of magit installed.

**Pull request merged**
