### PR TITLE
add n4js recipes

### PR DESCRIPTION
**Pull request by tmtxt**
interactive shell for neo4j in emacs
link https://github.com/tmtxt/n4js.el
I'm the creator and maintainer

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Rather than using a snapshot version for the `cypher-mode` dependency, please just use "0".

**Comment by purcell** [comment]
(Looks good otherwise.)

**Comment by tmtxt** [comment]
updated ;)

**Comment by purcell** [comment]
Thanks.

**Comment by tmtxt** [comment]
great!

**Pull request merged**
