### PR TITLE
Add simple-mpc

### PR DESCRIPTION
**Pull request by jorenvo**
https://github.com/jorenvo/simple-mpc

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Couple of notes:

- I'm not sure where `call-mpc` is defined, but it should be named `simple-mpc-call-mpc` or similar, so that it has the package prefix in its name
- Using `(declare-function simple-mpc-mode ...)` in [simple-mpc-query.el](https://github.com/jorenvo/simple-mpc/blob/master/simple-mpc-query.el#L32), which you require from `simple-mpc.el` is a sign that you've divided up your functionality in an unnatural way: you should be able to just `require` files as needed.
- `define-derived-mode` should set the mode map for you, so you don't need `use-local-map`

**Comment by jorenvo** [comment]
Hi @purcell,

Thanks a lot for the review.

> * I'm not sure where call-mpc is defined, but it should be named simple-mpc-call-mpc or similar, so that it has the package prefix in its name

You're right, somehow didn't see that. [Fixed](https://github.com/jorenvo/simple-mpc/commit/958cd49ae5bb2c0b11cc3215ed07ec48d43b1651).

> * Using (declare-function simple-mpc-mode ...) in simple-mpc-query.el, which you require from simple-mpc.el is a sign that you've divided up your functionality in an unnatural way: you should be able to just require files as needed.

Yes, I was being a bit too lazy when I did that. [Fixed](https://github.com/jorenvo/simple-mpc/commit/10c381eae8c95cd54e428ae326867a9262d6cb6d).

> *  define-derived-mode should set the mode map for you, so you don't need use-local-map 

Didn't know about that, thanks for letting me know. [Fixed](https://github.com/jorenvo/simple-mpc/commit/17be8f600d641fdcb9889377c2dfd7adb36b841d).

**Comment by purcell** [comment]
Great, thanks! -- added without the redundant `:files` spec in 62d7623.

**Comment by jorenvo** [comment]
Great, thank you!

**Pull request closed without merging**
