### PR TITLE
Add recipe for helm-img-tiqav

### PR DESCRIPTION
**Pull request by l3msh0**
This pull request depends following one.
https://github.com/milkypostman/melpa/pull/3418

tiqav.com is joking image search engine for Japanese.
helm-img-tiqav execute search via tiqav.com and show results on helm buffer.

Project repository: https://github.com/l3msh0/helm-img-tiqav

### CODE REVIEW

**Comment by purcell** [comment]
Needs the same code fix as in https://github.com/l3msh0/helm-img/pull/2, and the same recipe fix as in #3418.

**Comment by purcell** [comment]
You should also escape the query param in `helm-img-tiqav-search` because otherwise queries containing `&`, `?` etc. will break the URL. There's a built-in elisp function for this, but I don't remember its name right now, sorry.

**Comment by l3msh0** [comment]
Thanks!
I fixed the recipe and fixed escaping the query parameter by `url-hexify-string`.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
