### PR TITLE
Add fix-word

### PR DESCRIPTION
**Pull request by mrkkrp**
Here is a package that allows to transform words intelligently:

https://github.com/mrkkrp/fix-word

Although I hacked my config for long time, it's the first thing I put for other people to use. Hope it's useful, let's see if it's cool enough for MELPA.

*P.S. If you know some package that can do similar things, please tell me, because I couldn't find it.*

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Looks handy, but the `fw/` prefix isn't correct. Just use `fix-word-` for public symbols and `fix-word--` for "internal" vars and functions, as per the [official elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).

**Comment by mrkkrp** [comment]
@purcell, done. Comments and prefixes should be OK now. I've used `fw-` prefix for public symbols and `fw--` for private ones. Also note that the whole idea of `xx/` prefix comes from packages like `multiple-cursors` that actually use this sort of thing. It's not a big deal, though, but as an opinion, I think `/` is good as visual delimiter between prefix part and actual name of symbol.

`fw-` is less unique than your proposed `fix-word-`, but I believe it should be ample, because with `fix-word-` prefix, one my function should be called `fix-word-fix-word` — er… that sounds a bit paranoid!

Thanks for your reply and corrections!

**Comment by purcell** [comment]
> Also note that the whole idea of xx/ prefix comes from packages like multiple-cursors that actually use this sort of thing.

Yes, and that's wrong too.

> It's not a big deal, though, but as an opinion, I think / is good as visual delimiter between prefix part and actual name of symbol.

Yes, I prefer Clojure's convention, which is where @magnars got it from. But it's not the elisp way, so I strongly encourage the latter.

> fw- is less unique than your proposed fix-word-, but I believe it should be ample, because with fix-word- prefix, one my function should be called fix-word-fix-word — er… that sounds a bit paranoid!

Bytes are cheap. `fix-word-` is fine for most symbols (the convention works for the entire Emacs standard library, for example), and that particular function can just be called `fix-word` -- problem solved!

**Comment by mrkkrp** [comment]
@purcell, you're right, if every one used two-character prefixes, there could be only 26 × 26 = 676 packages total. Not enough! Fixed. Now using `fix-word-` prefix!

**Comment by purcell** [comment]
Awesome! Thanks for your patience. Merging now!

**Pull request merged**
