### PR TITLE
Add recipe for indent-of-doom

### PR DESCRIPTION
**Pull request by AtticHacker**
Hello,

Indent of doom is a small libary which provides a new TAB functionality and an EDSL to customize your indentation rules for a specific major mode. This let's you add rules e.g. indent 1 tab if the previous line ends on "[", "{" or "(".

https://github.com/AtticHacker/indent-of-doom

If I need to change anything please let me know, thanks!

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. In the middle of a big house move, so will review in more detail soon, but at first glance the symbol naming here seems random: `--` means "private symbol", and `/` is unidiomatic. Just use `indent-of-doom-...` for public symbols, and `indent-of-doom--...` for private symbols, to follow the [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).

**Comment by AtticHacker** [comment]
Hey thanks for the reply. Is it fine to use abbreviations such as iod--foo instead of indent-of-doom--foo?
Also the '/' was meant for functions to be used in the end-users emacs configurations, but that can be changed to '-'.

**Comment by milkypostman** [comment]
yes, do not look a the melpa code either, we use `/` :)

i think it's fine if you abbreviate for all the functions actually. Probably the biggest thing is to be consistent.

sorry for the delayed response. @purcell is apparently moving and I don't normally get on and comment on package stuff.

**Comment by AtticHacker** [comment]
No worries I'm not in a rush :)
In that case I'll abbreviate all the functions, thanks!

**Comment by purcell** [comment]
No, please use `indent-of-doom--`, as per the guidelines. Bytes are cheap. We should change the `/` prefixes and abbreviations in `package-build.el` because it sets a bad example. Bytes are cheap, and coding conventions are important in a community like this. (The way to get shorter symbols is to choose shorter package names, e.g. `doomindent`.)

**Comment by AtticHacker** [comment]
Hey, renamed the package to Indy. There don't seem to be any other packages with that name.

**Comment by purcell** [comment]
Awesome, but the `--` prefixes should be for private symbols only, not the `defcustom`s etc.

**Comment by purcell** [comment]
You won't need to autoload the various non-interactive functions either, I think.

**Comment by AtticHacker** [comment]
Thanks for the review, I removed the autoload for non interactive functions and removed the -- prefix for defcustoms.

**Comment by purcell** [comment]
Thanks - merged! :-)

**Pull request merged**
