### PR TITLE
Add Malabarba's missing packages

### PR DESCRIPTION
**Pull request by tarsius**
See https://github.com/milkypostman/melpa/issues/3383#issuecomment-164409053.

### CODE REVIEW

**Comment by vyp** [comment]
@tarsius the `lisp-assistant` name should be `lisa`.

**Comment by tarsius** [comment]
@vyp Thanks for the notice. Already fixed.

**Comment by Malabarba** [comment]
Thanks for the effort, but I don't want any of these to be merged. Some of these are not proper packages, they're just scripts. Others are packages that are not ready yet (and aren't properly formatted). 

The only repo there that is a proper package is the bug hunter, and there's no reason to add it to Melpa. It's already on Gelpa and it has no need for snapshot releases.

**Comment by Malabarba** [comment]
Minor correction: spinner is also a proper package, but everything I said about the bug hunter applies to it too.

**Comment by tarsius** [comment]
Alright. I'll close this then and add only `bug-hunter` and `spinner` to the Emacsmirror (allowing me and others to install them as submodules). Thanks for the information.

**Pull request closed without merging**
