### PR TITLE
Add recipe for the super-save package

### PR DESCRIPTION
**Pull request by bbatsov**
A small package, containing Prelude's save-on-focus-lost logic.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Couple of quick fixes are in order before merging, I think.

- `provide` form is missing
- The docstring `"Save the current buffer if `prelude-auto-save' is not nil."` needs updating. ;-)

Separately, I wonder if the various `defadvice` are needed when `focus-out-hook` is available?

**Comment by bbatsov** [comment]
Ops, I'll address those right away. 

> Separately, I wonder if the various defadvice are needed when focus-out-hook is available?

Sure they are - it's triggered only if the frame itself loses focus (and is not available in older Emacsen).

**Comment by bbatsov** [comment]
Done.

**Comment by purcell** [comment]
> > Separately, I wonder if the various defadvice are needed when focus-out-hook is available?
> 
> Sure they are - it's triggered only if the frame itself loses focus (and is not available in older Emacsen).

Ah, I was thinking `focus-out-hook` was per window, not frame. The former would be more useful, and then you wouldn't need any `defadvice` at all, which was what I was referring to.

**Comment by vyp** [comment]
@purcell Yes that would be pretty useful. Off topic, but I've been looking for some sort of window switch hook, do you know of any potential others that exist?

**Comment by purcell** [comment]
@vyp Nope, sorry.

**Comment by vyp** [comment]
Okay no worries. :+1:

**Pull request merged**
