### PR TITLE
Add recipe for smart-region

### PR DESCRIPTION
**Pull request by uk-ar**
Smart region guess what you want to select by one command.
If you call this command multiple times at the same position, it expands selected region (it calls ```er/expand-region```).
Else, if you move from the mark and call this command, it select the region rectangular (it call ```rectangle-mark-mode```).
Else, if you move from the mark and call this command at same column as mark, it add cursor to each line (it call ```mc/edit-lines```).
See README under the GitHub project home for further details.

https://github.com/uk-ar/smart-region

I'm the maintainer of this package.

### CODE REVIEW

**Comment by purcell** [comment]
Hi! Several issues with this:

- You should depend on the stable versions of packages, not the snapshot versions: check on stable.melpa.org
- You need to depend on (and require) `(cl-lib "0.5")` 
- You're defining (or redefining?) `er/mark-outside-quotes` and `er/mark-outside-pairs`, which belong in `expand-region`. I don't understand why they're being defined in this package.
- `rectangle-mark-mode` is a recent Emacs addition, I believe, so you would have to declare a dependency on the Emacs version which introduced it.
- It's not clear from the description line or comments what this does
- You can use `memq` instead of `(or (eq ...) (eq ...))`

Overall this package feels like personal configuration rather than widely usable code.

**Comment by uk-ar** [comment]
Hi! Thank you for your polite response :smile: 
I fixed issues for now. 

> - You should depend on the stable versions of packages, not the snapshot versions: check on stable.melpa.org
I modified the [Package-Requires: section](https://github.com/uk-ar/smart-region/blob/master/smart-region.el#L28) to use stable versions.
> - You need to depend on (and require) (cl-lib "0.5")
I Added the cl-lib to  [Package-Requires: section](https://github.com/uk-ar/smart-region/blob/master/smart-region.el#L28) and [require](https://github.com/uk-ar/smart-region/blob/master/smart-region.el#L45)
> - You're defining (or redefining?) er/mark-outside-quotes and er/mark-outside-pairs, which belong in expand-region. I don't understand why they're being defined in this package.
I modified ```er/mark-outside-pairs``` and ```er/mark-outside-quotes``` to use from smart-region. And I am pulling [request for this](https://github.com/magnars/expand-region.el/pull/162).
> - rectangle-mark-mode is a recent Emacs addition, I believe, so you would have to declare a dependency on the Emacs version which introduced it.
I declared Emacs version in [Compatibility: section](https://github.com/uk-ar/smart-region/blob/master/smart-region.el#L32)
> - It's not clear from the description line or comments what this does
I added the description to [Commentary: section](https://github.com/uk-ar/smart-region/blob/master/smart-region.el#L34-L41) and [function comment](https://github.com/uk-ar/smart-region/blob/master/smart-region.el#L87-L93).
> - You can use memq instead of (or (eq ...) (eq ...))
I changed [dispatch routine](https://github.com/uk-ar/smart-region/blob/master/smart-region.el#L99).
> Overall this package feels like personal configuration rather than widely usable code.
In the past, there was the popular Emacs Lisp named [sense-region](https://gist.github.com/tnoda/1776988). It has the feature of ```rectangle-mark-mode``` and ```er/expand-region``` in one command. But now, sense-region is not maintained. 
Smart-region emulate sense-region behavior. So I think it is useful for sense-region users to migrate.

**Comment by uk-ar** [comment]
>> - You're defining (or redefining?) er/mark-outside-quotes and er/mark-outside-pairs, which belong in expand-region. I don't understand why they're being defined in this package.
>I modified ```er/mark-outside-pairs``` and ```er/mark-outside-quotes``` to use from smart-region. And I am pulling [request for this](https://github.com/magnars/expand-region.el/pull/162).

The PR was rejected ...
So I removed those function from code.

**Comment by purcell** [comment]
Thanks. Sorry for the delay. I sent you a few fixes in https://github.com/uk-ar/smart-region/pull/1, then we're ready to merge.

**Comment by moonlite** [comment]
What happened with this? I'm quite interested in trying this out. :)

**Comment by uk-ar** [comment]
Thank you merging ,@purcell :smile:

**Pull request merged**
