### PR TITLE
add emacs-surround

### PR DESCRIPTION
**Pull request by ganmacs**
This package is inspired by [vim-surroun](https://github.com/tpope/vim-surround).

### CODE REVIEW

**Comment by milkypostman** [comment]
I think there is already a package that does this called "surround". Is
this package different?

**Comment by purcell** [comment]
Also, `emacs` in the file and package name is redundant, and would need to be removed. People are only going to encounter this code if they are already using Emacs.

**Comment by ganmacs** [comment]
Sorry, I don't know "surround". so close this PR.

**Comment by Silex** [comment]
Well, I think your `surround` is different than the `evil-surround` recipe. Yours is "emacs only" while the other depends on evil.

**Comment by milkypostman** [comment]
Don't think that's true Philippe. Evil is not listed as a dependency
intentionally.

**Comment by Silex** [comment]
Well, https://github.com/ganmacs/emacs-surround/blob/master/emacs-surround.el is nothing like https://github.com/timcharper/evil-surround/blob/master/evil-surround.el

Except if I'm missing something, the former really doesn't depends on evil at all.

**Comment by milkypostman** [comment]
why do you think they are not similar? they do essentially the same things right? but I have a couple comments anyways,

* the command `emacs-surround` requires a second keystroke to do anything useful. it should really just provide functions and the instructions should provide information about setting up keybindings.
* If you want you can provide a function like `surround-setup-keybindings` that users can use to use the default set of bindings if they want.
* there is a package called [hydra](http://melpa.org/#/hydra) that you could use for the keybindings rather than creating your own. 
* I think the `interactive` command already has support for what you are doing with `char-to-string` so you should use that functionality. According to the [manual](http://www.gnu.org/software/emacs/manual/html_node/elisp/Interactive-Codes.html#Interactive-Codes) the `c` code should do what you are doing?

**Comment by Silex** [comment]
I think you are missunderstanding what I'm saying. They are similar, and yes the implementation of `emacs-surround` is discutable... all I'm saying is that `emacs-surround` is different because it does not depend on `evil`. For people who flat out refuse to use `evil`, this package might be interesting is all I'm saying.

Myself I tend to use `sp-rewrap-sexp` from `smartparens` for these kind of tasks.

**Pull request closed without merging**
