### PR TITLE
Add recipe for telephone-line

### PR DESCRIPTION
**Pull request by dbordak**
- Summary: A new implementation of Powerline
- Repository: https://github.com/dbordak/telephone-line
- Association: Author/Maintainer

### CODE REVIEW

**Comment by mrkkrp** [comment]
@dbordak, This is pretty cool, something to try out! :+1:

**Comment by purcell** [comment]
`*.el` is in the default `:files` spec, so please amend the commit to remove the `:files` setting and force-push it back here.

Other feedback:

- Put your face definitions are going to cause problems. e.g. imagine if I have set the `mode-line-inactive-face` to have a `:foreground` of `gray11`: what will `(:background "grey11" :inherit mode-line-inactive)` look like? :-)
- You'll need to declare a dependency on Emacs 24.3 because you're using `setq-default`
- Don't refer to `window-system` at load-time. I can load this file in an Emacs daemon (where `window-system` is false), and then enable `telephone-line` in a GUI Emacs frame (where `window-system` is true). So only inspect `window-system` at "runtime".
- Whenever you have pairs of `enable`/`disable` functions, you probably want to have a `minor-mode` instead.

Hope that helps. :)

**Comment by dbordak** [comment]
Alright, fixed the recipe. I have a couple questions about the other things

- Faces: While I'm at this, would it be appropriate to have a parent face that sets properties but is never used itself? I want to make a default hierarchy so that customizing it is easier. This is a bit irrelevant, but you seem to know a lot about standards :P
- window-system: So that means I have to remove it from all my defcustoms and from defseparator?
- enable/disable: Yeah, I was really unsure about this. I know in general that's what a minor mode is for, but I was looking at smart-mode-line (and, well, powerline) for reference, and neither are minor modes -- I figured there was some reason for this.

**Comment by purcell** [comment]
> Faces: While I'm at this, would it be appropriate to have a parent face that sets properties but is never used itself? I want to make a default hierarchy so that customizing it is easier. This is a bit irrelevant, but you seem to know a lot about standards :P

Yes, that would make sense.

> window-system: So that means I have to remove it from all my defcustoms?

Yes, I'd suggest so, because referring to `window-system` at load time is always going to be potentially unreliable. It can be different from frame to frame, so it shouldn't be used to make decisions which may affect several frames.

> enable/disable: Yeah, I was really unsure about this. I know in general that's what a minor mode is for, but I was looking at smart-mode-line (and, well, powerline) for reference, and neither are minor modes -- I figured there was some reason for this.

Not necessarily. I'd say that in this case, a global minor mode would be quite appropriate.

**Comment by dbordak** [comment]
I've finished adding all the changes. Thanks for all the help!

**Comment by purcell** [comment]
:+1:

**Pull request merged**
