### PR TITLE
add recipe for meacupla-theme

### PR DESCRIPTION
**Pull request by jtecca**
A deftheme with a light background and lots of blue and grey color highlights.

The repo link is: https://gitlab.com/jtecca/meacupla-theme

Don't have a screenshot yet, but will insert into the repo when I have the time.

### CODE REVIEW

**Comment by purcell** [comment]
Doesn't build, and can't see the repo, sorry -- is it private?

**Comment by jtecca** [comment]
Yes, it was private -- sorry!  I thought I switched it off of private but must have forgotten before the PR.  Please try again at your convenience.

**Comment by purcell** [comment]
Great, thanks. All the package metadata in `meacupla-definitions.el` needs to go in `meacupla-theme.el`, because that's where MELPA will look for it. Looks good otherwise.

Funny to see how the basic structure of functions and macros has made its way from the code of my `sanityinc-solarized` and `sanityinc-tomorrow` themes!

**Comment by jtecca** [comment]
I moved the metadata to `meacupla-theme.el`, but when I'm testing installing the package in a sandbox, I'm getting overflow errors (lisp-max-eval-depth) when I'm trying to install it.  I'm going to re-read the packaging info and loading mechanisms to make sure that everything is set up correctly.  Sorry for the noise.  I'll reply again when I think it is fully ready to go.

**Comment by purcell** [comment]
Yep, took a quick look again, but it's not immediately obvious to me what might be going wrong, sorry.

**Comment by jtecca** [comment]
This should be fixed upstream now.  Life got in the way and I wasn't able to refactor everything until recently.  I condensed the theme down into one file, moved the package metadata into the single .el file.  The overflow errors were apparently because I had too many face forms in single list -- if I broke all of the face forms into multiple lists (3 is what I currently have) then Emacs didn't mind at all.

I don't think I need to change the melpa recipe with my latest refactorings, but let me know and I will create a new PR.  Thanks!

**Comment by purcell** [comment]
Looks great now -- merged! Thanks for circling back round to this.

**Pull request merged**
