### PR TITLE
Add recipe for shader-mode

### PR DESCRIPTION
**Pull request by midnightSuyama**
Shader mode is Unity shader editing mode for GNU Emacs.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You'll need to add `;; Package-Requires: ((emacs "24"))` because you're using `prog-mode`. Looks good otherwise.

**Comment by midnightSuyama** [comment]
Thanks. Added `Package-Requires`.

**Comment by purcell** [comment]
Pending https://github.com/midnightSuyama/shader-mode/pull/1

**Comment by midnightSuyama** [comment]
Grateful! Merged.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
