### PR TITLE
Add recipe for psc-ide emacs integration

### PR DESCRIPTION
**Pull request by rexim**
Recipe for Emacs integration with [psc-ide](https://github.com/kRITZCREEK/psc-ide)

### CODE REVIEW

**Comment by rexim** [comment]
cc @epost, @kRITZCREEK

**Comment by purcell** [comment]
The recipe and package name here are not valid: they should match the .el file name, ie. `psc-ide`, not `psc-ide-emacs`.

Re. `psc-ide.el`:
- you should add a short `Commentary` section in the header so that the user will have some information about how to use the package
- don't put `)` on trailing lines - see the [standard elisp conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html), which are there to benefit the whole community

re. `psc-ide-protocol.el`:
- All the symbols must have a common package-specific prefix, e.g. `psc-ide-` -- defining very generic-looking symbols like `unwrap-result` and `filter-exact` is a big no-no. :-)

And for all the .el files, the `provide` form should be at the bottom of the file, not the top.

Hope that helps!

**Comment by rexim** [comment]
@purcell thank you very much for your review! I'll try to fix all of these. :)

**Comment by rexim** [comment]
@purcell all the remarks are fixed. Please take a look when you get a chance!

**Comment by epost** [comment]
Thanks @rexim and @purcell!

**Comment by purcell** [comment]
Nice work, thanks.

I'd suggest that you make sure each file will byte-compile in isolation: I suspect that https://github.com/epost/psc-ide-emacs/blob/master/psc-ide-backported.el would need a `(require 'cl-lib)` at the top to avoid warnings, for example. `flycheck` should tell you some of this stuff while you're working on the code, btw.

**Comment by rexim** [comment]
@purcell thank you sir! Really appreciate your help! I'll check the isolated compilation of the files.

P.S. didn't know about flycheck, thanks! I certanly have to add this to my toolbox. :)

**Comment by purcell** [comment]
There's also my `flycheck-package`, for when you're working on elisp packages. :-)

**Pull request merged**
