### PR TITLE
Adding test-kitchen

### PR DESCRIPTION
**Pull request by jjasghar**
- Adding the test-kitchen for running test-kitchen inside emacs

### CODE REVIEW

**Comment by purcell** [comment]
Don't call this `test-kitchen-el` -- it's already in Emacs, so it's obviously elisp! Just use `test-kitchen.el` as the filename, `test-kitchen` as the feature and module name, and then everything will match the `test-kitchen-*` prefix you've (correctly) used for all the symbols in the code.

You can amend the recipe commit accordingly and force-push it when done to update the PR in place.

**Comment by purcell** [comment]
Also: the `Package-Requires:` header in the file is syntactically invalid, so you should either remove it, or use `()` as its empty value.

**Comment by jjasghar** [comment]
I think it's ready to go! :metal:

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
