### PR TITLE
ncl-mode: change :files property.

### PR DESCRIPTION
**Pull request by yyr**

### CODE REVIEW

**Comment by purcell** [comment]
Great, thanks -- this is neater.

**Comment by yyr** [comment]
It seems MELPA doesn't keep symlink as it is. I have a symlink in dict folder. when I install from mepla the link comes as a empty file instead of link. Is it a problem with MELPA or package.el.

**Comment by milkypostman** [comment]
It's going to copy the file not copy the symlinked. Likely our server
doesn't have the dictionary file. Many systems are different anyhow. I
don't think a symlinked is a good idea.

**Comment by purcell** [comment]
Windows systems don't support symlinks, so you can't use them in Emacs packages anyway.

**Comment by yyr** [comment]
The file was already auto generated, and I didn't want keep two copies. so made a symlink. 
Anyhow, will look into auto-complete code to see what can be done.

Thanks for the inputs.

**Comment by Fanael** [comment]
> Windows systems don't support symlinks

They do since Vista.

**Pull request merged**
