### PR TITLE
Initial recipes for axiom-environment and ob-axiom.

### PR DESCRIPTION
**Pull request by pdo**
These packages provide modes to work with the Axiom, OpenAxiom and FriCAS computer algebra systems.  I am the author.

Thanks,
Paul Onions

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! The README and LICENCE files are not to be included in the installable packages. Bundled documentation may however be provided in `.info` format, so that it is browsable through Emacs. Otherwise, looks great, so perhaps you could just amend the recipe commit and force-push it back here to update the PR?

**Comment by pdo** [comment]
Hi Purcell,

I've simply removed the README and LICENCE files from the recipe for now.  I will work on the info documentation when I have some more time.

Regards,
Paul

**Comment by purcell** [comment]
Looks good, thanks. No hurry on the `.info` -- just wanted to let you know what we support, so that you can choose whether or not to pursue that.

**Comment by pdo** [comment]
Okay, thanks Steve.  Apologies for calling you Purcell previously!

Paul

**Comment by purcell** [comment]
No problem - my last name is an odd choice for a github name.

**Pull request merged**
