### PR TITLE
Add lodgeit package for lodgeit pastebin support.

### PR DESCRIPTION
**Pull request by ionrock**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please amend the recipe to remove the `:files` spec -- it's unnecessary here. You can force-push the amended commit back here to keep the history clean.

Re. the code itself, looks good! I'd suggest adding a `;;;###autoload` comment on the line before `(defun lodgeit-paste ()` so that users will be able to use the command without having to explicitly `require` the library first.

**Comment by purcell** [comment]
Further feedback:

- You can make things more idiomatic by giving `lodgeit-paste` `start` and `end` parameters, and using `(interactive "r")` -- Emacs will then pass the extents of the selection directly to the command when called. (You can use `(unless (use-region-p) (error "No region selected"))` to handle the no-selection case.)
- There's a built-in `split-string` function, so you don't need `s` here.

**Comment by purcell** [comment]
The mode -> language logic will be unreliable in many cases, e.g. `js2-mode`, `nxhtml-mode`, `tuareg-mode` (ocaml). Might want to provide a customisable `alist` to map those things, and fall back to the current logic if there's no explicit entry there.

**Comment by ionrock** [comment]
Thanks so much for the feedback @purcell! I'll be updating the recipe pull request. Also, regarding the language logic, I had planned on doing just that but I haven't had a chance just yet. Thanks again!

**Comment by ionrock** [comment]
Bump!

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
