### PR TITLE
add recipe meta-presenter

### PR DESCRIPTION
**Pull request by myTerminal**
This package can be used as a simple presentation tool. It enables to start a slide-show from any buffer and move to the next or previous slide. It differs from the other presentation tools in the way that is allows the user to maintain slides as separate markdown files with simple numbering, hence no configuration is required. A session progress-bar is also shown at the top of the window while presenting.
Slide transition animations have also been implemented, though they are disabled by default as they are not so efficient at the moment.

The package repository can be found at [https://github.com/myTerminal/meta-presenter](https://github.com/myTerminal/meta-presenter).

I am the creator and maintainer of this package.

### CODE REVIEW

**Comment by purcell** [comment]
If this is compatible only with Emacs 24, you'll need to declare that with a `Package-Requires` header.

Also, don't modify global keybindings on behalf of the user: instead, provide a local minor mode which is enabled in the slide buffers. The minor mode keymap can have keybindings to move forwards and backwards (not function keys, though: see the [key binding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html)). Users can easily customize the bindings to function keys if they like.

**Comment by myTerminal** [comment]
Thanks, I'll handle that soon...

**Comment by myTerminal** [comment]
Emacs 24 is not the requirement here, I removed that mention. I have also created a minor mode with local key-bindings to move forwards and backwards. Could you please review?

**Comment by purcell** [comment]
Looks great!

**Comment by myTerminal** [comment]
Thank you so much @purcell, for all your help.

**Pull request merged**
