### PR TITLE
add ido-occur recipe

### PR DESCRIPTION
**Pull request by danil**
`ido-occur` search lines in current buffer like `occur` but interactively with `ido`
https://github.com/danil/ido-occur
I'm tested package build locally

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

- To strip properties, just use `buffer-substring-no-properties`
- Since this only works properly with `ido-vertical-mode`, you should probably depend on that, and enable it explicitly while you're calling `ido-completing-read`

**Comment by danil** [comment]
@purcell 
> To strip properties, just use buffer-substring-no-properties

as a result of the `buffer-substring-no-properties` lost syntax highlighting
ido-occur-wb

> Since this only works properly with ido-vertical-mode,
> you should probably depend on that,
> and enable it explicitly while you're calling ido-completing-read

ok

**Comment by danil** [comment]
close pull request accidentally

**Comment by purcell** [comment]
Cool - you're just missing a `(provide 'ido-occur)` now.

**Comment by danil** [comment]
ok, thanks

**Pull request merged**
