### PR TITLE
Add recipe for squiggly-clojure

### PR DESCRIPTION
**Pull request by expez**
squiggly-clojure adds flycheck support for clojure code.

### CODE REVIEW

**Comment by mwfogleman** [comment]
Can we merge this recipe now that there are three separate checkers?

https://github.com/clojure-emacs/squiggly-clojure/issues/11

**Comment by purcell** [comment]
Just wrote this at clojure-emacs/squiggly-clojure#11:

> Now that everything is `flycheck-clojure-*` internally - which is great! - we can (and should) rename the file to `flycheck-clojure.el` before packaging it.

**Comment by expez** [comment]
Thanks @purcell!

**Comment by purcell** [comment]
@expez Thanks to the five or so people involved in this... :-)

**Pull request closed without merging**
