### PR TITLE
Added a recipe for runtests

### PR DESCRIPTION
**Pull request by sunesimonsen**
This pull request adds a recipe for my package runtests.

This Emacs extension will run an external script called runtests that should be in your path. If the script fails the output of the script will be shown with ansi colors. Simple and useful.

https://github.com/sunesimonsen/emacs-runtests/

Let me know if I'm submitting this the wrong way, this is my first Melpa package.

Kind regards
Sune

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- You should make the `runtests` command configurable with a standard `defcustom` var.
- I guess the mode-line colour thing is designed to flash the mode line green or red temporarily, but you note the original colour at load time, so this won't work with themes, which may redefine the mode line colour long after `runtests.el` was loaded. It would be safer to note the old colour just before changing it.
- The `(replace-regexp-in-string "\033\\[\\(38\\|48\\);5;[0-9]+m" "" ...)` looks  a bit odd to me, given that you're also using `ansi-color-apply-on-region`.

**Comment by sunesimonsen** [comment]
Thanks for the feedback, I'll fix the problems and get back to you. The reason for the regex replacement is that `ansi-color` does not seem to understand 256 ansi color escape sequences :-/ I'll put in a comment and improve the readme as well.

Kind regards
Sune

**Comment by sunesimonsen** [comment]
Mhh I should probably just switch to this library for xterm colors https://github.com/atomontage/xterm-color

**Comment by sunesimonsen** [comment]
@purcell thanks again for your feedback. I updated master with the following improvements:

* made the `runtests-command` customizable
* show colored messages in the minibuffer instead of flashing the modeline
* updated the readme
* updated the license to GPLv3

**Comment by purcell** [comment]
Awesome, thanks!

**Comment by sunesimonsen** [comment]
Thanks a lot for the great help, this is probably not my last package. Now I know the level of quality that is wanted, so I'll try to do a better upfront job the next time.

**Comment by purcell** [comment]
It's not that we have particular quality standards (though certain things *have* to be right for everything to work) -- rather, I think the recipe PRs are a great opportunity to polish the code for a package before it starts being available to all the MELPA users, so that they get a good first impression. That way, everyone wins. :-)

**Comment by sunesimonsen** [comment]
It is really impressive to have this kind of curating process for such a large package repository. I definitely agree that it yields the best result.

**Comment by sunesimonsen** [comment]
@purcell may I ask one more thing, when will the package be available through melpa?

**Comment by purcell** [comment]
Usually within a couple of hours -- that's about how long the build cycle is. Looks like it built successfully 9 mins ago, so it's currently available for installation. :-)

**Comment by sunesimonsen** [comment]
Thanks, awesome. Now I can find it :-)

**Pull request merged**
