### PR TITLE
Add C-c-combo Recipe

### PR DESCRIPTION
**Pull request by CestDiego**
This package will make announcer sounds if you are over certain WPM

### CODE REVIEW

**Comment by purcell** [comment]
Fun, but no capitals in package or symbol names please.

**Comment by CestDiego** [comment]
I made the changes.

**Comment by CestDiego** [comment]
@purcell I forgot about the capitals in packages rule.

**Comment by purcell** [comment]
Thanks. You'll also need to prefix all top-level symbols with the package prefix, e.g. `get-announcer-file-paths` -> `c-c-combo--get-announcer-file-paths`

**Comment by purcell** [comment]
(I think that's the only one, actually.)

**Comment by CestDiego** [comment]
Woops I missed that one.

**Comment by CestDiego** [comment]
Done @purcell

**Comment by purcell** [comment]
Thanks.

**Pull request merged**
