### PR TITLE
Please merge wmp, a window manuplation package.

### PR DESCRIPTION
**Pull request by dme**
First time caller - please give feedback.

### CODE REVIEW

**Comment by Fanael** [comment]
[Variadic arithmetic comparison operators](https://github.com/xuchunyang/chinese-word-at-point.el/blob/4697803c24f2e4b6f92271a84ee03c9aaa98b067/chinese-word-at-point.el#L68) were introduced in Emacs 24.4.

**Comment by purcell** [comment]
@Fanael -- did you mean to leave this on #2385?

**Comment by purcell** [comment]
@dme Thanks for this. Looks good from a packaging point of view, but I think the code could be improved: the `global-set-key` is a smell.  Consider creating a global minor mode, and create a prefix map: this way, you can have a simple keymap containing the `<up>`, `<down>` commands etc, and put that map inside a prefix map with a configurable prefix key. See the [elisp manual's page on the topic](https://www.gnu.org/software/emacs/manual/html_node/emacs/Prefix-Keymaps.html) for more info.

**Comment by Fanael** [comment]
> @Fanael -- did you mean to leave this on #2385?

Yes.

(this comment will self-destruct)

**Comment by dme** [comment]
On Fri, Jan 09 2015, Steve Purcell wrote:
> @dme Thanks for this. Looks good from a packaging point of view, but I
> think the code could be improved: the `global-set-key` is a smell.
> Consider creating a global minor mode, and create a prefix map: this
> way, you can have a simple keymap containing the `<up>`, `<down>`
> commands etc, and put that map inside a prefix map with a configurable
> prefix key. See the [elisp manual's page on the
> topic](https://www.gnu.org/software/emacs/manual/html_node/emacs/Prefix-Keymaps.html)
> for more info.

Steve, thanks for the feedback. I will go and look at doing that.

**Comment by milkypostman** [comment]
@dme any word on this?

**Comment by dme** [comment]
Too busy with day job and life, sorry. Still using the original code, and hope to get back to the suggested improvements at some point. If you want to close the issue, please do and I will re-start things when I'm ready.

**Pull request closed without merging**
