### PR TITLE
bitbake: add bitbake-el recipes

### PR DESCRIPTION
**Pull request by coldnew**
Add bitbake-el recipes for yocto's bb file support.

Signed-off-by: Yen-Chin Lee <coldnew.tw@gmail.com>

### CODE REVIEW

**Comment by purcell** [comment]
- That package is missing dependency declarations on `s` and `mmm-mode`.
- A short `Commentary` would be helpful

**Comment by purcell** [comment]
- The symbol prefix should be `bitbake-`, rather than `bb-` -- there's really no need to abbreviate such a short prefix, because it just introduces the chance of clashes with other packages.
- It seems like an autoload or two for the main interactive commands would be a good idea

**Comment by canatella** [comment]
I'm not working on any bitbake project at the moment so I do not have much time to update the package. I'll try to have a look asap but in the mean time, coldnew, if you have a bit of spare time to update the package with the requested fixes, feel free to fork and issue me a pull request, I'll gladly merge it.

**Comment by coldnew** [comment]
@canatella Ok, I'll make pull-request these days, thanks for the nice packages :)

**Comment by canatella** [comment]
Pong
I'll try to merge this soon

Le jeu. 24 déc. 2015 08:48, Donald Curtis <notifications@github.com> a
écrit :

**Comment by canatella** [comment]
I've changed the prefix and added autoloads for the function referenced in the readme. The commentary section has been extended and the missing dependencies has been added thanks to @coldnew. 

I'm not working with bitbake these days, @coldnew, @milkypostman, could you give the new version a try ? Thanks.

**Comment by coldnew** [comment]
@canatella I add some PR to your latest commit, please help me review it.

**Comment by coldnew** [comment]
@canatella I have test it and it's work well in my PC, thanks for the nice package :)

**Comment by purcell** [comment]
Thanks folks!

**Pull request merged**
