### PR TITLE
recipes/timer-revert: add new package.

### PR DESCRIPTION
**Pull request by yyr**

### CODE REVIEW

**Comment by purcell** [comment]
The recipe says `ncl-mode`. Did you try building locally? It should have failed with an error.

**Comment by purcell** [comment]
Some feedback re. the code:

- You should provide a `defgroup` as well as the `defcustom`s, so that you can specify where in the customization hierarchy the settings will be found.
- You use `defvar-local`, which is only in Emacs 24.4 and greater, so you must either list `(emacs "24.4")` in the `Package-Requires` header, or (better) just use the old-fashioned combination of `defvar` and `make-variable-buffer-local`.
- Same for `setq-local`: just use `(set (make-local-variable 'varname) value)` instead.
- `M-x checkdoc` (or `flycheck`) will give you feedback about how to format the docstrings: they're not quite compliant with the conventions in their current form. :-)

Hope that helps!

**Comment by yyr** [comment]
Uff,  That was quick. steve, is it really you? or a bot?

> The recipe says ncl-mode. 

Sorry about that after pushing I noticed that. fixed it now. 

Did you try building locally? 
I did it now. seems working.

**Comment by purcell** [comment]
> Uff, That was quick. steve, is it really you? or a bot?

Hard to say. Perhaps I've just passed the Turing test.

**Comment by yyr** [comment]
> You should provide a defgroup as well as the defcustoms, so that you can specify where in the customization hierarchy the settings will be found.
> You use defvar-local, which is only in Emacs 24.4 and greater, so you must either list (emacs "24.4") in the Package-Requires header, or (better) just use the old-fashioned combination of defvar and make-variable-buffer-local.
> Same for setq-local: just use (set (make-local-variable 'varname) value) instead.

I will make it compatible with older emacsen in subsequent commits. But that doesn't relate to this pull, right? 


>      M-x checkdoc (or flycheck) will give you feedback about how to format the docstrings: they're not quite compliant with the conventions in their current form. :-)



I did that. Seems fine.

**Comment by purcell** [comment]
> I will make it compatible with older emacsen in subsequent commits. But that doesn't relate to this pull, right?

It will be installable for most people right now, but it won't actually work unless they have Emacs 24.4. So I think that should be fixed up *before* distributing the code widely via MELPA.

> I did that. Seems fine.

Hmm. I'd have expected it to complain about the missing capitalization and trailing period on this line: https://github.com/yyr/timer-revert/blob/master/timer-revert.el#L88

In any case, that's not a blocker for MELPA inclusion -- just pointing it out.

**Comment by yyr** [comment]
Okay I finished that. may you could merge now?

I wonder why travis builds are failing?

**Comment by yyr** [comment]
Oh,  It looks travis setup is broken.

**Comment by purcell** [comment]
Great, thanks.



> Oh, It looks travis setup is broken.

Yep, need to investigate that separately. :-)

**Pull request merged**
