### PR TITLE
Add missing magit.el

### PR DESCRIPTION
**Pull request by syohex**
See
- https://github.com/milkypostman/melpa/pull/3490#discussion_r49564716

### CODE REVIEW

**Comment by Silex** [comment]
@purcell: please merge this, magit installations are broken atm.

**Comment by iainbeeston** [comment]
I can confirm that.

**Comment by twillis** [comment]
what's the eta usually for these landing on melpa?

**Comment by mrkkrp** [comment]
What about `with-editor.el`?

**Comment by dunn** [comment]
@mrkkrp that's distributed as a separate package: https://github.com/milkypostman/melpa/blob/master/recipes/with-editor

**Comment by purcell** [comment]
Thanks all, sorry for the inconvenience -- I'd suggested the wrong wildcard to @syohex, who was kind enough to write it up into this PR.

**Comment by purcell** [comment]
I've forced an immediate build of the package too, since many people rely on it.

**Comment by zackp30** [comment]
@purcell Did the package fail to build? Can't see any update from the Twitter feed or in <kbd>M-x list-packages RET</kbd>.

**Comment by Superbil** [comment]
@zackp30 Try to reinstall magit, that will fix problem.

**Comment by syohex** [comment]
Thanks :+1:

**Pull request merged**
