### PR TITLE
Add recipe for eno

### PR DESCRIPTION
**Pull request by enoson**
This package provides functions to goto/copy/cut.. word/symbol/line.. in view, kind of similar to ace-jump.

repo: https://github.com/enoson/eno.el

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. I sent you a small patch in https://github.com/enoson/eno.el/pull/1, but more importantly you need to make sure all the top level symbols are properly prefixed with `eno-` (or `eno--` for package-private symbols), in order to follow the [elisp conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).

**Comment by mrkkrp** [comment]
As a potential user of this, I don't get how it's better than [avy](https://github.com/abo-abo/avy) for example. You say:

> ace-jump/easymotion provides "goto certain char in view", which let us moving without mouse, but it's still not efficient or intuitive enough

But personally I cannot understand what is so inefficient in `ace-jump` that's fixed in `eno`, it's not clear from screenshots without descriptions.

**Comment by enoson** [comment]
@purcell merged and added prefix.

@mrkkrp actually the goto-line is the same, and `eno-word-goto` is the same as `avy-goto-word-0`, but  `eno-word-copy` will also copy the word which saves one key press. and there are symbol/string/paren  which avy/ace-jump didn't provide.

**Comment by purcell** [comment]
Thanks. What's `same-finger-list`? It's odd that it's getting set globally at the top level [here](https://github.com/enoson/eno.el/blob/master/eno.el#L509).

**Comment by enoson** [comment]
@purcell I missed that out, prefixed now. 
(it's list of same finger letters, e.g. if you set it as '("qa" "ws"), then the hint "qa", "aq", "ws" and "sw" won't show.)

**Comment by purcell** [comment]
ok, thanks

**Pull request merged**
