### PR TITLE
add receipt for foreman-mode

### PR DESCRIPTION
**Pull request by zweifisch**
manage processes defined in `Procfile`
https://github.com/zweifisch/foreman-mode

### CODE REVIEW

**Comment by purcell** [comment]
You'll need to declare a dependency on the correct `emacs` version for `tabulated-list`, e.g. perhaps `(emacs "24")`.

**Comment by purcell** [comment]
Also:

- you have a `load-procfile` function. It should be called `foreman-load-procfile`.  Same for `find-procfile` etc.
- don't use `:` in var names; use `-` instead.
- consider adding an `;;;###autoload` for the main interactive entry point(s)

**Comment by zweifisch** [comment]
Thanks for the code review! I didn't know autoload. updated.

**Comment by purcell** [comment]
Great, thanks!

**Comment by purcell** [comment]
Looks useful, by the way. :-)

**Comment by rejeep** [comment]
@zweifisch FYI, I have a similar tool called prodigy (https://github.com/rejeep/prodigy.el). You can use that with foreman simply by running `foreman start` as command.

**Comment by purcell** [comment]
@rejeep Might be worth mentioning in the README for the benefit of google.

**Comment by rejeep** [comment]
@purcell Good idea! :) https://github.com/rejeep/prodigy.el/commit/700eb15293260fdfa2fc0cff38df600693b7e4e5

**Comment by zweifisch** [comment]
@rejeep Hi, foreman-mode is not a wrapper of the ruby program, and thus have some interesting feature like manipulating environment variables and start/stop single application. foreman-mode uses Procfile, which is simple and project oriented. prodigy looks more versatile and the gui looks much  better.

**Pull request merged**
