### PR TITLE
Add recipe

### PR DESCRIPTION
**Pull request by wasamasa**
Emacs port of [vim-molasses](https://github.com/0x0dea/vim-molasses) I've made.

### CODE REVIEW

**Comment by xuchunyang** [comment]
Repo: https://github.com/wasamasa/jammer

so your `:repo` should be `wasamasa/jammer`, not `wasamasa/fetcher`

**Comment by wasamasa** [comment]
@xuchunyang Thanks, fixed.

**Comment by purcell** [comment]
Thanks. Maybe add an `;;;###autoload` for `jammer-mode`?

**Comment by wasamasa** [comment]
Done, not sure how I did overlook that.

**Pull request merged**
