### PR TITLE
Add markdown-preview-mode recipe

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
cf https://github.com/ancane/markdown-preview-mode/pull/5

Thanks in advance :smiley:

### CODE REVIEW

**Comment by milkypostman** [comment]
@AdrieanKhisbe yes I think we should cleanup the naming before merging. Despite me not being @purcell his guidance should be respected :)

**Comment by AdrieanKhisbe** [comment]
the prefix convertion is pending ;)

**Comment by milkypostman** [comment]
great, please ping when ready.

**Comment by AdrieanKhisbe** [comment]
Will do =)

**Comment by AdrieanKhisbe** [comment]
*voili voila voilou :smiley:* :speaker: :speech_balloon:

**Comment by ancane** [comment]
Hi @milkypostman. I confirm, with help from @AdrieanKhisbe :+1: we made `flycheck-package` happy.

**Comment by AdrieanKhisbe** [comment]
@milkypostman Good to go :smiley:

**Comment by AdrieanKhisbe** [comment]
great! =)
Thanks @milkypostman !

**Comment by ancane** [comment]
Thanks, guys!

**Pull request merged**
