### PR TITLE
Add lens

### PR DESCRIPTION
**Pull request by Fanael**

### CODE REVIEW

**Comment by Fanael** [comment]
LOL! This package actually found [a bug in flycheck-package](https://github.com/purcell/flycheck-package/commit/0ad0329a82ea9cc583ea0dd0f9140f5b0ec5d1bd)!

**Comment by Silex** [comment]
I don't get it... how can https://hackage.haskell.org/package/lens be similar to https://github.com/Fanael/lens.el/blob/master/lens.el?

I'm not doing much haskell so there's probably some information I'm missing :)

**Comment by Fanael** [comment]
It's a joke about lens's dependency tree. Lens is notorious for pulling in tons and tons of seemingly unrelated packages.

**Comment by Silex** [comment]
Oh, okay :laughing:

**Comment by purcell** [comment]
Is this worth adding to MELPA? Probably not, right?

**Comment by Fanael** [comment]
Hackage has acme-everything, which is the same thing, so why not?

You can also think of it as a unit test of MELPA scalability when faced with insane dependency lists.

**Comment by purcell** [comment]
Yeah, I think I'd want to see this package accurately described, then, ie. "lens.el --- installs absolutely everything in MELPA". Or even "melpa-everything.el". I don't want to be handling the complaints when people install this and then end up with all of MELPA installed.

**Comment by Silex** [comment]
I'd prefer `melpa-everything`, I'm afraid haskell ecosystem jokes don't translate that well to elisp :)

**Comment by tzz** [comment]
The package is confusing and useless to 99.999% of all users.  If it's a test, make it a test...

**Comment by purcell** [comment]
Yep, will decline this, but a submission of something similar called `melpa-everything` or `every-package` might be acceptable. :-)

**Pull request closed without merging**
