### PR TITLE
added recipe for real-auto-save

### PR DESCRIPTION
**Pull request by ChillarAnand**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this, but I'm not sure if it provides anything new: Emacs has `auto-save-mode` built-in, and with `auto-save-visited-file-name` set to `t`, the behaviour would be pretty much the same as with your code.

**Comment by ChillarAnand** [comment]
some packages & other configs (like whitespace cleanup, lint checking) use `after-save-hook` to perform some actions.

But `do-auto-save` doesn't trigger `after-save-hook`?

**Comment by purcell** [comment]
> But do-auto-save doesn't trigger after-save-hook?

Right. No, it doesn't, and in my view that's an Emacs bug. I just played around with code like the following, but it doesn't get executed (I believe) because you can't add advice to C functions:

```el
(defadvice do-auto-save (around maybe-run-after-save-hooks activate)
  (let (maybe-auto-save-buffers)
    (dolist (buf (buffer-list))
      (with-current-buffer buf
        (when (and auto-save-visited-file-name
                   (recent-auto-save-p)
                   (buffer-modified-p))
          (push buf maybe-auto-save-buffers))))
    ad-do-it
    (dolist (buf maybe-auto-save-buffers)
      (with-current-buffer buf
        (unless (buffer-modified-p)
          (message "Running after-save-hook in %s" (buffer-name))
          (run-hooks after-save-hook))))))
```

So yes, I can see the rationale for this code. Quick feedback then:

- You should fix the symbols so that they are all prefixed with `real-auto-save-` (e.g. `remove-buffer-from-alist` is currently unprefixed).
- Provide a proper minor mode instead of separate `turn-on` and `turn-off` functions -- that's what minor modes are for!
- Consider the case when `real-auto-save-interval` is changed after the timer has been started.
- The `real-auto-save-ignore-list` should be unnecessary: either the mode is enabled or it isn't, so if the user says "always enable real-auto-save in prog-mode", that's what should happen. There are any number of mechanisms by which the user can selectively enable or disable a minor mode in certain major modes or buffers.
- I'm guessing you should use `(save-buffer)` instead of `(write-file (buffer-file-name))`

Hope that helps!

**Comment by ChillarAnand** [comment]
> Consider the case when real-auto-save-interval is changed after the timer has been started.

I coudn't find any hooks to detect change in variables?

Remaining all issues were solved :smile:

**Comment by purcell** [comment]
I think the idea would be that whenever the timer function runs, it should cancel the timer and restart it using the current value of the interval variable.

Looks much better otherwise, except for a couple of issues:

- You're defining a function inside a function [here](https://github.com/ChillarAnand/real-auto-save/blob/master/real-auto-save.el#L80).
- You've marked the minor mode as global, but the body of it will only be executed once: the code which refers to `(buffer-file-name)` therefore makes no sense, because it will not be executed in each individual buffer. What you probably want to do is make it a non-global minor mode instead.
- The `Commentary:` text doesn't quite match the code now.

**Comment by ChillarAnand** [comment]
check it out once

**Comment by purcell** [comment]
Great - merged! Thanks. :-)

**Pull request merged**
