### PR TITLE
Rename docker recipe to docker-tramp

### PR DESCRIPTION
**Pull request by Silex**
Alright, we came to agreement in emacs-pe/docker-tramp.el#1.

This is the first step of #2782

You can merge this.

### CODE REVIEW

**Comment by purcell** [comment]
This should probably have an `:old-names (docker)` entry to indicate the renaming, right?

**Comment by Silex** [comment]
Okay, adding it, but this recipe is like 1-2 weeks old. I doubt many people installed it, and a new one named "docker" will replace it.

What does `:old-names` do by the way? Is it for when ugprading packages?

**Comment by Silex** [comment]
Alright, added `:old-names`.

**Comment by purcell** [comment]
Okay, thanks. When a new `docker` recipe is added, we should then remove the `:old-names`.

**Comment by purcell** [comment]
(`:old-names` is really just for download counts, and also for redirecting the package page, ie. http://melpa.org/#/docker)

**Comment by Silex** [comment]
Thanks!

**Pull request merged**
