### PR TITLE
Add recipe for dim

### PR DESCRIPTION
**Pull request by alezost**
Hello, would it be acceptable to add another package for setting
mode-line names of major and minor modes to MELPA?

### CODE REVIEW

**Comment by milkypostman** [comment]
it would but I suspect that @purcell is going to add what it adds over things like `diminish` (what other ones exist?).

**Comment by vyp** [comment]
@milkypostman [delight.el](http://www.emacswiki.org/emacs/delight.el)

**Comment by purcell** [comment]
Fine with me, since there's a good rational for not using `diminish` or `delight` in the author's case.

**Comment by alezost** [comment]
Thanks for merging!  I described my reasons for this package at https://github.com/alezost/dim.el#why

**Pull request merged**
