### PR TITLE
Add recipe for evil-smartparens

### PR DESCRIPTION
**Pull request by expez**

### CODE REVIEW

**Comment by purcell** [comment]
Please remove the :files spec from this recipe: the default already includes "*.el", and is therefore sufficient here. Ideally, you would amend the commit as necessary and force-push it back here to keep the PR commit history clean.

Re. the code itself, I don't think this package should `diminish` smartparens-mode in the modeline. That's the user's choice, and the dependency on `diminish` seems undesirable. You could use something like `ESP` for your lighter, and allow smartparens to handle indicating strict mode in its lighter. If the user wants to hide either, he can use `diminish`.

**Comment by expez** [comment]
I've removed the dynamic lighter and the dependence on `diminish` and `s`. The lighter is now simply `es` instead of replacing the smartparens lighter, which is either `SP` or `SP/s`, with `SP/e` and `SP/es`.  

I've not settled on the structure of the repo, so if it's OK with you I'd rather keep the `:files` there to explicitly list the single file I want packaged.  It's not like it's hurting anyone, nobody but machines are reading these package files after the merge anyway.

**Comment by purcell** [comment]
> I've removed the dynamic lighter and the dependence on diminish and s. The lighter is now simply es instead of replacing the smartparens lighter, which is either SP or SP/s, with SP/e and SP/es.

Great, I think that's better, and more idiomatic.

> I've not settled on the structure of the repo, so if it's OK with you I'd rather keep the :files there to explicitly list the single file I want packaged. It's not like it's hurting anyone, nobody but machines are reading these package files after the merge anyway.

Conversely, if you leave it there then you'll have to ping us if you add another file to be packaged. I don't think that's any better. We work from the reasonable assumption that - by default - there's a 1-1 correspondence between your repo and the package we build. Also, don't forget that `*-test.el`, `*-tests.el` etc are ignored by default, and you can always put unrelated files in a subdir if you don't want them packaged.

So I'm not really sure I see why this `:files` spec is likely to help you overall.

**Comment by expez** [comment]
I've updated the recipe

**Comment by purcell** [comment]
Thanks!

**Comment by expez** [comment]
Thanks for the review.  Much appreciated!

**Pull request merged**
