### PR TITLE
Add mode-line-in-header

### PR DESCRIPTION
**Pull request by EricCrosson**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this. Quick feedback:

- `header-line-format` is already defined: I don't think this package should be trying to redefine it.
- I presume you're using `set-window-buffer` to trigger a mode/header-line update, but there's `force-mode-line-update` for this.

Overall I'm not completely sure this package is going to work reliably or provide much added value. For example, when toggling minor modes it presumably won't reflect the mode line changes in the header line.

**Comment by EricCrosson** [comment]
Thanks for your feedback. I just ran a quick test and `force-mode-line-update`works as advertised. Also, minor mode changes are reflected in the mode line in the header.

When changing major modes the mode line seems to be restored, but I think that's a pretty rare occasion on most buffers.

I'll look into using the built-in `header-line-format`.

**Comment by EricCrosson** [comment]
I see what you mean, and I removed the defcustom for `header-line-format`.
I'm done with edits due to your feedback.

**Comment by purcell** [comment]
Cool. Sent you a further fix in https://github.com/EricCrosson/mode-line-in-header/pull/2. Seems to work quite nicely! :-)

**Pull request merged**
