### PR TITLE
Add 0bl-mode

### PR DESCRIPTION
**Pull request by etu**
Hello, I would like to add a small layout-managing mode I've created.

### CODE REVIEW

**Comment by purcell** [comment]
Cool. Normally the `-mode` package name prefix is reserved for major modes, e.g. for programming languages, and it's somewhat bad practice to use it for minor modes. I've made that mistake before. Would you object to renaming the file/package to simply `0bl`? Also, please put some info in the `Commentary` section of the `.el` file: that section will be displayed to users who press `?` in the packages menu, and on the MELPA package page. The package is more likely to get used if it's easy to understand what it does.

I also think it would helpful to compare/contrast this package with widely-used facilities like Emacs' `window-configuration-to-register`, and popular packages like `elscreen`, `workgroups`, `window-layout` etc. Check those out if you haven't alread! :-)

Cheers,
-Steve

**Comment by etu** [comment]
I see, had no idea!

The `l` is short for `layout` so I could rename the entire thing to `0blayout` (which I intended to start with) but then assumed that `-mode` was best practice and shortened it.

The closest one I've seen to my mode is `eyebrowse` which I found after I've built mine. But then I decided to stick with mine anyways to learn more elisp.

I'll come up with something more constructive to add to the Commentary and come back with a new pull-request later today after adjusting things :)

~E

**Comment by purcell** [comment]
Great, yes, `0blayout` would be good. Just make sure to fix up everything inside the `.el` file so it all matches up. You can amend the recipe commit and force-push your MELPA branch to update this PR, if that's easier than creating a fresh PR. Either is fine with me. :-)

**Comment by etu** [comment]
Ok, there we go! Renamed the project earlier. And added a much better `Commentary` section. Thank's for the feedback :)

**Comment by purcell** [comment]
Thanks - added as a single commit in 6521ec4. :-)

**Pull request closed without merging**
