### PR TITLE
Add cycle-themes package

### PR DESCRIPTION
**Pull request by toroidal-code**
This commit adds the 'cycle-themes' package to the list of recipes.

### CODE REVIEW

**Comment by xuchunyang** [comment]
Repo direct link: https://github.com/toroidal-code/cycle-themes.el

`:repo` should be `toroidal-code/cycle-themes.el`, not `toroidal-code/cycle-themes`.

(Why didn't Travis CI find out this mistake?)

**Comment by toroidal-code** [comment]
whoops. it's cycle-themes on my local machine. Forgot about the .el extension here. Fixed and squashed.

**Comment by purcell** [comment]
> (Why didn't Travis CI find out this mistake?)

Travis doesn't build the recipes. It just checks basic recipe syntax.

**Comment by purcell** [comment]
Thanks for this. Quick feedback:

- You'll need to declare a package dependency on cl-lib:
```
;; Package-Requires: ((cl-lib "0.5"))
```
- You might also want to place the `defgroup` in `'appearance` rather than `'emacs`.
- `M-x checkdoc` will help you make the docstrings standards-compliant.

Otherwise, looks great. :-)

**Comment by toroidal-code** [comment]
Thanks for the help! Alright, everything should be good now.

**Comment by purcell** [comment]
Great, merged - thanks!

**Pull request merged**
