### PR TITLE
Add recipe for company-ansible

### PR DESCRIPTION
**Pull request by krzysztof-magosa**

### CODE REVIEW

**Comment by purcell** [comment]
Don't depend on version `1.0` of `cl-lib`, because that version is not installable separately from Emacs. Since you are already requiring a recent Emacs version, I suggest dropping the `cl-lib` dependency declaration.

**Comment by purcell** [comment]
Also, please put the `Keywords`/`Author` etc between the `Copyright` and the license info in order to fit with conventions. (Enabling `auto-insert-mode` will help you to create the correct boilerplate in future.)

**Comment by krzysztof-magosa** [comment]
Thank you for your feedback.
Issues fixed, please review again.

Cheers.

**Comment by purcell** [comment]
Thanks! Merged.

**Pull request merged**
