### PR TITLE
Add markdown-preview-eww

### PR DESCRIPTION
**Pull request by izuo**
This is markdown realtime preview by eww. 
more detail: https://github.com/niku/realtime-preview.el

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
LGTM

**Comment by purcell** [comment]
Thanks for this. I think that the name "realtime-preview" is too general: perhaps "markdown-preview-eww" would be clearer? It would also fit better with https://github.com/ancane/markdown-preview-mode, which we're also adding to MELPA.

**Comment by izuo** [comment]
Thanks, I agree to that.

**Comment by izuo** [comment]
Oops

**Pull request closed without merging**
