### PR TITLE
Update racer recipe to reflect new project home

### PR DESCRIPTION
**Pull request by phildawes**
We've just moved the racer emacs mode out of the racer repo into it's own project. I hope I've done this right!  -Thanks

### CODE REVIEW

**Comment by Wilfred** [comment]
Looks good to me! I believe MELPA picks up all *.el files by default, so we don't need to explicitly specify it here.

**Comment by purcell** [comment]
Correct, the `:files` spec should be removed here please. Ideally, amend the commit and force-push it to keep the history clean.

**Comment by fbergroth** [comment]
@phildawes ping :)

**Comment by phildawes** [comment]
Oops sorry, I've updated the patch to remove the :files section

**Pull request merged**
