### PR TITLE
Added CFF recipe

### PR DESCRIPTION
**Pull request by fourier**
A simple package to search C/C++ headers file by source file and vice versa in a typical different tree in git/svn repository. Allows to search using simple regexp/rules, like for a **file.cpp** file in **src** directory find the corresponding **file.h/hpp** file in *closest* **inc** directory.

### CODE REVIEW

**Comment by fourier** [comment]
Can't find why it is fail (no fails on my package). Can you please take a look?

**Comment by fourier** [comment]
Any ideas why it seems to be broken? Cannot find anything related to cff.

**Comment by purcell** [comment]
Nope, the build is a spurious failure, but you'll need the fix I sent you in https://github.com/fourier/cff/pull/1 so that we can merge.

**Comment by fourier** [comment]
Updated, thanks.

**Comment by purcell** [comment]
Super - merged!

**Pull request merged**
