### PR TITLE
Add recipe for MHC

### PR DESCRIPTION
**Pull request by yoshinari-nomura**
I'm author and maintainer of MHC.
Repository is: https://github.com/yoshinari-nomura/mhc

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Why not just `"emacs/mhc*.el"`? Not sure why you need two patterns.

**Comment by yoshinari-nomura** [comment]
Because `mhc.el` is the main elisp file of this package, so I wanted to list up first.
Is it meaningless ?

**Comment by purcell** [comment]
Yes, the order is unimportant. Perhaps you can amend the recipe commit and force-push it?

**Comment by yoshinari-nomura** [comment]
Thanks.
I amended my commit. Please check again.

**Comment by purcell** [comment]
Great - thanks!

**Comment by yoshinari-nomura** [comment]
Thank you very much!

**Pull request merged**
