### PR TITLE
Add quick-preview recipe

### PR DESCRIPTION
**Pull request by myuhe**

### CODE REVIEW

**Comment by purcell** [comment]
Don't forget the `(provide ...)` form!

**Comment by myuhe** [comment]
Thanks. Fixed it. https://github.com/myuhe/quick-preview.el/commit/83484998177ef8903b5bd7eaa983ea28dcdaa5c1

**Comment by myuhe** [comment]
Ping.

**Comment by purcell** [comment]
Thanks. Sorry about the delay.

**Comment by myuhe** [comment]
Thanks :+1:

**Pull request merged**
