### PR TITLE
Add bury-successful-compilation-buffer-mode

### PR DESCRIPTION
**Pull request by EricCrosson**

### CODE REVIEW

**Comment by purcell** [comment]
Can we maybe rename this to simply `bury-successful-compilation`? The current name is getting a bit out of control. ;-)

(With that renaming, you could also just use `bury-successful-compilation-` instead of the `bcsb-` prefix.)

**Comment by EricCrosson** [comment]
I agree with the name getting out of control, but I wasn't having any more luck finding a clear name and trying to mesh with mode naming conventions. Thanks for the feedback, changes have been pushed!

**Comment by purcell** [comment]
What's the plan here? I see you picked the middle ground of removing `-mode` but not `-buffer-mode` as I suggested. If you consider this ready to add, I'll go ahead and take care of the recipe.

-Steve

P.S. Re. mode naming conventions, it's only really conventional to include `-mode` in the name of a library when the library provides a major mode. In most other cases I believe it's discouraged.

**Comment by EricCrosson** [comment]
I myself grew confused with the long namespace and didn't notice your suggestion included dropping two words. I've made my final changes but messed up this fork; I pushed with a -f and the 'reopen and comment' button is not active.

I opened another pull-request as I don't know how to fix this one.
Thanks again,
Eric

**Comment by purcell** [comment]
No problem. I added a recipe myself in f66e2e2. :)

Thanks for your patience.

**Pull request closed without merging**
