### PR TITLE
Add recipe: company-web

### PR DESCRIPTION
**Pull request by osv**
Same as ac-html, but `company` completion framework used.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

Now, this depends on `ac-html`, and therefore `auto-complete` -- that doesn't seem ideal, since people use either `company` or `auto-complete` and shouldn't need to have both installed. You should probably just copy the data you need from `ac-html`.

Also, you've got `company-web-...` names in `company-web.el` (good!), and `company-web/...` in the other files - not so good! It'd be worth renaming those `/` symbols to fit the elisp conventions.

**Comment by osv** [comment]
>in the other files - not so good! It'd be worth renaming those / symbols to fit the elisp conventions.

Done, I rename symbols to company-web-XXXX-foo-bar.

>You should probably just copy the data you need from

Yes, it depends on `ac-html`, but `auto-complete` is not required.
I need not only copy of data, but variable `ac-html-source-dirs` (in `ac-html` pkg) that used by other packages `ac-html-bootstrap` and `ac-html-csswatcher`.  And after apply this pull req. I wanted (as owner those packages) create aliasses for `ac-html-csswatcher+` and `ac-html-bootstrap+`: `company-web-csswatcher+`, `company-web-bootstrap+` and leave package names untouched with prefix `ac-html-...` I don't want create packages `company-web-bootstrap` and  `company-web-csswatcher`

So, if I just copy data like you say:
* create var company-web-source-dirs instead of ac-html-source-dirs.
* I need remove from `ac-html-csswatcher`, `ac-html-bootstrap` depend on ac-html too:
```lisp
;; Package-Requires: ((ac-html "0.3.0"))
```
* add to `ac-html-csswatcher`, `ac-html-bootstrap` function related to `company-web`
* update Commentary of `ac-html-csswatcher`, `ac-html-bootstrap` about choice: `ac-html` or `company-web` framework.

If no reply here I will do it tomorrow.

**Comment by purcell** [comment]
> Yes, it depends on ac-html, but auto-complete is not required.

But `ac-html` depends on `auto-complete`, so `auto-complete` will be installed.

Any common data could be put in a new package (e.g. `web-completion-data`), upon which `ac-html` and `company-web` etc. could depend

**Comment by osv** [comment]
yes, creating 3rd package (like you say `web-completion-data`) may be other way and better for maintaining completion data. I contact author of `ac-html` if he ok with it, I prepare package.

**Comment by osv** [comment]
I remove depend on `ac-html`, and add require `web-completion-data` https://github.com/milkypostman/melpa/pull/2739

**Comment by purcell** [comment]
Great! Merged.

**Pull request merged**
