### PR TITLE
add babeljs-repl package

### PR DESCRIPTION
**Pull request by hung-phan**
I create a package for emacs to support for javascript compiler (https://babeljs.io) in https://github.com/hung-phan/babeljs-repl.el/.

### CODE REVIEW

**Comment by purcell** [comment]
The package name is `babeljs-repl`, but the symbols all have the `babel-` prefix. The two names should match up, according to the [elisp conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html). I suggest you call the package `babeljs` instead, so rename to `babeljs.el`, and then rename the symbols so that they all have the `babeljs-` prefix. Hope that helps.

**Comment by hung-phan** [comment]
Thanks @purcell will fix this.

**Comment by hung-phan** [comment]
Already updated

**Comment by purcell** [comment]
Thanks, squashed into a single commit and applied in dfd4ac0.

**Pull request closed without merging**
