### PR TITLE
add pixie-mode

### PR DESCRIPTION
**Pull request by mpenet**
adding https://github.com/johnwalker/pixie-mode for https://github.com/pixie-lang/pixie

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Pending https://github.com/johnwalker/pixie-mode/pull/2

**Comment by purcell** [comment]
Oh, and https://github.com/johnwalker/pixie-mode/pull/3.

**Comment by mpenet** [comment]
:+1:

**Comment by johnwalker** [comment]
Oh wow, thanks @purcell, @mpenet. I was concerned that this would be too small for inclusion in melpa.

**Comment by purcell** [comment]
> I was concerned that this would be too small for inclusion in melpa.

Worth putting in if it's well-packages and useful to multiple people. I think this qualifies, even if it's small. :-)

**Comment by johnwalker** [comment]
I appreciate it. Thanks for your PRs, I always learn a lot from your elisp.

**Comment by purcell** [comment]
Always happy to help.

**Pull request merged**
