### PR TITLE
Add recipe for hoa-mode

### PR DESCRIPTION
**Pull request by adl**
This is a major mode for editing files in the [Hanoi Omega Automaton](http://adl.github.io/hoaf/) format.

Sources at https://gitlab.lrde.epita.fr/spot/emacs-modes/blob/master/hoa-mode.el
I'm the author.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. I'd strongly encourage you to use `define-derived-mode` to declare the major mode, because it will allow you to remove a bunch of boilerplate: you could remove the hook definition, and

```el
;;;### autoload
(defun hoa-mode ()
  "Major mode for editing files in the Hanoi Omega Automata format.

See URL `http://adl.github.io/hoaf/' for a definition of that format.

The following key bindings are installed in hoa-mode:

\\{hoa-mode-map}

By default the `hoa-display-automaton-at-point' function requires
extra software (Spot and GraphViz), but can be configured to use
other tools.  See that function for details."
  (interactive)
  (kill-all-local-variables)
  (set-syntax-table hoa-mode-syntax-table)
  (setq font-lock-defaults '((hoa-font-lock-keywords-1
			      hoa-font-lock-keywords-1
			      hoa-font-lock-keywords-2))
	major-mode 'hoa-mode
	mode-name "HOA")
  (use-local-map hoa-mode-map)
  (run-hooks 'hoa-mode-hook))
```

would turn into something like:

```el
;;;### autoload
(define-derived-mode hoa-mode fundamental-mode "HOA"
  "Major mode for editing files in the Hanoi Omega Automata format.

See URL `http://adl.github.io/hoaf/' for a definition of that format.

The following key bindings are installed in hoa-mode:

\\{hoa-mode-map}

By default the `hoa-display-automaton-at-point' function requires
extra software (Spot and GraphViz), but can be configured to use
other tools.  See that function for details."
  (setq font-lock-defaults '((hoa-font-lock-keywords-1
			      hoa-font-lock-keywords-1
			      hoa-font-lock-keywords-2))))
```

**Comment by adl** [comment]
Thank you for the useful suggestion.  I've simplified that code.

**Comment by tarsius** [comment]
@adl This package cannot be updated anymore.

```
fatal: unable to access 'https://gitlab.lrde.epita.fr/spot/emacs-modes.git/': SSL: certificate subject name (gitlab.lre.epita.fr) does not match target host name 'gitlab.lrde.epita.fr'
```

**Comment by adl** [comment]
We can use the new address https://gitlab.lre.epita.fr/spot/emacs-modes.git instead.  I'll forward the SSL certificate issue of the old address to our sysadmins.

**Comment by adl** [comment]
Cf. #9648

**Pull request merged**
