### PR TITLE
Add recipes for ac-html-csswatcher

### PR DESCRIPTION
**Pull request by osv**

### CODE REVIEW

**Comment by purcell** [comment]
The `:repo` value here looks incomplete. Did you actually try building this? ;-)

**Comment by osv** [comment]
Sorry!

**Comment by purcell** [comment]
Thanks. Squashed and committed in fba8b9b.

**Comment by purcell** [comment]
Thanks for closing this -- I forgot. :-)

**Comment by osv** [comment]
np :)

**Pull request closed without merging**
