### PR TITLE
Add css-comb recipe

### PR DESCRIPTION
**Pull request by channikhabra**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Pending https://github.com/channikhabra/css-comb.el/pull/1.

**Comment by purcell** [comment]
Thanks!

**Comment by channikhabra** [comment]
Thanks a lot for the pull request (and for merging this one)!

So you read every package submitted to elpa like that? That's damn awesome man! How do you manage the work-life balance and such dedication to FOSS?

**Comment by purcell** [comment]
> So you read every package submitted to elpa like that? 

Yep, at least a quick look. Helping new package authors is one reason why MELPA has succeeded, and benefits the whole community - including me!.

> That's damn awesome man! How do you manage the work-life balance and such dedication to FOSS?

I don't always balance it well. It becomes faster over time. These days I time-box my MELPA work.

**Comment by channikhabra** [comment]
> So you read every package submitted to elpa like that?
I meant MELPA (not so good with spellings).

Thanks a lot for the good work in FOSS! I aspire to be like you. But at the moment, my balance is even worst than my spellings. I mean work balance, not mental balance (although that's is sorta slim too, but not that bad).

**Comment by purcell** [comment]
Well, you're on the right track. Good luck on your journey. :-)

**Pull request merged**
