### PR TITLE
Add osx-dictionary

### PR DESCRIPTION
**Pull request by xuchunyang**
OSX Dictionary.app interface for Emacs

Link: https://github.com/xuchunyang/osx-dictionary.el

### CODE REVIEW

**Comment by purcell** [comment]
We don't include READMEs in packages, because people won't easily find or read them -- can I make a suggestion? Detect when the program is not available locally, and then offer to compile it for the user. Place the compiled program in the same directory as the package by default, and look for it there by default. Then the recipe can just include the `.el` and `.m` file, and everything will work easily out-of-the-box. :-)

**Comment by xuchunyang** [comment]
Thanks for you suggestion. I will remove README.md and compile `.m` file automatically from Emacs.

**Comment by xuchunyang** [comment]
I have remove README.md file.

**Comment by purcell** [comment]
Great!

**Pull request merged**
