### PR TITLE
Add emacs-fontawesome package

### PR DESCRIPTION
**Pull request by CestDiego**
Got authorization to post this from its original author,
https://github.com/syohex/emacs-fontawesome/issues/1

Also, this is my first time publishing something to MELPA so please tell
me if there is something wrong, I ran the `C-c C-c` test and package
loads just fine. So there is that.

### CODE REVIEW

**Comment by purcell** [comment]
Looks good, but the `:files` spec is unnecessary; can you amend the recipe commit to remove it, then force-push the amended commit back here to update the PR cleanly?

**Comment by CestDiego** [comment]
ok right away.

**Comment by purcell** [comment]
Super, thanks.

**Comment by CestDiego** [comment]
Awesome :) thanks

**Pull request merged**
